#!/bin/sh
# Test whether the compiler is producing the right errors.
# Return a status of 0 (true) if everything is all right, and 1 otherwise.

. ../handle_options
. ../startup

eval mmake $mmakeopts depend || exit 1
eval mmake $mmakeopts -k check
checkstatus=$?

cat *.err_res > .allres
if test ! -s .allres -a "$checkstatus" = 0
then
	echo "the tests in the invalid directory succeeded"
	echo "mmakeopts=$mmakeopts"
	rm -f .allres
	. ../shutdown
	exit 0
else
	echo "the tests in the invalid directory failed"
	echo "mmakeopts=$mmakeopts"
	echo "the differences are:"
	cat .allres
	exit 1
fi
