       1:      1  1  CALL DET  debugger_test:main/2-0 
trace command [a|c|d|j|n|s] valid commands are:
 a: abort the current execution.
 c: continue to end, not printing the trace.
 d: continue to end, printing the trace.
 n: go to the next trace event.
 s: skip the current call, not printing trace.
 j: jump to end of current call, printing trace.
trace command [a|c|d|j|n|s] Pure Prolog Interpreter.

       2:      1  1  ELSE DET  debugger_test:main/2-0 c4;e;
trace command [a|c|d|j|n|s]        3:      2  2   CALL DET  debugger_test:database_init/1-0 
trace command [a|c|d|j|n|s]        4:      2  2   EXIT DET  debugger_test:database_init/1-0 
trace command [a|c|d|j|n|s]        5:      3  2   CALL DET  debugger_test:consult_list/5-0 
trace command [a|c|d|j|n|s]        6:      3  2   SWTC DET  debugger_test:consult_list/5-0 s1;
trace command [a|c|d|j|n|s]        7:      4  3    CALL DET  debugger_test:consult/5-0 
trace command [a|c|d|j|n|s] Consulting file `debugger_test.m'...
       8:      4  3    THEN DET  debugger_test:consult/5-0 c7;t;
trace command [a|c|d|j|n|s]        9:      5  4     CALL DET  debugger_test:consult_until_eof/4-0 
trace command [a|c|d|j|n|s]       10:      6  5      CALL DET  debugger_test:consult_until_eof_2/5-0 
trace command [a|c|d|j|n|s]       11:      6  5      SWTC DET  debugger_test:consult_until_eof_2/5-0 s3;
trace command [a|c|d|j|n|s]       12:      7  6       CALL DET  debugger_test:database_assert_clause/4-0 
trace command [a|c|d|j|n|s]       13:      7  6       ELSE DET  debugger_test:database_assert_clause/4-0 e;
trace command [a|c|d|j|n|s]       14:      7  6       EXIT DET  debugger_test:database_assert_clause/4-0 
trace command [a|c|d|j|n|s]       15:      8  6       CALL DET  debugger_test:consult_until_eof/4-0 
trace command [a|c|d|j|n|s]       16:      9  7        CALL DET  debugger_test:consult_until_eof_2/5-0 
trace command [a|c|d|j|n|s]       17:      9  7        SWTC DET  debugger_test:consult_until_eof_2/5-0 s3;
trace command [a|c|d|j|n|s]       18:     10  8         CALL DET  debugger_test:database_assert_clause/4-0 
trace command [a|c|d|j|n|s]       19:     10  8         ELSE DET  debugger_test:database_assert_clause/4-0 e;
trace command [a|c|d|j|n|s]       20:     10  8         EXIT DET  debugger_test:database_assert_clause/4-0 
trace command [a|c|d|j|n|s]       21:     11  8         CALL DET  debugger_test:consult_until_eof/4-0 
trace command [a|c|d|j|n|s]      681:     11  8         EXIT DET  debugger_test:consult_until_eof/4-0 
trace command [a|c|d|j|n|s]      682:      9  7        EXIT DET  debugger_test:consult_until_eof_2/5-0 
trace command [a|c|d|j|n|s]      683:      8  6       EXIT DET  debugger_test:consult_until_eof/4-0 
trace command [a|c|d|j|n|s] valid commands are:
 a: abort the current execution.
 c: continue to end, not printing the trace.
 d: continue to end, printing the trace.
 n: go to the next trace event.
 s: skip the current call, not printing trace.
 j: jump to end of current call, printing trace.
trace command [a|c|d|j|n|s]      684:      6  5      EXIT DET  debugger_test:consult_until_eof_2/5-0 
trace command [a|c|d|j|n|s]      685:      5  4     EXIT DET  debugger_test:consult_until_eof/4-0 
trace command [a|c|d|j|n|s]      686:      4  3    EXIT DET  debugger_test:consult/5-0 
trace command [a|c|d|j|n|s]      687:    259  3    CALL DET  debugger_test:consult_list/5-0 
trace command [a|c|d|j|n|s]      688:    259  3    SWTC DET  debugger_test:consult_list/5-0 s2;
     689:    259  3    EXIT DET  debugger_test:consult_list/5-0 
trace command [a|c|d|j|n|s]      690:      3  2   EXIT DET  debugger_test:consult_list/5-0 
trace command [a|c|d|j|n|s]      691:    260  2   CALL DET  debugger_test:main_loop/3-0 
trace command [a|c|d|j|n|s] ?-      692:    261  3    CALL DET  debugger_test:main_loop_2/4-0 
trace command [a|c|d|j|n|s]      693:    261  3    SWTC DET  debugger_test:main_loop_2/4-0 s3;
trace command [a|c|d|j|n|s]      694:    262  4     CALL NON  debugger_test:solve/4-0 
trace command [a|c|d|j|n|s]      695:    262  4     DISJ NON  debugger_test:solve/4-0 d1;
trace command [a|c|d|j|n|s]      696:    262  4     DISJ NON  debugger_test:solve/4-0 d2;
trace command [a|c|d|j|n|s]      697:    262  4     DISJ NON  debugger_test:solve/4-0 d3;
trace command [a|c|d|j|n|s]      698:    262  4     DISJ NON  debugger_test:solve/4-0 d4;
trace command [a|c|d|j|n|s]      699:    263  5      CALL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      700:    263  5      SWTC SEMI debugger_test:unify/4-0 s2;
     701:    263  5      SWTC SEMI debugger_test:unify/4-0 s2;c2;s1;
     702:    263  5      ELSE SEMI debugger_test:unify/4-0 s2;c2;s1;c2;e;
     703:    264  6       CALL SEMI debugger_test:occurs_list/3-0 
     704:    264  6       FAIL SEMI debugger_test:occurs_list/3-0 
     705:    263  5      EXIT SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      706:    262  4     EXIT NON  debugger_test:solve/4-0 
trace command [a|c|d|j|n|s]      707:    262  4     DISJ NON  debugger_test:solve/4-0 d5;
trace command [a|c|d|j|n|s]      708:    265  5      CALL NON  debugger_test:database_lookup_clause/5-0 
trace command [a|c|d|j|n|s]      709:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
trace command [a|c|d|j|n|s]      710:    266  5      CALL DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      711:    266  5      EXIT DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      712:    267  5      CALL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      713:    267  5      SWTC SEMI debugger_test:unify/4-0 s1;
     714:    267  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     715:    267  5      FAIL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      716:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
trace command [a|c|d|j|n|s]      717:    268  5      CALL DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      718:    268  5      EXIT DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      719:    269  5      CALL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      720:    269  5      SWTC SEMI debugger_test:unify/4-0 s1;
trace command [a|c|d|j|n|s]      721:    269  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
trace command [a|c|d|j|n|s]      722:    269  5      FAIL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      723:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
trace command [a|c|d|j|n|s]      724:    270  5      CALL DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      725:    270  5      EXIT DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      726:    271  5      CALL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      727:    271  5      SWTC SEMI debugger_test:unify/4-0 s1;
trace command [a|c|d|j|n|s]      728:    271  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
trace command [a|c|d|j|n|s]      729:    271  5      FAIL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      730:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
trace command [a|c|d|j|n|s]      731:    272  5      CALL DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      732:    272  5      EXIT DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      733:    273  5      CALL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      734:    273  5      SWTC SEMI debugger_test:unify/4-0 s1;
trace command [a|c|d|j|n|s]      735:    273  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
trace command [a|c|d|j|n|s]      736:    273  5      FAIL SEMI debugger_test:unify/4-0 
trace command [a|c|d|j|n|s]      737:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
trace command [a|c|d|j|n|s]      738:    274  5      CALL DET  debugger_test:rename_apart/5-0 
trace command [a|c|d|j|n|s]      739:    274  5      EXIT DET  debugger_test:rename_apart/5-0 
     740:    275  5      CALL SEMI debugger_test:unify/4-0 
     741:    275  5      SWTC SEMI debugger_test:unify/4-0 s1;
     742:    275  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     743:    275  5      FAIL SEMI debugger_test:unify/4-0 
     744:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     745:    276  5      CALL DET  debugger_test:rename_apart/5-0 
     746:    276  5      EXIT DET  debugger_test:rename_apart/5-0 
     747:    277  5      CALL SEMI debugger_test:unify/4-0 
     748:    277  5      SWTC SEMI debugger_test:unify/4-0 s1;
     749:    277  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     750:    277  5      FAIL SEMI debugger_test:unify/4-0 
     751:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     752:    278  5      CALL DET  debugger_test:rename_apart/5-0 
     753:    278  5      EXIT DET  debugger_test:rename_apart/5-0 
     754:    279  5      CALL SEMI debugger_test:unify/4-0 
     755:    279  5      SWTC SEMI debugger_test:unify/4-0 s1;
     756:    279  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     757:    279  5      FAIL SEMI debugger_test:unify/4-0 
     758:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     759:    280  5      CALL DET  debugger_test:rename_apart/5-0 
     760:    280  5      EXIT DET  debugger_test:rename_apart/5-0 
     761:    281  5      CALL SEMI debugger_test:unify/4-0 
     762:    281  5      SWTC SEMI debugger_test:unify/4-0 s1;
     763:    281  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     764:    281  5      FAIL SEMI debugger_test:unify/4-0 
     765:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     766:    282  5      CALL DET  debugger_test:rename_apart/5-0 
     767:    282  5      EXIT DET  debugger_test:rename_apart/5-0 
     768:    283  5      CALL SEMI debugger_test:unify/4-0 
     769:    283  5      SWTC SEMI debugger_test:unify/4-0 s1;
     770:    283  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     771:    283  5      FAIL SEMI debugger_test:unify/4-0 
     772:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     773:    284  5      CALL DET  debugger_test:rename_apart/5-0 
     774:    284  5      EXIT DET  debugger_test:rename_apart/5-0 
     775:    285  5      CALL SEMI debugger_test:unify/4-0 
     776:    285  5      SWTC SEMI debugger_test:unify/4-0 s1;
     777:    285  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     778:    285  5      FAIL SEMI debugger_test:unify/4-0 
     779:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     780:    286  5      CALL DET  debugger_test:rename_apart/5-0 
     781:    286  5      EXIT DET  debugger_test:rename_apart/5-0 
     782:    287  5      CALL SEMI debugger_test:unify/4-0 
     783:    287  5      SWTC SEMI debugger_test:unify/4-0 s1;
     784:    287  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     785:    287  5      FAIL SEMI debugger_test:unify/4-0 
     786:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     787:    288  5      CALL DET  debugger_test:rename_apart/5-0 
     788:    288  5      EXIT DET  debugger_test:rename_apart/5-0 
     789:    289  5      CALL SEMI debugger_test:unify/4-0 
     790:    289  5      SWTC SEMI debugger_test:unify/4-0 s1;
     791:    289  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     792:    289  5      FAIL SEMI debugger_test:unify/4-0 
     793:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     794:    290  5      CALL DET  debugger_test:rename_apart/5-0 
     795:    290  5      EXIT DET  debugger_test:rename_apart/5-0 
     796:    291  5      CALL SEMI debugger_test:unify/4-0 
     797:    291  5      SWTC SEMI debugger_test:unify/4-0 s1;
     798:    291  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     799:    291  5      FAIL SEMI debugger_test:unify/4-0 
     800:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     801:    292  5      CALL DET  debugger_test:rename_apart/5-0 
     802:    292  5      EXIT DET  debugger_test:rename_apart/5-0 
     803:    293  5      CALL SEMI debugger_test:unify/4-0 
     804:    293  5      SWTC SEMI debugger_test:unify/4-0 s1;
     805:    293  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     806:    293  5      FAIL SEMI debugger_test:unify/4-0 
     807:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     808:    294  5      CALL DET  debugger_test:rename_apart/5-0 
     809:    294  5      EXIT DET  debugger_test:rename_apart/5-0 
     810:    295  5      CALL SEMI debugger_test:unify/4-0 
     811:    295  5      SWTC SEMI debugger_test:unify/4-0 s1;
     812:    295  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     813:    295  5      FAIL SEMI debugger_test:unify/4-0 
     814:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     815:    296  5      CALL DET  debugger_test:rename_apart/5-0 
     816:    296  5      EXIT DET  debugger_test:rename_apart/5-0 
     817:    297  5      CALL SEMI debugger_test:unify/4-0 
     818:    297  5      SWTC SEMI debugger_test:unify/4-0 s1;
     819:    297  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     820:    297  5      FAIL SEMI debugger_test:unify/4-0 
     821:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     822:    298  5      CALL DET  debugger_test:rename_apart/5-0 
     823:    298  5      EXIT DET  debugger_test:rename_apart/5-0 
     824:    299  5      CALL SEMI debugger_test:unify/4-0 
     825:    299  5      SWTC SEMI debugger_test:unify/4-0 s1;
     826:    299  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     827:    299  5      FAIL SEMI debugger_test:unify/4-0 
     828:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     829:    300  5      CALL DET  debugger_test:rename_apart/5-0 
     830:    300  5      EXIT DET  debugger_test:rename_apart/5-0 
     831:    301  5      CALL SEMI debugger_test:unify/4-0 
     832:    301  5      SWTC SEMI debugger_test:unify/4-0 s1;
     833:    301  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     834:    301  5      FAIL SEMI debugger_test:unify/4-0 
     835:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     836:    302  5      CALL DET  debugger_test:rename_apart/5-0 
     837:    302  5      EXIT DET  debugger_test:rename_apart/5-0 
     838:    303  5      CALL SEMI debugger_test:unify/4-0 
     839:    303  5      SWTC SEMI debugger_test:unify/4-0 s1;
     840:    303  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     841:    303  5      FAIL SEMI debugger_test:unify/4-0 
     842:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     843:    304  5      CALL DET  debugger_test:rename_apart/5-0 
     844:    304  5      EXIT DET  debugger_test:rename_apart/5-0 
     845:    305  5      CALL SEMI debugger_test:unify/4-0 
     846:    305  5      SWTC SEMI debugger_test:unify/4-0 s1;
     847:    305  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     848:    305  5      FAIL SEMI debugger_test:unify/4-0 
     849:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     850:    306  5      CALL DET  debugger_test:rename_apart/5-0 
     851:    306  5      EXIT DET  debugger_test:rename_apart/5-0 
     852:    307  5      CALL SEMI debugger_test:unify/4-0 
     853:    307  5      SWTC SEMI debugger_test:unify/4-0 s1;
     854:    307  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     855:    307  5      FAIL SEMI debugger_test:unify/4-0 
     856:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     857:    308  5      CALL DET  debugger_test:rename_apart/5-0 
     858:    308  5      EXIT DET  debugger_test:rename_apart/5-0 
     859:    309  5      CALL SEMI debugger_test:unify/4-0 
     860:    309  5      SWTC SEMI debugger_test:unify/4-0 s1;
     861:    309  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     862:    309  5      FAIL SEMI debugger_test:unify/4-0 
     863:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     864:    310  5      CALL DET  debugger_test:rename_apart/5-0 
     865:    310  5      EXIT DET  debugger_test:rename_apart/5-0 
     866:    311  5      CALL SEMI debugger_test:unify/4-0 
     867:    311  5      SWTC SEMI debugger_test:unify/4-0 s1;
     868:    311  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     869:    311  5      FAIL SEMI debugger_test:unify/4-0 
     870:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     871:    312  5      CALL DET  debugger_test:rename_apart/5-0 
     872:    312  5      EXIT DET  debugger_test:rename_apart/5-0 
     873:    313  5      CALL SEMI debugger_test:unify/4-0 
     874:    313  5      SWTC SEMI debugger_test:unify/4-0 s1;
     875:    313  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     876:    313  5      FAIL SEMI debugger_test:unify/4-0 
     877:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     878:    314  5      CALL DET  debugger_test:rename_apart/5-0 
     879:    314  5      EXIT DET  debugger_test:rename_apart/5-0 
     880:    315  5      CALL SEMI debugger_test:unify/4-0 
     881:    315  5      SWTC SEMI debugger_test:unify/4-0 s1;
     882:    315  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     883:    315  5      FAIL SEMI debugger_test:unify/4-0 
     884:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     885:    316  5      CALL DET  debugger_test:rename_apart/5-0 
     886:    316  5      EXIT DET  debugger_test:rename_apart/5-0 
     887:    317  5      CALL SEMI debugger_test:unify/4-0 
     888:    317  5      SWTC SEMI debugger_test:unify/4-0 s1;
     889:    317  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     890:    317  5      FAIL SEMI debugger_test:unify/4-0 
     891:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     892:    318  5      CALL DET  debugger_test:rename_apart/5-0 
     893:    318  5      EXIT DET  debugger_test:rename_apart/5-0 
     894:    319  5      CALL SEMI debugger_test:unify/4-0 
     895:    319  5      SWTC SEMI debugger_test:unify/4-0 s1;
     896:    319  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     897:    319  5      FAIL SEMI debugger_test:unify/4-0 
     898:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     899:    320  5      CALL DET  debugger_test:rename_apart/5-0 
     900:    320  5      EXIT DET  debugger_test:rename_apart/5-0 
     901:    321  5      CALL SEMI debugger_test:unify/4-0 
     902:    321  5      SWTC SEMI debugger_test:unify/4-0 s1;
     903:    321  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     904:    321  5      FAIL SEMI debugger_test:unify/4-0 
     905:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     906:    322  5      CALL DET  debugger_test:rename_apart/5-0 
     907:    322  5      EXIT DET  debugger_test:rename_apart/5-0 
     908:    323  5      CALL SEMI debugger_test:unify/4-0 
     909:    323  5      SWTC SEMI debugger_test:unify/4-0 s1;
     910:    323  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     911:    323  5      FAIL SEMI debugger_test:unify/4-0 
     912:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     913:    324  5      CALL DET  debugger_test:rename_apart/5-0 
     914:    324  5      EXIT DET  debugger_test:rename_apart/5-0 
     915:    325  5      CALL SEMI debugger_test:unify/4-0 
     916:    325  5      SWTC SEMI debugger_test:unify/4-0 s1;
     917:    325  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     918:    325  5      FAIL SEMI debugger_test:unify/4-0 
     919:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     920:    326  5      CALL DET  debugger_test:rename_apart/5-0 
     921:    326  5      EXIT DET  debugger_test:rename_apart/5-0 
     922:    327  5      CALL SEMI debugger_test:unify/4-0 
     923:    327  5      SWTC SEMI debugger_test:unify/4-0 s1;
     924:    327  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     925:    327  5      FAIL SEMI debugger_test:unify/4-0 
     926:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     927:    328  5      CALL DET  debugger_test:rename_apart/5-0 
     928:    328  5      EXIT DET  debugger_test:rename_apart/5-0 
     929:    329  5      CALL SEMI debugger_test:unify/4-0 
     930:    329  5      SWTC SEMI debugger_test:unify/4-0 s1;
     931:    329  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     932:    329  5      FAIL SEMI debugger_test:unify/4-0 
     933:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     934:    330  5      CALL DET  debugger_test:rename_apart/5-0 
     935:    330  5      EXIT DET  debugger_test:rename_apart/5-0 
     936:    331  5      CALL SEMI debugger_test:unify/4-0 
     937:    331  5      SWTC SEMI debugger_test:unify/4-0 s1;
     938:    331  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     939:    331  5      FAIL SEMI debugger_test:unify/4-0 
     940:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     941:    332  5      CALL DET  debugger_test:rename_apart/5-0 
     942:    332  5      EXIT DET  debugger_test:rename_apart/5-0 
     943:    333  5      CALL SEMI debugger_test:unify/4-0 
     944:    333  5      SWTC SEMI debugger_test:unify/4-0 s1;
     945:    333  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     946:    333  5      FAIL SEMI debugger_test:unify/4-0 
     947:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     948:    334  5      CALL DET  debugger_test:rename_apart/5-0 
     949:    334  5      EXIT DET  debugger_test:rename_apart/5-0 
     950:    335  5      CALL SEMI debugger_test:unify/4-0 
     951:    335  5      SWTC SEMI debugger_test:unify/4-0 s1;
     952:    335  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     953:    335  5      FAIL SEMI debugger_test:unify/4-0 
     954:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     955:    336  5      CALL DET  debugger_test:rename_apart/5-0 
     956:    336  5      EXIT DET  debugger_test:rename_apart/5-0 
     957:    337  5      CALL SEMI debugger_test:unify/4-0 
     958:    337  5      SWTC SEMI debugger_test:unify/4-0 s1;
     959:    337  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     960:    337  5      FAIL SEMI debugger_test:unify/4-0 
     961:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     962:    338  5      CALL DET  debugger_test:rename_apart/5-0 
     963:    338  5      EXIT DET  debugger_test:rename_apart/5-0 
     964:    339  5      CALL SEMI debugger_test:unify/4-0 
     965:    339  5      SWTC SEMI debugger_test:unify/4-0 s1;
     966:    339  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     967:    339  5      FAIL SEMI debugger_test:unify/4-0 
     968:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     969:    340  5      CALL DET  debugger_test:rename_apart/5-0 
     970:    340  5      EXIT DET  debugger_test:rename_apart/5-0 
     971:    341  5      CALL SEMI debugger_test:unify/4-0 
     972:    341  5      SWTC SEMI debugger_test:unify/4-0 s1;
     973:    341  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     974:    341  5      FAIL SEMI debugger_test:unify/4-0 
     975:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     976:    342  5      CALL DET  debugger_test:rename_apart/5-0 
     977:    342  5      EXIT DET  debugger_test:rename_apart/5-0 
     978:    343  5      CALL SEMI debugger_test:unify/4-0 
     979:    343  5      SWTC SEMI debugger_test:unify/4-0 s1;
     980:    343  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     981:    343  5      FAIL SEMI debugger_test:unify/4-0 
     982:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     983:    344  5      CALL DET  debugger_test:rename_apart/5-0 
     984:    344  5      EXIT DET  debugger_test:rename_apart/5-0 
     985:    345  5      CALL SEMI debugger_test:unify/4-0 
     986:    345  5      SWTC SEMI debugger_test:unify/4-0 s1;
     987:    345  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     988:    345  5      FAIL SEMI debugger_test:unify/4-0 
     989:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     990:    346  5      CALL DET  debugger_test:rename_apart/5-0 
     991:    346  5      EXIT DET  debugger_test:rename_apart/5-0 
     992:    347  5      CALL SEMI debugger_test:unify/4-0 
     993:    347  5      SWTC SEMI debugger_test:unify/4-0 s1;
     994:    347  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
     995:    347  5      FAIL SEMI debugger_test:unify/4-0 
     996:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
     997:    348  5      CALL DET  debugger_test:rename_apart/5-0 
     998:    348  5      EXIT DET  debugger_test:rename_apart/5-0 
     999:    349  5      CALL SEMI debugger_test:unify/4-0 
    1000:    349  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1001:    349  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1002:    349  5      FAIL SEMI debugger_test:unify/4-0 
    1003:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1004:    350  5      CALL DET  debugger_test:rename_apart/5-0 
    1005:    350  5      EXIT DET  debugger_test:rename_apart/5-0 
    1006:    351  5      CALL SEMI debugger_test:unify/4-0 
    1007:    351  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1008:    351  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1009:    351  5      FAIL SEMI debugger_test:unify/4-0 
    1010:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1011:    352  5      CALL DET  debugger_test:rename_apart/5-0 
    1012:    352  5      EXIT DET  debugger_test:rename_apart/5-0 
    1013:    353  5      CALL SEMI debugger_test:unify/4-0 
    1014:    353  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1015:    353  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1016:    353  5      FAIL SEMI debugger_test:unify/4-0 
    1017:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1018:    354  5      CALL DET  debugger_test:rename_apart/5-0 
    1019:    354  5      EXIT DET  debugger_test:rename_apart/5-0 
    1020:    355  5      CALL SEMI debugger_test:unify/4-0 
    1021:    355  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1022:    355  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1023:    355  5      FAIL SEMI debugger_test:unify/4-0 
    1024:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1025:    356  5      CALL DET  debugger_test:rename_apart/5-0 
    1026:    356  5      EXIT DET  debugger_test:rename_apart/5-0 
    1027:    357  5      CALL SEMI debugger_test:unify/4-0 
    1028:    357  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1029:    357  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1030:    357  5      FAIL SEMI debugger_test:unify/4-0 
    1031:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1032:    358  5      CALL DET  debugger_test:rename_apart/5-0 
    1033:    358  5      EXIT DET  debugger_test:rename_apart/5-0 
    1034:    359  5      CALL SEMI debugger_test:unify/4-0 
    1035:    359  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1036:    359  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1037:    359  5      FAIL SEMI debugger_test:unify/4-0 
    1038:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1039:    360  5      CALL DET  debugger_test:rename_apart/5-0 
    1040:    360  5      EXIT DET  debugger_test:rename_apart/5-0 
    1041:    361  5      CALL SEMI debugger_test:unify/4-0 
    1042:    361  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1043:    361  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1044:    361  5      FAIL SEMI debugger_test:unify/4-0 
    1045:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1046:    362  5      CALL DET  debugger_test:rename_apart/5-0 
    1047:    362  5      EXIT DET  debugger_test:rename_apart/5-0 
    1048:    363  5      CALL SEMI debugger_test:unify/4-0 
    1049:    363  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1050:    363  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1051:    363  5      FAIL SEMI debugger_test:unify/4-0 
    1052:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1053:    364  5      CALL DET  debugger_test:rename_apart/5-0 
    1054:    364  5      EXIT DET  debugger_test:rename_apart/5-0 
    1055:    365  5      CALL SEMI debugger_test:unify/4-0 
    1056:    365  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1057:    365  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1058:    365  5      FAIL SEMI debugger_test:unify/4-0 
    1059:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1060:    366  5      CALL DET  debugger_test:rename_apart/5-0 
    1061:    366  5      EXIT DET  debugger_test:rename_apart/5-0 
    1062:    367  5      CALL SEMI debugger_test:unify/4-0 
    1063:    367  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1064:    367  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1065:    367  5      FAIL SEMI debugger_test:unify/4-0 
    1066:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1067:    368  5      CALL DET  debugger_test:rename_apart/5-0 
    1068:    368  5      EXIT DET  debugger_test:rename_apart/5-0 
    1069:    369  5      CALL SEMI debugger_test:unify/4-0 
    1070:    369  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1071:    369  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1072:    369  5      FAIL SEMI debugger_test:unify/4-0 
    1073:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1074:    370  5      CALL DET  debugger_test:rename_apart/5-0 
    1075:    370  5      EXIT DET  debugger_test:rename_apart/5-0 
    1076:    371  5      CALL SEMI debugger_test:unify/4-0 
    1077:    371  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1078:    371  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1079:    371  5      FAIL SEMI debugger_test:unify/4-0 
    1080:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1081:    372  5      CALL DET  debugger_test:rename_apart/5-0 
    1082:    372  5      EXIT DET  debugger_test:rename_apart/5-0 
    1083:    373  5      CALL SEMI debugger_test:unify/4-0 
    1084:    373  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1085:    373  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1086:    373  5      FAIL SEMI debugger_test:unify/4-0 
    1087:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1088:    374  5      CALL DET  debugger_test:rename_apart/5-0 
    1089:    374  5      EXIT DET  debugger_test:rename_apart/5-0 
    1090:    375  5      CALL SEMI debugger_test:unify/4-0 
    1091:    375  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1092:    375  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1093:    375  5      FAIL SEMI debugger_test:unify/4-0 
    1094:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1095:    376  5      CALL DET  debugger_test:rename_apart/5-0 
    1096:    376  5      EXIT DET  debugger_test:rename_apart/5-0 
    1097:    377  5      CALL SEMI debugger_test:unify/4-0 
    1098:    377  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1099:    377  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1100:    377  5      FAIL SEMI debugger_test:unify/4-0 
    1101:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1102:    378  5      CALL DET  debugger_test:rename_apart/5-0 
    1103:    378  5      EXIT DET  debugger_test:rename_apart/5-0 
    1104:    379  5      CALL SEMI debugger_test:unify/4-0 
    1105:    379  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1106:    379  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1107:    379  5      FAIL SEMI debugger_test:unify/4-0 
    1108:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1109:    380  5      CALL DET  debugger_test:rename_apart/5-0 
    1110:    380  5      EXIT DET  debugger_test:rename_apart/5-0 
    1111:    381  5      CALL SEMI debugger_test:unify/4-0 
    1112:    381  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1113:    381  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1114:    381  5      FAIL SEMI debugger_test:unify/4-0 
    1115:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1116:    382  5      CALL DET  debugger_test:rename_apart/5-0 
    1117:    382  5      EXIT DET  debugger_test:rename_apart/5-0 
    1118:    383  5      CALL SEMI debugger_test:unify/4-0 
    1119:    383  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1120:    383  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1121:    383  5      FAIL SEMI debugger_test:unify/4-0 
    1122:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1123:    384  5      CALL DET  debugger_test:rename_apart/5-0 
    1124:    384  5      EXIT DET  debugger_test:rename_apart/5-0 
    1125:    385  5      CALL SEMI debugger_test:unify/4-0 
    1126:    385  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1127:    385  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1128:    385  5      FAIL SEMI debugger_test:unify/4-0 
    1129:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1130:    386  5      CALL DET  debugger_test:rename_apart/5-0 
    1131:    386  5      EXIT DET  debugger_test:rename_apart/5-0 
    1132:    387  5      CALL SEMI debugger_test:unify/4-0 
    1133:    387  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1134:    387  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1135:    387  5      FAIL SEMI debugger_test:unify/4-0 
    1136:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1137:    388  5      CALL DET  debugger_test:rename_apart/5-0 
    1138:    388  5      EXIT DET  debugger_test:rename_apart/5-0 
    1139:    389  5      CALL SEMI debugger_test:unify/4-0 
    1140:    389  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1141:    389  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1142:    389  5      FAIL SEMI debugger_test:unify/4-0 
    1143:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1144:    390  5      CALL DET  debugger_test:rename_apart/5-0 
    1145:    390  5      EXIT DET  debugger_test:rename_apart/5-0 
    1146:    391  5      CALL SEMI debugger_test:unify/4-0 
    1147:    391  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1148:    391  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1149:    391  5      FAIL SEMI debugger_test:unify/4-0 
    1150:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1151:    392  5      CALL DET  debugger_test:rename_apart/5-0 
    1152:    392  5      EXIT DET  debugger_test:rename_apart/5-0 
    1153:    393  5      CALL SEMI debugger_test:unify/4-0 
    1154:    393  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1155:    393  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1156:    393  5      FAIL SEMI debugger_test:unify/4-0 
    1157:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1158:    394  5      CALL DET  debugger_test:rename_apart/5-0 
    1159:    394  5      EXIT DET  debugger_test:rename_apart/5-0 
    1160:    395  5      CALL SEMI debugger_test:unify/4-0 
    1161:    395  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1162:    395  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1163:    395  5      FAIL SEMI debugger_test:unify/4-0 
    1164:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1165:    396  5      CALL DET  debugger_test:rename_apart/5-0 
    1166:    396  5      EXIT DET  debugger_test:rename_apart/5-0 
    1167:    397  5      CALL SEMI debugger_test:unify/4-0 
    1168:    397  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1169:    397  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1170:    397  5      FAIL SEMI debugger_test:unify/4-0 
    1171:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1172:    398  5      CALL DET  debugger_test:rename_apart/5-0 
    1173:    398  5      EXIT DET  debugger_test:rename_apart/5-0 
    1174:    399  5      CALL SEMI debugger_test:unify/4-0 
    1175:    399  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1176:    399  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1177:    399  5      FAIL SEMI debugger_test:unify/4-0 
    1178:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1179:    400  5      CALL DET  debugger_test:rename_apart/5-0 
    1180:    400  5      EXIT DET  debugger_test:rename_apart/5-0 
    1181:    401  5      CALL SEMI debugger_test:unify/4-0 
    1182:    401  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1183:    401  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1184:    401  5      FAIL SEMI debugger_test:unify/4-0 
    1185:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1186:    402  5      CALL DET  debugger_test:rename_apart/5-0 
    1187:    402  5      EXIT DET  debugger_test:rename_apart/5-0 
    1188:    403  5      CALL SEMI debugger_test:unify/4-0 
    1189:    403  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1190:    403  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1191:    403  5      FAIL SEMI debugger_test:unify/4-0 
    1192:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1193:    404  5      CALL DET  debugger_test:rename_apart/5-0 
    1194:    404  5      EXIT DET  debugger_test:rename_apart/5-0 
    1195:    405  5      CALL SEMI debugger_test:unify/4-0 
    1196:    405  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1197:    405  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1198:    405  5      FAIL SEMI debugger_test:unify/4-0 
    1199:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1200:    406  5      CALL DET  debugger_test:rename_apart/5-0 
    1201:    406  5      EXIT DET  debugger_test:rename_apart/5-0 
    1202:    407  5      CALL SEMI debugger_test:unify/4-0 
    1203:    407  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1204:    407  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1205:    407  5      FAIL SEMI debugger_test:unify/4-0 
    1206:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1207:    408  5      CALL DET  debugger_test:rename_apart/5-0 
    1208:    408  5      EXIT DET  debugger_test:rename_apart/5-0 
    1209:    409  5      CALL SEMI debugger_test:unify/4-0 
    1210:    409  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1211:    409  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1212:    409  5      FAIL SEMI debugger_test:unify/4-0 
    1213:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1214:    410  5      CALL DET  debugger_test:rename_apart/5-0 
    1215:    410  5      EXIT DET  debugger_test:rename_apart/5-0 
    1216:    411  5      CALL SEMI debugger_test:unify/4-0 
    1217:    411  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1218:    411  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1219:    411  5      FAIL SEMI debugger_test:unify/4-0 
    1220:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1221:    412  5      CALL DET  debugger_test:rename_apart/5-0 
    1222:    412  5      EXIT DET  debugger_test:rename_apart/5-0 
    1223:    413  5      CALL SEMI debugger_test:unify/4-0 
    1224:    413  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1225:    413  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1226:    413  5      FAIL SEMI debugger_test:unify/4-0 
    1227:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1228:    414  5      CALL DET  debugger_test:rename_apart/5-0 
    1229:    414  5      EXIT DET  debugger_test:rename_apart/5-0 
    1230:    415  5      CALL SEMI debugger_test:unify/4-0 
    1231:    415  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1232:    415  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1233:    415  5      FAIL SEMI debugger_test:unify/4-0 
    1234:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1235:    416  5      CALL DET  debugger_test:rename_apart/5-0 
    1236:    416  5      EXIT DET  debugger_test:rename_apart/5-0 
    1237:    417  5      CALL SEMI debugger_test:unify/4-0 
    1238:    417  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1239:    417  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1240:    417  5      FAIL SEMI debugger_test:unify/4-0 
    1241:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1242:    418  5      CALL DET  debugger_test:rename_apart/5-0 
    1243:    418  5      EXIT DET  debugger_test:rename_apart/5-0 
    1244:    419  5      CALL SEMI debugger_test:unify/4-0 
    1245:    419  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1246:    419  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1247:    419  5      FAIL SEMI debugger_test:unify/4-0 
    1248:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1249:    420  5      CALL DET  debugger_test:rename_apart/5-0 
    1250:    420  5      EXIT DET  debugger_test:rename_apart/5-0 
    1251:    421  5      CALL SEMI debugger_test:unify/4-0 
    1252:    421  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1253:    421  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1254:    421  5      FAIL SEMI debugger_test:unify/4-0 
    1255:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1256:    422  5      CALL DET  debugger_test:rename_apart/5-0 
    1257:    422  5      EXIT DET  debugger_test:rename_apart/5-0 
    1258:    423  5      CALL SEMI debugger_test:unify/4-0 
    1259:    423  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1260:    423  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1261:    423  5      FAIL SEMI debugger_test:unify/4-0 
    1262:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1263:    424  5      CALL DET  debugger_test:rename_apart/5-0 
    1264:    424  5      EXIT DET  debugger_test:rename_apart/5-0 
    1265:    425  5      CALL SEMI debugger_test:unify/4-0 
    1266:    425  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1267:    425  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1268:    425  5      FAIL SEMI debugger_test:unify/4-0 
    1269:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1270:    426  5      CALL DET  debugger_test:rename_apart/5-0 
    1271:    426  5      EXIT DET  debugger_test:rename_apart/5-0 
    1272:    427  5      CALL SEMI debugger_test:unify/4-0 
    1273:    427  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1274:    427  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1275:    427  5      FAIL SEMI debugger_test:unify/4-0 
    1276:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1277:    428  5      CALL DET  debugger_test:rename_apart/5-0 
    1278:    428  5      EXIT DET  debugger_test:rename_apart/5-0 
    1279:    429  5      CALL SEMI debugger_test:unify/4-0 
    1280:    429  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1281:    429  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1282:    429  5      FAIL SEMI debugger_test:unify/4-0 
    1283:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1284:    430  5      CALL DET  debugger_test:rename_apart/5-0 
    1285:    430  5      EXIT DET  debugger_test:rename_apart/5-0 
    1286:    431  5      CALL SEMI debugger_test:unify/4-0 
    1287:    431  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1288:    431  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1289:    431  5      FAIL SEMI debugger_test:unify/4-0 
    1290:    265  5      EXIT NON  debugger_test:database_lookup_clause/5-0 
    1291:    432  5      CALL DET  debugger_test:rename_apart/5-0 
    1292:    432  5      EXIT DET  debugger_test:rename_apart/5-0 
    1293:    433  5      CALL SEMI debugger_test:unify/4-0 
    1294:    433  5      SWTC SEMI debugger_test:unify/4-0 s1;
    1295:    433  5      SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1296:    433  5      FAIL SEMI debugger_test:unify/4-0 
    1297:    262  4     FAIL NON  debugger_test:solve/4-0 
    1298:    434  4     CALL DET  debugger_test:write_solutions/4-0 
    1299:    434  4     ELSE DET  debugger_test:write_solutions/4-0 e;
    1300:    435  5      CALL DET  debugger_test:write_solutions_2/4-0 
    1301:    435  5      SWTC DET  debugger_test:write_solutions_2/4-0 s1;
1 = 1.
    1302:    436  6       CALL DET  debugger_test:write_solutions_2/4-0 
    1303:    436  6       SWTC DET  debugger_test:write_solutions_2/4-0 s2;
    1304:    436  6       EXIT DET  debugger_test:write_solutions_2/4-0 
    1305:    435  5      EXIT DET  debugger_test:write_solutions_2/4-0 
Yes.
    1306:    434  4     EXIT DET  debugger_test:write_solutions/4-0 
    1307:    437  4     CALL DET  debugger_test:main_loop/3-0 
?-     1308:    438  5      CALL DET  debugger_test:main_loop_2/4-0 
    1309:    438  5      SWTC DET  debugger_test:main_loop_2/4-0 s3;
    1310:    439  6       CALL NON  debugger_test:solve/4-0 
    1311:    439  6       DISJ NON  debugger_test:solve/4-0 d1;
    1312:    439  6       DISJ NON  debugger_test:solve/4-0 d2;
    1313:    439  6       DISJ NON  debugger_test:solve/4-0 d3;
    1314:    439  6       DISJ NON  debugger_test:solve/4-0 d4;
    1315:    440  7        CALL SEMI debugger_test:unify/4-0 
    1316:    440  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1317:    440  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1318:    441  8         CALL SEMI debugger_test:unify_list/4-0 
    1319:    441  8         SWTC SEMI debugger_test:unify_list/4-0 s1;
    1320:    442  9          CALL SEMI debugger_test:unify/4-0 
    1321:    442  9          SWTC SEMI debugger_test:unify/4-0 s1;
    1322:    442  9          SWTC SEMI debugger_test:unify/4-0 s1;c2;s2;
    1323:    442  9          ELSE SEMI debugger_test:unify/4-0 s1;c2;s2;c2;e;
    1324:    443 10           CALL SEMI debugger_test:occurs_list/3-0 
    1325:    443 10           FAIL SEMI debugger_test:occurs_list/3-0 
    1326:    442  9          EXIT SEMI debugger_test:unify/4-0 
    1327:    444  9          CALL SEMI debugger_test:unify_list/4-0 
    1328:    444  9          SWTC SEMI debugger_test:unify_list/4-0 s2;
    1329:    444  9          EXIT SEMI debugger_test:unify_list/4-0 
    1330:    441  8         EXIT SEMI debugger_test:unify_list/4-0 
    1331:    440  7        EXIT SEMI debugger_test:unify/4-0 
    1332:    439  6       EXIT NON  debugger_test:solve/4-0 
    1333:    439  6       DISJ NON  debugger_test:solve/4-0 d5;
    1334:    445  7        CALL NON  debugger_test:database_lookup_clause/5-0 
    1335:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1336:    446  7        CALL DET  debugger_test:rename_apart/5-0 
    1337:    446  7        EXIT DET  debugger_test:rename_apart/5-0 
    1338:    447  7        CALL SEMI debugger_test:unify/4-0 
    1339:    447  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1340:    447  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1341:    447  7        FAIL SEMI debugger_test:unify/4-0 
    1342:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1343:    448  7        CALL DET  debugger_test:rename_apart/5-0 
    1344:    448  7        EXIT DET  debugger_test:rename_apart/5-0 
    1345:    449  7        CALL SEMI debugger_test:unify/4-0 
    1346:    449  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1347:    449  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1348:    449  7        FAIL SEMI debugger_test:unify/4-0 
    1349:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1350:    450  7        CALL DET  debugger_test:rename_apart/5-0 
    1351:    450  7        EXIT DET  debugger_test:rename_apart/5-0 
    1352:    451  7        CALL SEMI debugger_test:unify/4-0 
    1353:    451  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1354:    451  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1355:    451  7        FAIL SEMI debugger_test:unify/4-0 
    1356:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1357:    452  7        CALL DET  debugger_test:rename_apart/5-0 
    1358:    452  7        EXIT DET  debugger_test:rename_apart/5-0 
    1359:    453  7        CALL SEMI debugger_test:unify/4-0 
    1360:    453  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1361:    453  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1362:    453  7        FAIL SEMI debugger_test:unify/4-0 
    1363:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1364:    454  7        CALL DET  debugger_test:rename_apart/5-0 
    1365:    454  7        EXIT DET  debugger_test:rename_apart/5-0 
    1366:    455  7        CALL SEMI debugger_test:unify/4-0 
    1367:    455  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1368:    455  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1369:    455  7        FAIL SEMI debugger_test:unify/4-0 
    1370:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1371:    456  7        CALL DET  debugger_test:rename_apart/5-0 
    1372:    456  7        EXIT DET  debugger_test:rename_apart/5-0 
    1373:    457  7        CALL SEMI debugger_test:unify/4-0 
    1374:    457  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1375:    457  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1376:    457  7        FAIL SEMI debugger_test:unify/4-0 
    1377:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1378:    458  7        CALL DET  debugger_test:rename_apart/5-0 
    1379:    458  7        EXIT DET  debugger_test:rename_apart/5-0 
    1380:    459  7        CALL SEMI debugger_test:unify/4-0 
    1381:    459  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1382:    459  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1383:    459  7        FAIL SEMI debugger_test:unify/4-0 
    1384:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1385:    460  7        CALL DET  debugger_test:rename_apart/5-0 
    1386:    460  7        EXIT DET  debugger_test:rename_apart/5-0 
    1387:    461  7        CALL SEMI debugger_test:unify/4-0 
    1388:    461  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1389:    461  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1390:    461  7        FAIL SEMI debugger_test:unify/4-0 
    1391:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1392:    462  7        CALL DET  debugger_test:rename_apart/5-0 
    1393:    462  7        EXIT DET  debugger_test:rename_apart/5-0 
    1394:    463  7        CALL SEMI debugger_test:unify/4-0 
    1395:    463  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1396:    463  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1397:    463  7        FAIL SEMI debugger_test:unify/4-0 
    1398:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1399:    464  7        CALL DET  debugger_test:rename_apart/5-0 
    1400:    464  7        EXIT DET  debugger_test:rename_apart/5-0 
    1401:    465  7        CALL SEMI debugger_test:unify/4-0 
    1402:    465  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1403:    465  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1404:    465  7        FAIL SEMI debugger_test:unify/4-0 
    1405:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1406:    466  7        CALL DET  debugger_test:rename_apart/5-0 
    1407:    466  7        EXIT DET  debugger_test:rename_apart/5-0 
    1408:    467  7        CALL SEMI debugger_test:unify/4-0 
    1409:    467  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1410:    467  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1411:    467  7        FAIL SEMI debugger_test:unify/4-0 
    1412:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1413:    468  7        CALL DET  debugger_test:rename_apart/5-0 
    1414:    468  7        EXIT DET  debugger_test:rename_apart/5-0 
    1415:    469  7        CALL SEMI debugger_test:unify/4-0 
    1416:    469  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1417:    469  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1418:    469  7        FAIL SEMI debugger_test:unify/4-0 
    1419:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1420:    470  7        CALL DET  debugger_test:rename_apart/5-0 
    1421:    470  7        EXIT DET  debugger_test:rename_apart/5-0 
    1422:    471  7        CALL SEMI debugger_test:unify/4-0 
    1423:    471  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1424:    471  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1425:    471  7        FAIL SEMI debugger_test:unify/4-0 
    1426:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1427:    472  7        CALL DET  debugger_test:rename_apart/5-0 
    1428:    472  7        EXIT DET  debugger_test:rename_apart/5-0 
    1429:    473  7        CALL SEMI debugger_test:unify/4-0 
    1430:    473  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1431:    473  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1432:    473  7        FAIL SEMI debugger_test:unify/4-0 
    1433:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1434:    474  7        CALL DET  debugger_test:rename_apart/5-0 
    1435:    474  7        EXIT DET  debugger_test:rename_apart/5-0 
    1436:    475  7        CALL SEMI debugger_test:unify/4-0 
    1437:    475  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1438:    475  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1439:    475  7        FAIL SEMI debugger_test:unify/4-0 
    1440:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1441:    476  7        CALL DET  debugger_test:rename_apart/5-0 
    1442:    476  7        EXIT DET  debugger_test:rename_apart/5-0 
    1443:    477  7        CALL SEMI debugger_test:unify/4-0 
    1444:    477  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1445:    477  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1446:    477  7        FAIL SEMI debugger_test:unify/4-0 
    1447:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1448:    478  7        CALL DET  debugger_test:rename_apart/5-0 
    1449:    478  7        EXIT DET  debugger_test:rename_apart/5-0 
    1450:    479  7        CALL SEMI debugger_test:unify/4-0 
    1451:    479  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1452:    479  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1453:    479  7        FAIL SEMI debugger_test:unify/4-0 
    1454:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1455:    480  7        CALL DET  debugger_test:rename_apart/5-0 
    1456:    480  7        EXIT DET  debugger_test:rename_apart/5-0 
    1457:    481  7        CALL SEMI debugger_test:unify/4-0 
    1458:    481  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1459:    481  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1460:    481  7        FAIL SEMI debugger_test:unify/4-0 
    1461:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1462:    482  7        CALL DET  debugger_test:rename_apart/5-0 
    1463:    482  7        EXIT DET  debugger_test:rename_apart/5-0 
    1464:    483  7        CALL SEMI debugger_test:unify/4-0 
    1465:    483  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1466:    483  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1467:    483  7        FAIL SEMI debugger_test:unify/4-0 
    1468:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1469:    484  7        CALL DET  debugger_test:rename_apart/5-0 
    1470:    484  7        EXIT DET  debugger_test:rename_apart/5-0 
    1471:    485  7        CALL SEMI debugger_test:unify/4-0 
    1472:    485  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1473:    485  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1474:    485  7        FAIL SEMI debugger_test:unify/4-0 
    1475:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1476:    486  7        CALL DET  debugger_test:rename_apart/5-0 
    1477:    486  7        EXIT DET  debugger_test:rename_apart/5-0 
    1478:    487  7        CALL SEMI debugger_test:unify/4-0 
    1479:    487  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1480:    487  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1481:    487  7        FAIL SEMI debugger_test:unify/4-0 
    1482:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1483:    488  7        CALL DET  debugger_test:rename_apart/5-0 
    1484:    488  7        EXIT DET  debugger_test:rename_apart/5-0 
    1485:    489  7        CALL SEMI debugger_test:unify/4-0 
    1486:    489  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1487:    489  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1488:    489  7        FAIL SEMI debugger_test:unify/4-0 
    1489:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1490:    490  7        CALL DET  debugger_test:rename_apart/5-0 
    1491:    490  7        EXIT DET  debugger_test:rename_apart/5-0 
    1492:    491  7        CALL SEMI debugger_test:unify/4-0 
    1493:    491  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1494:    491  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1495:    491  7        FAIL SEMI debugger_test:unify/4-0 
    1496:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1497:    492  7        CALL DET  debugger_test:rename_apart/5-0 
    1498:    492  7        EXIT DET  debugger_test:rename_apart/5-0 
    1499:    493  7        CALL SEMI debugger_test:unify/4-0 
    1500:    493  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1501:    493  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1502:    493  7        FAIL SEMI debugger_test:unify/4-0 
    1503:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1504:    494  7        CALL DET  debugger_test:rename_apart/5-0 
    1505:    494  7        EXIT DET  debugger_test:rename_apart/5-0 
    1506:    495  7        CALL SEMI debugger_test:unify/4-0 
    1507:    495  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1508:    495  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1509:    495  7        FAIL SEMI debugger_test:unify/4-0 
    1510:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1511:    496  7        CALL DET  debugger_test:rename_apart/5-0 
    1512:    496  7        EXIT DET  debugger_test:rename_apart/5-0 
    1513:    497  7        CALL SEMI debugger_test:unify/4-0 
    1514:    497  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1515:    497  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1516:    497  7        FAIL SEMI debugger_test:unify/4-0 
    1517:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1518:    498  7        CALL DET  debugger_test:rename_apart/5-0 
    1519:    498  7        EXIT DET  debugger_test:rename_apart/5-0 
    1520:    499  7        CALL SEMI debugger_test:unify/4-0 
    1521:    499  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1522:    499  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1523:    499  7        FAIL SEMI debugger_test:unify/4-0 
    1524:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1525:    500  7        CALL DET  debugger_test:rename_apart/5-0 
    1526:    500  7        EXIT DET  debugger_test:rename_apart/5-0 
    1527:    501  7        CALL SEMI debugger_test:unify/4-0 
    1528:    501  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1529:    501  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1530:    501  7        FAIL SEMI debugger_test:unify/4-0 
    1531:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1532:    502  7        CALL DET  debugger_test:rename_apart/5-0 
    1533:    502  7        EXIT DET  debugger_test:rename_apart/5-0 
    1534:    503  7        CALL SEMI debugger_test:unify/4-0 
    1535:    503  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1536:    503  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1537:    503  7        FAIL SEMI debugger_test:unify/4-0 
    1538:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1539:    504  7        CALL DET  debugger_test:rename_apart/5-0 
    1540:    504  7        EXIT DET  debugger_test:rename_apart/5-0 
    1541:    505  7        CALL SEMI debugger_test:unify/4-0 
    1542:    505  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1543:    505  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1544:    505  7        FAIL SEMI debugger_test:unify/4-0 
    1545:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1546:    506  7        CALL DET  debugger_test:rename_apart/5-0 
    1547:    506  7        EXIT DET  debugger_test:rename_apart/5-0 
    1548:    507  7        CALL SEMI debugger_test:unify/4-0 
    1549:    507  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1550:    507  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1551:    507  7        FAIL SEMI debugger_test:unify/4-0 
    1552:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1553:    508  7        CALL DET  debugger_test:rename_apart/5-0 
    1554:    508  7        EXIT DET  debugger_test:rename_apart/5-0 
    1555:    509  7        CALL SEMI debugger_test:unify/4-0 
    1556:    509  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1557:    509  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1558:    509  7        FAIL SEMI debugger_test:unify/4-0 
    1559:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1560:    510  7        CALL DET  debugger_test:rename_apart/5-0 
    1561:    510  7        EXIT DET  debugger_test:rename_apart/5-0 
    1562:    511  7        CALL SEMI debugger_test:unify/4-0 
    1563:    511  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1564:    511  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1565:    511  7        FAIL SEMI debugger_test:unify/4-0 
    1566:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1567:    512  7        CALL DET  debugger_test:rename_apart/5-0 
    1568:    512  7        EXIT DET  debugger_test:rename_apart/5-0 
    1569:    513  7        CALL SEMI debugger_test:unify/4-0 
    1570:    513  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1571:    513  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1572:    513  7        FAIL SEMI debugger_test:unify/4-0 
    1573:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1574:    514  7        CALL DET  debugger_test:rename_apart/5-0 
    1575:    514  7        EXIT DET  debugger_test:rename_apart/5-0 
    1576:    515  7        CALL SEMI debugger_test:unify/4-0 
    1577:    515  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1578:    515  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1579:    515  7        FAIL SEMI debugger_test:unify/4-0 
    1580:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1581:    516  7        CALL DET  debugger_test:rename_apart/5-0 
    1582:    516  7        EXIT DET  debugger_test:rename_apart/5-0 
    1583:    517  7        CALL SEMI debugger_test:unify/4-0 
    1584:    517  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1585:    517  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1586:    517  7        FAIL SEMI debugger_test:unify/4-0 
    1587:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1588:    518  7        CALL DET  debugger_test:rename_apart/5-0 
    1589:    518  7        EXIT DET  debugger_test:rename_apart/5-0 
    1590:    519  7        CALL SEMI debugger_test:unify/4-0 
    1591:    519  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1592:    519  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1593:    519  7        FAIL SEMI debugger_test:unify/4-0 
    1594:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1595:    520  7        CALL DET  debugger_test:rename_apart/5-0 
    1596:    520  7        EXIT DET  debugger_test:rename_apart/5-0 
    1597:    521  7        CALL SEMI debugger_test:unify/4-0 
    1598:    521  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1599:    521  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1600:    521  7        FAIL SEMI debugger_test:unify/4-0 
    1601:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1602:    522  7        CALL DET  debugger_test:rename_apart/5-0 
    1603:    522  7        EXIT DET  debugger_test:rename_apart/5-0 
    1604:    523  7        CALL SEMI debugger_test:unify/4-0 
    1605:    523  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1606:    523  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1607:    523  7        FAIL SEMI debugger_test:unify/4-0 
    1608:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1609:    524  7        CALL DET  debugger_test:rename_apart/5-0 
    1610:    524  7        EXIT DET  debugger_test:rename_apart/5-0 
    1611:    525  7        CALL SEMI debugger_test:unify/4-0 
    1612:    525  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1613:    525  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1614:    525  7        FAIL SEMI debugger_test:unify/4-0 
    1615:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1616:    526  7        CALL DET  debugger_test:rename_apart/5-0 
    1617:    526  7        EXIT DET  debugger_test:rename_apart/5-0 
    1618:    527  7        CALL SEMI debugger_test:unify/4-0 
    1619:    527  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1620:    527  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1621:    527  7        FAIL SEMI debugger_test:unify/4-0 
    1622:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1623:    528  7        CALL DET  debugger_test:rename_apart/5-0 
    1624:    528  7        EXIT DET  debugger_test:rename_apart/5-0 
    1625:    529  7        CALL SEMI debugger_test:unify/4-0 
    1626:    529  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1627:    529  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1628:    529  7        FAIL SEMI debugger_test:unify/4-0 
    1629:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1630:    530  7        CALL DET  debugger_test:rename_apart/5-0 
    1631:    530  7        EXIT DET  debugger_test:rename_apart/5-0 
    1632:    531  7        CALL SEMI debugger_test:unify/4-0 
    1633:    531  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1634:    531  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1635:    531  7        FAIL SEMI debugger_test:unify/4-0 
    1636:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1637:    532  7        CALL DET  debugger_test:rename_apart/5-0 
    1638:    532  7        EXIT DET  debugger_test:rename_apart/5-0 
    1639:    533  7        CALL SEMI debugger_test:unify/4-0 
    1640:    533  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1641:    533  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1642:    533  7        FAIL SEMI debugger_test:unify/4-0 
    1643:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1644:    534  7        CALL DET  debugger_test:rename_apart/5-0 
    1645:    534  7        EXIT DET  debugger_test:rename_apart/5-0 
    1646:    535  7        CALL SEMI debugger_test:unify/4-0 
    1647:    535  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1648:    535  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1649:    535  7        FAIL SEMI debugger_test:unify/4-0 
    1650:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1651:    536  7        CALL DET  debugger_test:rename_apart/5-0 
    1652:    536  7        EXIT DET  debugger_test:rename_apart/5-0 
    1653:    537  7        CALL SEMI debugger_test:unify/4-0 
    1654:    537  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1655:    537  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1656:    537  7        FAIL SEMI debugger_test:unify/4-0 
    1657:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1658:    538  7        CALL DET  debugger_test:rename_apart/5-0 
    1659:    538  7        EXIT DET  debugger_test:rename_apart/5-0 
    1660:    539  7        CALL SEMI debugger_test:unify/4-0 
    1661:    539  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1662:    539  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1663:    539  7        FAIL SEMI debugger_test:unify/4-0 
    1664:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1665:    540  7        CALL DET  debugger_test:rename_apart/5-0 
    1666:    540  7        EXIT DET  debugger_test:rename_apart/5-0 
    1667:    541  7        CALL SEMI debugger_test:unify/4-0 
    1668:    541  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1669:    541  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1670:    541  7        FAIL SEMI debugger_test:unify/4-0 
    1671:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1672:    542  7        CALL DET  debugger_test:rename_apart/5-0 
    1673:    542  7        EXIT DET  debugger_test:rename_apart/5-0 
    1674:    543  7        CALL SEMI debugger_test:unify/4-0 
    1675:    543  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1676:    543  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1677:    543  7        FAIL SEMI debugger_test:unify/4-0 
    1678:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1679:    544  7        CALL DET  debugger_test:rename_apart/5-0 
    1680:    544  7        EXIT DET  debugger_test:rename_apart/5-0 
    1681:    545  7        CALL SEMI debugger_test:unify/4-0 
    1682:    545  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1683:    545  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1684:    545  7        FAIL SEMI debugger_test:unify/4-0 
    1685:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1686:    546  7        CALL DET  debugger_test:rename_apart/5-0 
    1687:    546  7        EXIT DET  debugger_test:rename_apart/5-0 
    1688:    547  7        CALL SEMI debugger_test:unify/4-0 
    1689:    547  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1690:    547  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1691:    547  7        FAIL SEMI debugger_test:unify/4-0 
    1692:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1693:    548  7        CALL DET  debugger_test:rename_apart/5-0 
    1694:    548  7        EXIT DET  debugger_test:rename_apart/5-0 
    1695:    549  7        CALL SEMI debugger_test:unify/4-0 
    1696:    549  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1697:    549  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1698:    549  7        FAIL SEMI debugger_test:unify/4-0 
    1699:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1700:    550  7        CALL DET  debugger_test:rename_apart/5-0 
    1701:    550  7        EXIT DET  debugger_test:rename_apart/5-0 
    1702:    551  7        CALL SEMI debugger_test:unify/4-0 
    1703:    551  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1704:    551  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1705:    551  7        FAIL SEMI debugger_test:unify/4-0 
    1706:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1707:    552  7        CALL DET  debugger_test:rename_apart/5-0 
    1708:    552  7        EXIT DET  debugger_test:rename_apart/5-0 
    1709:    553  7        CALL SEMI debugger_test:unify/4-0 
    1710:    553  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1711:    553  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1712:    553  7        FAIL SEMI debugger_test:unify/4-0 
    1713:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1714:    554  7        CALL DET  debugger_test:rename_apart/5-0 
    1715:    554  7        EXIT DET  debugger_test:rename_apart/5-0 
    1716:    555  7        CALL SEMI debugger_test:unify/4-0 
    1717:    555  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1718:    555  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1719:    555  7        FAIL SEMI debugger_test:unify/4-0 
    1720:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1721:    556  7        CALL DET  debugger_test:rename_apart/5-0 
    1722:    556  7        EXIT DET  debugger_test:rename_apart/5-0 
    1723:    557  7        CALL SEMI debugger_test:unify/4-0 
    1724:    557  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1725:    557  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1726:    557  7        FAIL SEMI debugger_test:unify/4-0 
    1727:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1728:    558  7        CALL DET  debugger_test:rename_apart/5-0 
    1729:    558  7        EXIT DET  debugger_test:rename_apart/5-0 
    1730:    559  7        CALL SEMI debugger_test:unify/4-0 
    1731:    559  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1732:    559  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1733:    559  7        FAIL SEMI debugger_test:unify/4-0 
    1734:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1735:    560  7        CALL DET  debugger_test:rename_apart/5-0 
    1736:    560  7        EXIT DET  debugger_test:rename_apart/5-0 
    1737:    561  7        CALL SEMI debugger_test:unify/4-0 
    1738:    561  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1739:    561  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1740:    561  7        FAIL SEMI debugger_test:unify/4-0 
    1741:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1742:    562  7        CALL DET  debugger_test:rename_apart/5-0 
    1743:    562  7        EXIT DET  debugger_test:rename_apart/5-0 
    1744:    563  7        CALL SEMI debugger_test:unify/4-0 
    1745:    563  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1746:    563  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1747:    563  7        FAIL SEMI debugger_test:unify/4-0 
    1748:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1749:    564  7        CALL DET  debugger_test:rename_apart/5-0 
    1750:    564  7        EXIT DET  debugger_test:rename_apart/5-0 
    1751:    565  7        CALL SEMI debugger_test:unify/4-0 
    1752:    565  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1753:    565  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1754:    565  7        FAIL SEMI debugger_test:unify/4-0 
    1755:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1756:    566  7        CALL DET  debugger_test:rename_apart/5-0 
    1757:    566  7        EXIT DET  debugger_test:rename_apart/5-0 
    1758:    567  7        CALL SEMI debugger_test:unify/4-0 
    1759:    567  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1760:    567  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1761:    567  7        FAIL SEMI debugger_test:unify/4-0 
    1762:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1763:    568  7        CALL DET  debugger_test:rename_apart/5-0 
    1764:    568  7        EXIT DET  debugger_test:rename_apart/5-0 
    1765:    569  7        CALL SEMI debugger_test:unify/4-0 
    1766:    569  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1767:    569  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1768:    569  7        FAIL SEMI debugger_test:unify/4-0 
    1769:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1770:    570  7        CALL DET  debugger_test:rename_apart/5-0 
    1771:    570  7        EXIT DET  debugger_test:rename_apart/5-0 
    1772:    571  7        CALL SEMI debugger_test:unify/4-0 
    1773:    571  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1774:    571  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1775:    571  7        FAIL SEMI debugger_test:unify/4-0 
    1776:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1777:    572  7        CALL DET  debugger_test:rename_apart/5-0 
    1778:    572  7        EXIT DET  debugger_test:rename_apart/5-0 
    1779:    573  7        CALL SEMI debugger_test:unify/4-0 
    1780:    573  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1781:    573  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1782:    573  7        FAIL SEMI debugger_test:unify/4-0 
    1783:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1784:    574  7        CALL DET  debugger_test:rename_apart/5-0 
    1785:    574  7        EXIT DET  debugger_test:rename_apart/5-0 
    1786:    575  7        CALL SEMI debugger_test:unify/4-0 
    1787:    575  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1788:    575  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1789:    575  7        FAIL SEMI debugger_test:unify/4-0 
    1790:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1791:    576  7        CALL DET  debugger_test:rename_apart/5-0 
    1792:    576  7        EXIT DET  debugger_test:rename_apart/5-0 
    1793:    577  7        CALL SEMI debugger_test:unify/4-0 
    1794:    577  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1795:    577  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1796:    577  7        FAIL SEMI debugger_test:unify/4-0 
    1797:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1798:    578  7        CALL DET  debugger_test:rename_apart/5-0 
    1799:    578  7        EXIT DET  debugger_test:rename_apart/5-0 
    1800:    579  7        CALL SEMI debugger_test:unify/4-0 
    1801:    579  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1802:    579  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1803:    579  7        FAIL SEMI debugger_test:unify/4-0 
    1804:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1805:    580  7        CALL DET  debugger_test:rename_apart/5-0 
    1806:    580  7        EXIT DET  debugger_test:rename_apart/5-0 
    1807:    581  7        CALL SEMI debugger_test:unify/4-0 
    1808:    581  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1809:    581  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1810:    581  7        FAIL SEMI debugger_test:unify/4-0 
    1811:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1812:    582  7        CALL DET  debugger_test:rename_apart/5-0 
    1813:    582  7        EXIT DET  debugger_test:rename_apart/5-0 
    1814:    583  7        CALL SEMI debugger_test:unify/4-0 
    1815:    583  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1816:    583  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1817:    583  7        FAIL SEMI debugger_test:unify/4-0 
    1818:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1819:    584  7        CALL DET  debugger_test:rename_apart/5-0 
    1820:    584  7        EXIT DET  debugger_test:rename_apart/5-0 
    1821:    585  7        CALL SEMI debugger_test:unify/4-0 
    1822:    585  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1823:    585  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1824:    585  7        FAIL SEMI debugger_test:unify/4-0 
    1825:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1826:    586  7        CALL DET  debugger_test:rename_apart/5-0 
    1827:    586  7        EXIT DET  debugger_test:rename_apart/5-0 
    1828:    587  7        CALL SEMI debugger_test:unify/4-0 
    1829:    587  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1830:    587  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1831:    587  7        FAIL SEMI debugger_test:unify/4-0 
    1832:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1833:    588  7        CALL DET  debugger_test:rename_apart/5-0 
    1834:    588  7        EXIT DET  debugger_test:rename_apart/5-0 
    1835:    589  7        CALL SEMI debugger_test:unify/4-0 
    1836:    589  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1837:    589  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1838:    589  7        FAIL SEMI debugger_test:unify/4-0 
    1839:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1840:    590  7        CALL DET  debugger_test:rename_apart/5-0 
    1841:    590  7        EXIT DET  debugger_test:rename_apart/5-0 
    1842:    591  7        CALL SEMI debugger_test:unify/4-0 
    1843:    591  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1844:    591  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1845:    591  7        FAIL SEMI debugger_test:unify/4-0 
    1846:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1847:    592  7        CALL DET  debugger_test:rename_apart/5-0 
    1848:    592  7        EXIT DET  debugger_test:rename_apart/5-0 
    1849:    593  7        CALL SEMI debugger_test:unify/4-0 
    1850:    593  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1851:    593  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1852:    593  7        FAIL SEMI debugger_test:unify/4-0 
    1853:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1854:    594  7        CALL DET  debugger_test:rename_apart/5-0 
    1855:    594  7        EXIT DET  debugger_test:rename_apart/5-0 
    1856:    595  7        CALL SEMI debugger_test:unify/4-0 
    1857:    595  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1858:    595  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1859:    595  7        FAIL SEMI debugger_test:unify/4-0 
    1860:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1861:    596  7        CALL DET  debugger_test:rename_apart/5-0 
    1862:    596  7        EXIT DET  debugger_test:rename_apart/5-0 
    1863:    597  7        CALL SEMI debugger_test:unify/4-0 
    1864:    597  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1865:    597  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1866:    597  7        FAIL SEMI debugger_test:unify/4-0 
    1867:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1868:    598  7        CALL DET  debugger_test:rename_apart/5-0 
    1869:    598  7        EXIT DET  debugger_test:rename_apart/5-0 
    1870:    599  7        CALL SEMI debugger_test:unify/4-0 
    1871:    599  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1872:    599  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1873:    599  7        FAIL SEMI debugger_test:unify/4-0 
    1874:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1875:    600  7        CALL DET  debugger_test:rename_apart/5-0 
    1876:    600  7        EXIT DET  debugger_test:rename_apart/5-0 
    1877:    601  7        CALL SEMI debugger_test:unify/4-0 
    1878:    601  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1879:    601  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1880:    601  7        FAIL SEMI debugger_test:unify/4-0 
    1881:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1882:    602  7        CALL DET  debugger_test:rename_apart/5-0 
    1883:    602  7        EXIT DET  debugger_test:rename_apart/5-0 
    1884:    603  7        CALL SEMI debugger_test:unify/4-0 
    1885:    603  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1886:    603  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1887:    603  7        FAIL SEMI debugger_test:unify/4-0 
    1888:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1889:    604  7        CALL DET  debugger_test:rename_apart/5-0 
    1890:    604  7        EXIT DET  debugger_test:rename_apart/5-0 
    1891:    605  7        CALL SEMI debugger_test:unify/4-0 
    1892:    605  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1893:    605  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1894:    605  7        FAIL SEMI debugger_test:unify/4-0 
    1895:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1896:    606  7        CALL DET  debugger_test:rename_apart/5-0 
    1897:    606  7        EXIT DET  debugger_test:rename_apart/5-0 
    1898:    607  7        CALL SEMI debugger_test:unify/4-0 
    1899:    607  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1900:    607  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1901:    607  7        FAIL SEMI debugger_test:unify/4-0 
    1902:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1903:    608  7        CALL DET  debugger_test:rename_apart/5-0 
    1904:    608  7        EXIT DET  debugger_test:rename_apart/5-0 
    1905:    609  7        CALL SEMI debugger_test:unify/4-0 
    1906:    609  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1907:    609  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1908:    609  7        FAIL SEMI debugger_test:unify/4-0 
    1909:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1910:    610  7        CALL DET  debugger_test:rename_apart/5-0 
    1911:    610  7        EXIT DET  debugger_test:rename_apart/5-0 
    1912:    611  7        CALL SEMI debugger_test:unify/4-0 
    1913:    611  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1914:    611  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1915:    611  7        FAIL SEMI debugger_test:unify/4-0 
    1916:    445  7        EXIT NON  debugger_test:database_lookup_clause/5-0 
    1917:    612  7        CALL DET  debugger_test:rename_apart/5-0 
    1918:    612  7        EXIT DET  debugger_test:rename_apart/5-0 
    1919:    613  7        CALL SEMI debugger_test:unify/4-0 
    1920:    613  7        SWTC SEMI debugger_test:unify/4-0 s1;
    1921:    613  7        SWTC SEMI debugger_test:unify/4-0 s1;c2;s1;
    1922:    613  7        FAIL SEMI debugger_test:unify/4-0 
    1923:    439  6       FAIL NON  debugger_test:solve/4-0 
    1924:    614  6       CALL DET  debugger_test:write_solutions/4-0 
    1925:    614  6       ELSE DET  debugger_test:write_solutions/4-0 e;
    1926:    615  7        CALL DET  debugger_test:write_solutions_2/4-0 
    1927:    615  7        SWTC DET  debugger_test:write_solutions_2/4-0 s1;
f(a) = f(a).
    1928:    616  8         CALL DET  debugger_test:write_solutions_2/4-0 
    1929:    616  8         SWTC DET  debugger_test:write_solutions_2/4-0 s2;
    1930:    616  8         EXIT DET  debugger_test:write_solutions_2/4-0 
    1931:    615  7        EXIT DET  debugger_test:write_solutions_2/4-0 
Yes.
    1932:    614  6       EXIT DET  debugger_test:write_solutions/4-0 
    1933:    617  6       CALL DET  debugger_test:main_loop/3-0 
?-     1934:    618  7        CALL DET  debugger_test:main_loop_2/4-0 
    1935:    618  7        SWTC DET  debugger_test:main_loop_2/4-0 s1;
    1936:    618  7        EXIT DET  debugger_test:main_loop_2/4-0 
    1937:    617  6       EXIT DET  debugger_test:main_loop/3-0 
    1938:    438  5      EXIT DET  debugger_test:main_loop_2/4-0 
    1939:    437  4     EXIT DET  debugger_test:main_loop/3-0 
    1940:    261  3    EXIT DET  debugger_test:main_loop_2/4-0 
    1941:    260  2   EXIT DET  debugger_test:main_loop/3-0 
    1942:      1  1  EXIT DET  debugger_test:main/2-0 
