det_throw:
	yes(univ_cons("det_throw"))
	[]
det_succeed:
	no
	["det_succeed"]
semidet_throw:
	yes(univ_cons("semidet_throw"))
	[]
semidet_succeed:
	no
	["semidet_succeed"]
semidet_fail:
	no
	[]
multi_throw:
	yes(univ_cons("multi_throw"))
	[]
multi_succeed:
	no
	["multi_succeed 1", "multi_succeed 2"]
multi_succeed_then_throw:
	yes(univ_cons("multi_succeed_then_throw 3"))
	["multi_succeed_then_throw 1", "multi_succeed_then_throw 2"]
nondet_throw:
	yes(univ_cons("nondet_throw"))
	[]
nondet_succeed:
	no
	["nondet_succeed 1", "nondet_succeed 2"]
nondet_fail:
	no
	[]
nondet_succeed_then_throw:
	yes(univ_cons("nondet_succeed_then_throw 3"))
	["nondet_succeed_then_throw 1", "nondet_succeed_then_throw 2"]
