#!/bin/sh
#
# INSTALL - installation instructions and installation script.
#
# Step 0.  Extract the files from the gzipped tar archive.
#
# Step 1.  Set the installation target directories and other system-specific
#	   macros in the file Mmake.common.
#	   Uncomment the `MMAKEFLAGS=-j3' below if you want to do a parallel
#	   make.
#
# Step 2.  Execute this script.  (Just type `sh INSTALL'.)
#	   [If it doesn't work first time, try again.]
#
# Step 3.  Check the permissions on the installed files.

PATH=`pwd`/scripts:$PATH
export PATH
(cd scripts && make -f Mmake.makefile) &&
mmake install # MMAKEFLAGS=-j3
