#!/bin/sh
#
# INSTALL_CVS - installation instructions and installation script.
#	This version is for use by Mercury developers after you have
#       just checked the files out from the CVS archive. 
#        Note: you need a previous version of Mercury
#	already installed (the CVS archive doesn't have all the necessary
#	files for bootstrapping).
#	You also need autoconf (and hence GNU m4) installed.
#
# Step 0.  autoconf
#
# Step 1.  ./configure
#
# Step 2.  mmake depend
#
# Step 3.  mmake
#
# Step 4.  mmake install
#
#	   If you just want to do a `make' rather than a `make install',
#	   then comment out the `mmake install' line below.
#	   If you don't want to do a parallel make, comment out the
#	   `parallel=-j3' line below.

parallel=-j3

autoconf &&
./configure &&
touch Mmake.params &&
mmake depend $parallel &&
mmake MMAKEFLAGS=$parallel &&
mmake install MMAKEFLAGS=$parallel &&
true
