#!/bin/sh
# Generate the .exp files that are used as a basis of comparison to check
# the correctness of the code emitted by the Mercury compiler.

. ./handle_options

root=`pwd`
for dir in benchmarks general
do
	cd $dir
	mmake $jfactor realclean
	mmake $jfactor depend
	mmake $jfactor HAVE_NUPROLOG=yes exp
	cd $root
done
