#!/bin/sh

# Process command line options.
. ./handle_options

# Run the tests in each of the subdirectories.
. ./subdir_runtests

if test "$subdir_failures" = ""
then
	echo "all tests have succeeded"
	echo "gradeopt=$gflag, flagsopt=$fflag, cflagsopt=$cflag"
	exit 0
else
	echo "some tests have failed in: $subdir_failures"
	echo "gradeopt=$gflag, flagsopt=$fflag, cflagsopt=$cflag"
	exit 1
fi
