#!/bin/sh
# Run the tests in each of the subdirectories.

. ./handle_options

failures=""
for dir in *
do
	if test -d $dir -a -x $dir/runtests
	then
		cd $dir
		if runtests $jfactor $fflag $gflag
		then
			true
		else
			failures="$failures $dir"
		fi
		cd ..
	fi
done

if test "$failures" = ""
then
	echo "all tests have succeeded"
	exit 0
else
	echo "some tests have failed in: $failures"
	exit 1
fi
