--no-mercury-stdlib-dir
-I@WORKSPACE@/library
-I@WORKSPACE@/browser
-I@WORKSPACE@/mdbcomp
--c-include-directory @WORKSPACE@/boehm_gc
--c-include-directory @WORKSPACE@/boehm_gc/include
--c-include-directory @WORKSPACE@/runtime
--c-include-directory @WORKSPACE@/library
--c-include-directory @WORKSPACE@/library/Mercury/mihs
--c-include-directory @WORKSPACE@/mdbcomp
--c-include-directory @WORKSPACE@/mdbcomp/Mercury/mihs
--c-include-directory @WORKSPACE@/browser
--c-include-directory @WORKSPACE@/browser/Mercury/mihs
--c-include-directory @WORKSPACE@/trace
--c-include-directory @WORKSPACE@/ssdb
--c-include-directory @WORKSPACE@/ssdb/Mercury/mihs
--linkage shared
--csharp-flags -lib:@WORKSPACE@/library
--csharp-flags -r:mer_std.dll
--config-file @WORKSPACE@/scripts/Mercury.config.bootstrap
