#!/bin/sh
# Test whether smart recompilation works and is producing the
# expected output.
# Return a status of 0 (true) if everything is all right, and 1 otherwise.

. ../handle_options

case "`eval mmake $mmakeopts should_run_recompilation_tests`" in
	no)	
		exit 0
		;;
esac

. ../startup

. ./TESTS

failing_tests=""
cleanup=true

# If the compilation is supposed to fail then the mmake
# output should be suppressed to avoid making it harder
# to find genuine failures in the nightly test logs.
failing_make_output=failing_make_output

export mmakeopts generate_missing_exp_files cleanup failing_make_output

run_all_tests () {
	test_should_fail=$1
	shift

	for test in "$@"
	do
		rm -f $test.res
		touch $test.res
		if ./two_module_test $test_should_fail $test ${test}_2
		then
			:
		else
			failing_tests="$failing_tests $test"
		fi
	done
}

run_all_tests false $TESTS_SHOULD_SUCCEED
run_all_tests true $TESTS_SHOULD_FAIL

# Parallel mmake does not work with nested sub-modules,
# so disable it for tests which contain nested sub-modules.
oldmmakeopts="$mmakeopts"
mmakeopts="$mmakeopts -j1"
export mmakeopts
run_all_tests false $NO_PARALLEL_MAKE_TESTS

mmakeopts=$oldmmakeopts
export mmakeopts

cat *.res > .allres
if [ "$failing_tests" = "" -a ! -s .allres ]
then
	echo "the tests in the recompilation directory succeeded"
	echo "mmakeopts=$mmakeopts"
	rm -f .allres
	case $cleanup in true)
		rm -f $failing_make_output
		. ../shutdown ;;
	esac
	exit 0
else
	echo "the tests in the recompilation directory failed"
	echo "mmakeopts=$mmakeopts"
	echo "the tests that failed are: $failing_tests"
	echo "the differences are:"
	cat .allres
	exit 1
fi
