rotations(3, 2, [10, 20, 30, 40, 50]) =
	soln 0: [30, 40, 50, 10, 20]
	soln 1: [40, 50, 10, 20, 30]

rotations(3, 2, [10, 20, 30, 40, 50]) =
	soln 0: [30, 40, 50, 10, 20]
	soln 1: [40, 50, 10, 20, 30]

rotations(3, 2, ["ten", "twenty", "thirty", "forty", "fifty"]) =
	soln 0: ["forty", "fifty", "ten", "twenty", "thirty"]
	soln 1: ["thirty", "forty", "fifty", "ten", "twenty"]

rotations(3, 2, [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0]]) =
	soln 0: [[3, 0], [4, 0], [5, 0], [1, 0], [2, 0]]
	soln 1: [[4, 0], [5, 0], [1, 0], [2, 0], [3, 0]]

rotations(3, 2, [sol([1]), sol([1, 2]), sol([1, 2, 3]), sol([1, 2, 3, 4])]) =
	soln 0: [sol([1, 2, 3]), sol([1, 2, 3, 4]), sol([1]), sol([1, 2])]
	soln 1: [sol([1, 2, 3, 4]), sol([1]), sol([1, 2]), sol([1, 2, 3])]

rotations(3, 1, [10, 20, 30, 40, 50]) =
	soln 0: [40, 50, 10, 20, 30]

rotations(3, 1, [10, 20, 30, 40, 50]) =
	soln 0: [40, 50, 10, 20, 30]

rotations(3, 1, ["ten", "twenty", "thirty", "forty", "fifty"]) =
	soln 0: ["forty", "fifty", "ten", "twenty", "thirty"]

rotations(3, 1, [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0]]) =
	soln 0: [[4, 0], [5, 0], [1, 0], [2, 0], [3, 0]]

rotations(3, 1, [sol([1]), sol([1, 2]), sol([1, 2, 3]), sol([1, 2, 3, 4])]) =
	soln 0: [sol([1, 2, 3, 4]), sol([1]), sol([1, 2]), sol([1, 2, 3])]

rotations(2, 1, [10, 20, 30, 40, 50]) =
	soln 0: [30, 40, 50, 10, 20]

rotations(2, 1, [10, 20, 30, 40, 50]) =
	soln 0: [30, 40, 50, 10, 20]

rotations(2, 1, ["ten", "twenty", "thirty", "forty", "fifty"]) =
	soln 0: ["thirty", "forty", "fifty", "ten", "twenty"]

rotations(2, 1, [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0]]) =
	soln 0: [[3, 0], [4, 0], [5, 0], [1, 0], [2, 0]]

rotations(2, 1, [sol([1]), sol([1, 2]), sol([1, 2, 3]), sol([1, 2, 3, 4])]) =
	soln 0: [sol([1, 2, 3]), sol([1, 2, 3, 4]), sol([1]), sol([1, 2])]

rotations(2, 0, [10, 20, 30, 40, 50]) =

rotations(2, 0, [10, 20, 30, 40, 50]) =

rotations(2, 0, ["ten", "twenty", "thirty", "forty", "fifty"]) =

rotations(2, 0, [[1, 0], [2, 0], [3, 0], [4, 0], [5, 0]]) =

rotations(2, 0, [sol([1]), sol([1, 2]), sol([1, 2, 3]), sol([1, 2, 3, 4])]) =

