#!/bin/sh
#
# INSTALL - installation instructions and installation script
#	    for the binary distribution of Mercury.
#
# You need GNU C (2.6.3 or later) and GNU Make (3.69 or later) in order
# to use Mercury, though you don't need them to install this distribution.
#
# Step 0.  Extract the files from the gzipped tar archive.
#
# Step 1.  Run `configure'.  (Just type `sh configure'.)
#
#	   By default, the files will be installed in /usr/local/mercury-0.4.
#	   If you want the files to be installed someplace else,
#	   use the `--prefix <directory>' option to `configure'.
#
# Step 2.  Run `make install'.
#	   This step will copy the various files that make up the distribution
#	   to their final places.
#
# Step 4.  Check the permissions on the installed files.
#	   Add /usr/local/mercury-0.4/bin to your PATH, and
#	   add /usr/local/mercury-0.4/info to your INFOPATH.
#	   You can also add a WWW link to the Mercury documentation in
#	   /usr/local/mercury-0.4/lib/mercury/html to your WWW home page,
#	   and you may want to print out a hard-copy of the documentation
#	   from the DVI files in /usr/local/mercury-0.4/lib/mercury/doc.
#
# As a short-cut, steps 1 & 2 are listed below, so they can be replaced
# by just executing this file.  It's advisable to redirect the output
# into a file, just in case anything should go wrong.  I suggest you
# run it in the background, and read the Mercury documentation in the
# `doc' directory while you are waiting.  You can use the command 
#	sh -c './INSTALL > errs 2>&1' &
# to do this; the output will be redirected to the file `errs'.

sh configure &&
make install

# De-installation:
# ----------------
#
# You may eventually want to uninstall this version of Mercury
# (to free up disk space so you can install the next version ;-).
# If you installed in the default location, you can simply
# use `rm -rf /usr/local/mercury-0.4' to uninstall.
