#!/bin/sh
# vim: sw=4 ts=4 et ft=sh

# This script replaces the body of the Invocation chapter of the User's Guide
# with the texinfo version of the mmc help text.
#
# It is here in a separate shell script because including a dollar sign
# in the last invocation of sed below is unreasonably hard when the
# command is in an action in a makefile, given that we actually want
# the two characters $ and w, not the value of a shell or make variable
# named w.
cp user_guide.texi USER_GUIDE_TEXI_OLD
/bin/rm -f USER_GUIDE_TEXI_START USER_GUIDE_TEXI_END > /dev/null 2>&1
/bin/rm -f INVOCATION_OLD0 INVOCATION_OLD INVOCATION_NEW > /dev/null 2>&1
echo > INVOCATION_NEW
../compiler/mercury_compile --help-texinfo \
    --no-mercury-stdlib-dir \
    --config-file ../scripts/Mercury.config \
    >> INVOCATION_NEW
echo >> INVOCATION_NEW
sed -e '1,/INCLUDE_HELP_TEXT_START/w USER_GUIDE_TEXI_START' \
    < user_guide.texi > /dev/null 2>&1
sed -e '/INCLUDE_HELP_TEXT_START/,/INCLUDE_HELP_TEXT_END/w INVOCATION_OLD0' \
    < user_guide.texi > /dev/null 2>&1
sed -e '/INCLUDE_HELP_TEXT/d' < INVOCATION_OLD0 > INVOCATION_OLD
sed -e '/INCLUDE_HELP_TEXT_END/,$w USER_GUIDE_TEXI_END' \
    < user_guide.texi > /dev/null 2>&1
cat USER_GUIDE_TEXI_START INVOCATION_NEW USER_GUIDE_TEXI_END \
    > user_guide.texi.new
mv -f user_guide.texi.new user_guide.texi
/bin/rm -f USER_GUIDE_TEXI_START USER_GUIDE_TEXI_END > /dev/null 2>&1
/bin/rm -f INVOCATION_OLD0 > /dev/null 2>&1

diff -u INVOCATION_OLD INVOCATION_NEW > INVOCATION_DIFF
diff -u USER_GUIDE_TEXI_OLD user_guide.texi > USER_GUIDE_TEXI_DIFF

echo "The diff to invocation chapter is in INVOCATION_DIFF."
echo "The diff to user_guide.texi is in USER_GUIDE_TEXI_DIFF."
exit 0
