Writing copies of terms:
myf(1)
f(1, "hello", 42)
f(2, 'w', 42)
f(3, goo, 42)
f(4, g("hello"), 42)
f(5, g2(12), 42)
f(6, foo("hello", "world"), 42)
g(7.0, g("hello"), 42.0)
f(8, u("hello"), 42)
f2(9, "hello", u("hello"), 432.1, u("world"), 42)
multi(10, "multiparameter")
multi2(11, "multiparameter", 42.0)

Writing some terms:
myf(1)
f(1, "hello", 42)
f(2, 'w', 42)
f(3, goo, 42)
f(4, g("hello"), 42)
f(5, g2(12), 42)
f(6, foo("hello", "world"), 42)
g(7.0, g("hello"), 42.0)
f(8, u("hello"), 42)
f2(9, "hello", u("hello"), 432.1, u("world"), 42)
multi(10, "multiparameter")
multi2(11, "multiparameter", 42.0)

Writing copies of terms again:
myf(1)
f(1, "hello", 42)
f(2, 'w', 42)
f(3, goo, 42)
f(4, g("hello"), 42)
f(5, g2(12), 42)
f(6, foo("hello", "world"), 42)
g(7.0, g("hello"), 42.0)
f(8, u("hello"), 42)
f2(9, "hello", u("hello"), 432.1, u("world"), 42)
multi(10, "multiparameter")
multi2(11, "multiparameter", 42.0)
Writing deconstructed terms:
myf/1
univ_cons(1)
f/3
univ_cons(1), univ_cons("hello"), univ_cons(42)
f/3
univ_cons(2), univ_cons('w'), univ_cons(42)
f/3
univ_cons(3), univ_cons(goo), univ_cons(42)
f/3
univ_cons(4), univ_cons(g("hello")), univ_cons(42)
f/3
univ_cons(5), univ_cons(g2(12)), univ_cons(42)
f/3
univ_cons(6), univ_cons(foo("hello", "world")), univ_cons(42)
g/3
univ_cons(7.0), univ_cons(g("hello")), univ_cons(42.0)
f/3
univ_cons(8), univ_cons(u("hello")), univ_cons(42)
f2/6
univ_cons(9), univ_cons("hello"), univ_cons(u("hello")), univ_cons(432.1), univ_cons(u("world")), univ_cons(42)
multi/2
univ_cons(10), univ_cons("multiparameter")
multi2/3
univ_cons(11), univ_cons("multiparameter"), univ_cons(42.0)
