#!/bin/sh
#
# INSTALL_CVS - installation instructions and installation script.
#	This version is for use after you have just checked the files out from
#	the CVS archive.  Note: you need a previous version of Mercury
#	already installed (the CVS archive doesn't have all the necessary
#	files for bootstrapping).
#
# Step 1.  In the file Mmake.params, set the installation target directories
#	   and other system-specific macros that are listed in Mmake.common.
#	   (But don't edit Mmake.common, otherwise you might accidentally
#	   commit your changes later.)
#	   Set the MERCURY_COMPILER environment variable below to point
#	   to the compiler executable to use for bootstrapping.
#	   If you just want to do a `make' rather than a `make install',
#	   then comment out the `mmake install' line below.
#	   If you don't want to do a parallel make, comment out the
#	   `parallel=-j3' line below.
#
# Step 2.  Execute this script.  (Just type `sh INSTALL_CVS'.)
#
# Step 3.  Check the permissions on the installed files.

MERCURY_COMPILER=/usr/local/contrib/lib/mercury/bin/`fullarch`/mercury_compile
export MERCURY_COMPILER

parallel=-j3

(cd scripts; mmake $parallel) &&
mmake depend $parallel &&
mmake MMAKEFLAGS=$parallel &&
mmake install MMAKEFLAGS=$parallel &&
true
