// vim: ts=4 sw=4 expandtab ft=java
//
// Copyright (C) 2009 The University of Melbourne.
// Copyright (C) 2018 The Mercury team.
// This file is distributed under the terms specified in COPYING.LIB.
//
// This interface is implemented by wrapper classes which are automatically
// generated by the Java back-end to implement method pointers in Java.
//

package jmercury.runtime;

public interface MethodPtr4 extends MethodPtr {
    public abstract java.lang.Object call___0_0(
        java.lang.Object arg1,
        java.lang.Object arg2,
        java.lang.Object arg3,
        java.lang.Object arg4);
}
