%---------------------------------------------------------------------------%
% vim: ft=mercury ts=4 sw=4 et
%---------------------------------------------------------------------------%
% Copyright (C) 2026 The Mercury team.
% This file may only be copied under the terms of the GNU General
% Public License - see the file COPYING in the Mercury distribution.
%---------------------------------------------------------------------------%
%
% File: input_specialization.m.
% Author: zs.
%
% This module implements input specialization pragmas.
%
% Given
%
%   :- pragma input_spec(<type>, <replace_or_add>,
%       [inst_name1, ..., inst_nameN]).
%
% in either module M's .m file or its .int file,
%
% - it looks for predicates and/or functions in module M
%   one or more of whose argument types are <type>,
%
% - for each argument position for which that is tue,
%   it looks for modes that specify "in" in that argument position,
%
% - creates copies of those modes that replace "in" with "in(inst_nameI")
%   for all I in 1..N;
%
% - and either replaces the original mode with its modified copies
%   (if <replace_or_add> is replace_in_mode, or adds the modified copies
%   before the original mode (if <replace_or_add> is add_to_in_mode).
%
% If a predicate or function has more than one mode that specifies the "in"
% mode for argument to be input specialized, the same addition or replacement
% will happen for all of them.
%
% If a predicate or function has more than argument that should be input
% specialized, then the input to the process of specializing the Nth such
% argument is the mode list generated by specializing the previous N-1
% arguments. In other words, the final result will be a mode list that
% could be called a "cross product" of all the input specializations.
%
%---------------------------------------------------------------------------%
%
% This program transformation can change the proc_id of a procedure
% in a predicate or function. This means that it can potentially affect
% the operation of all Mercury program constructs that refer to proc_ids.
% These constructs are all pragmas.
%
% The following lists the pragmas that can refer to specific procedures
% (as opposed to whole predicates and/or functions), and how we handle them.
% A common theme is that the code that add the pragma to the HLDS
% puts information about it into a field of the proc_info, and that
% this module both preserves that field in the original procedure and
% copies it to any input-specialized procedures.
%
% termination
% termination2
% require_tail_rec
%   The compiler records these pragmas in the termination_info,
%   termination2_info, and require_tailrec_info fields of the proc_info
%   respectively. The parts of the passes implementing these pragmas
%   that generate the diagnostics that they call for can include proc_ids
%   (mode numbers) in those diagnostics, but they will map the then-actual
%   proc_ids back to their original proc_ids using the maybe_input_spec field,
%   which is set by code in this module. This mapping back is done by
%   describe_one_proc_name and its variants, and by its subcontractor
%   original_proc_id, in hlds_error_util.
%
% obsolete_proc
%   The compiler records this pragma in the obsolete_in_favour_of field
%   of the proc_info. simplify_goal_call.m, which implements the pragma,
%   looks only at this field, so it gets the "should this call get an
%   obsolete proc warning" test right using its existing code. And the code
%   generating the warning did not need any changes either, because its text
%   identifies the obsolete procedure not by giving its proc_id, but by
%   listing its argument modes.
%
% foreign_proc
%   The compiler records this pragma BY PRED_ID AND PROC_ID in the
%   pragma_exported_procs field of the module_info. If the pred_id
%   in such as record identifies a predicate that we input specialize,
%   then update_exported_proc_id_if_needed below will update the proc_id.
%
% tabled
%   The compiler generates target language variables and auxiliary predicates
%   whose names include the proc_id when it adds tabled pragmas to the HLDS.
%   Since input specialization can change these proc_ids, it is not compatible
%   with tabling. This is why if a predicate that *could* be input specialized
%   has one or more tabled procedures, we generate an error message, and
%   do not perform the input specialization.
%
%   (We do this even if the predicate's tabled procedures would NOT have
%   their proc_ids changed by input specialization. The reason for this
%   decision is that this is a fragile state of affairs, subject to change
%   e.g. by the addition of new modes, and it is better for programmers
%   to learn about this incompatibility before they start relying on
%   something that is liable to break later.)
%
%   There is one form of tabling, I/O tabling, that is implemented
%   entirely by table_gen.m, which runs much later than input specialization.
%   It applies only to predicates that do NOT have a tabled pragma,
%   so their implementations do not involve any variable or procedure names
%   that were decided at the add-pragma-to-the-HLDS time. Their implementation
%   works with the current proc_ids, and should work whether those proc_ids
%   were updated by input specialization or not. In some cases, we can
%   generate diagnostics for such predicates, and these diagnostics do
%   include proc_ids, but describe_one_proc_name maps them back to their
%   originals.
%
% structure_sharing
% structure_reuse
%   Both structure_sharing and structure_reuse pragmas can contain
%   structure_sharing_domains, which contain proc_ids. For pragmas read in
%   from other modules' .opt and/or .trans_opt files, we handle this
%   the same way we handle the interaction with tabling: if a predicate
%   that *could* be input specialized has one or more procedures for which
%   we have read sharing and/or reuse pragmas, we generate an error message,
%   and do not perform the input specialization.
%
%   When creating .opt and/or .trans_opt files, we do not output either
%   structure_sharing and structure_reuse pragmas for procedures that
%   are either logically deleted by input specialization (since they are
%   not supposed to be referred to at all), or are themselves the
%   specialized procedures created by input specialization (since we
%   don't yet know whether we want to export those procedures outside
%   their defining module, and no pragma in a .opt/.trans_opt file
%   should refer to a procedure that its reader may have no knowledge of).
%
% exceptions
% trailing
% mm_tabling
%   The compiler records these pragmas in the exception_info, trailing_info,
%   and mm_tabling_info fields of the proc_info respectively. When input
%   specialization specializes a procedure, these fields get copied as well,
%   and since specialization leaves the body goal of the procedure unchanged,
%   the analysis results they contain remain valid.
%
%   When intermodule optimization writes out these pragmas, we have handle
%   two issues. First as with the structure_sharing and structure_reuse
%   pragmas, we do not write out these pragmas for either procedures
%   logically deleted by input specialization, nor for the new specialized
%   procedures created by it. As for the procedures that do not fall into
%   either of those categories, the second issue is that their procedure number
%   may have been changed by input specialization. We therefore map
%   their procedure ids back to the original.
%
% unused_args
%   We handle writing out unused_args pragmas to .opt/.trans_opt files
%   the same say we handle writing exceptions, trailing, and mm_tabling
%   pragmas, and for the same reason.
%
%   For reading them in, we do not have to do anything special, because
%   while add the contents of each unused_args pragma we read in to a
%   table in the module_info, we do not actually DO anything with the
%   contents of the table :-)
%
% type_spec
%   We do not yet have code to handle these pragmas correctly.
%
%---------------------------------------------------------------------------%

:- module hlds.input_specialization.

:- interface.

:- import_module hlds.hlds_module.
:- import_module parse_tree.
:- import_module parse_tree.error_spec.

:- import_module list.

:- pred input_specialize_in_module(module_info::in, module_info::out,
    list(diag_spec)::in, list(diag_spec)::out) is det.

%---------------------------------------------------------------------------%

:- implementation.

:- import_module hlds.hlds_error_util.
:- import_module hlds.hlds_markers.
:- import_module hlds.hlds_pred.
:- import_module hlds.hlds_proc.
:- import_module hlds.mode_util.
:- import_module hlds.pred_name.
:- import_module hlds.pred_proc_id.
:- import_module hlds.proc_info_types.
:- import_module libs.
:- import_module libs.maybe_util.
:- import_module mdbcomp.
:- import_module mdbcomp.sym_name.
:- import_module parse_tree.prog_data.
:- import_module parse_tree.prog_data_pragma.
:- import_module parse_tree.prog_item_pragma.

:- import_module assoc_list.
:- import_module bool.
:- import_module cord.
:- import_module int.
:- import_module map.
:- import_module maybe.
:- import_module one_or_more.
:- import_module pair.
:- import_module require.
:- import_module set_tree234.

%---------------------------------------------------------------------------%

input_specialize_in_module(!ModuleInfo, !Specs) :-
    module_info_get_input_spec_table(!.ModuleInfo, InputSpecTable),
    module_info_get_valid_pred_ids(!.ModuleInfo, PredIds),
    list.foldl3(maybe_input_specialize_in_pred(InputSpecTable), PredIds,
        [], SpecPredIds, !ModuleInfo, !Specs),
    module_info_get_pragma_exported_procs(!.ModuleInfo, ExportedProcCord0),
    ( if
        SpecPredIds = [_ | _],
        cord.is_non_empty(ExportedProcCord0)
    then
        set_tree234.list_to_set(SpecPredIds, SpecPredIdSet),
        cord.map_pred(
            update_exported_proc_id_if_needed(!.ModuleInfo, SpecPredIdSet),
            ExportedProcCord0, ExportedProcCord),
        module_info_set_pragma_exported_procs(ExportedProcCord, !ModuleInfo)
    else
        true
    ).

:- pred maybe_input_specialize_in_pred(input_spec_table::in, pred_id::in,
    list(pred_id)::in, list(pred_id)::out,
    module_info::in, module_info::out,
    list(diag_spec)::in, list(diag_spec)::out) is det.

maybe_input_specialize_in_pred(InputSpecTable, PredId,
        !SpecPredIds, !ModuleInfo, !Specs) :-
    module_info_pred_info(!.ModuleInfo, PredId, PredInfo0),
    pred_info_get_module_name(PredInfo0, ModuleName),
    ( if map.search(InputSpecTable, ModuleName, InModuleMap) then
        pred_info_get_origin(PredInfo0, Origin),
        (
            Origin = origin_user(UserMade),
            (
                UserMade = user_made_pred(_, _, _),
                input_specialize_in_pred_if_possible(!.ModuleInfo, InModuleMap,
                    PredInfo0, MaybeNewPredInfo, !Specs),
                (
                    MaybeNewPredInfo = no
                ;
                    MaybeNewPredInfo = yes(NewPredInfo),
                    !:SpecPredIds = [PredId | !.SpecPredIds],
                    module_info_set_pred_info(PredId, NewPredInfo, !ModuleInfo)
                )
            ;
                ( UserMade = user_made_lambda(_, _, _)
                ; UserMade = user_made_class_method(_, _)
                ; UserMade = user_made_instance_method(_, _)
                ; UserMade = user_made_assertion(_, _, _)
                )
                % It would make sense to specialize lambda expressions,
                % but they will exist in the form of separate predicates
                % only after the frontend pass.
                %
                % For class and instance methods, altering their signature
                % would be a bug.
                %
                % For assertions, specializations of any kind are irrelevant.
            )
        ;
            ( Origin = origin_compiler(_)
            ; Origin = origin_pred_transform(_, _, _)
            ; Origin = origin_proc_transform(_, _, _, _)
            )
            % Do not specialize either unify/compare/index predicates,
            % or predicates implementing initialise, finalise, mutable
            % and solver type declarations. The other kinds of compiler-made
            % predicates, and all transformed predicates, can only be created
            % by compiler passes that execute after the frontend.
        )
    else
        true
    ).

:- pred input_specialize_in_pred_if_possible(module_info::in,
    input_spec_in_module_map::in, pred_info::in, maybe(pred_info)::out,
    list(diag_spec)::in, list(diag_spec)::out) is det.

input_specialize_in_pred_if_possible(ModuleInfo, InModuleMap,
        PredInfo0, MaybeNewPredInfo, !Specs) :-
    pred_info_get_arg_types(PredInfo0, ArgTypes),
    find_args_to_specialize(InModuleMap, 1, ArgTypes, ArgsToSpec),
    (
        ArgsToSpec = [],
        MaybeNewPredInfo = no
    ;
        ArgsToSpec = [HeadArgToSpec | TailArgsToSpec],
        report_any_incompatibilities(PredInfo0, PredSpecs),
        (
            PredSpecs = [],
            input_specialize_in_pred(ModuleInfo, HeadArgToSpec, TailArgsToSpec,
                PredInfo0, NewPredInfo),
            MaybeNewPredInfo = yes(NewPredInfo)
        ;
            PredSpecs = [_ | _],
            !:Specs = PredSpecs ++ !.Specs,
            MaybeNewPredInfo = no
        )
    ).

:- type arg_to_specialize
    --->    arg_to_specialize(int, input_spec_info).
            % The argument number, and how to specialize it.

:- pred find_args_to_specialize(input_spec_in_module_map::in,
    int::in, list(mer_type)::in, list(arg_to_specialize)::out) is det.

find_args_to_specialize(_, _, [], []).
find_args_to_specialize(InModuleMap, ArgNum, [ArgType | ArgTypes],
        ArgsToSpec) :-
    find_args_to_specialize(InModuleMap, ArgNum + 1, ArgTypes,
        ArgsToSpecTail),
    % This search works only if the types in input_spec pragmas are ground.
    % At the moment, add_pragma_decl.m does require them to be ground.
    ( if map.search(InModuleMap, ArgType, InputSpecInfo) then
        ArgToSpec = arg_to_specialize(ArgNum, InputSpecInfo),
        ArgsToSpec = [ArgToSpec | ArgsToSpecTail]
    else
        ArgsToSpec = ArgsToSpecTail
    ).

%---------------------------------------------------------------------------%

:- pred report_any_incompatibilities(pred_info::in, list(diag_spec)::out)
    is det.

report_any_incompatibilities(PredInfo0, Specs) :-
    pred_info_get_proc_table(PredInfo0, ProcTable0),
    map.foldl4(acc_proc_eval_methods_structs, ProcTable0,
        [], NormalProcIds, [], TabledProcIds, no, Sharing, no, Reuse),
    pred_info_get_context(PredInfo0, Context),
    (
        TabledProcIds = [_ | _],
        (
            NormalProcIds = [],
            (
                TabledProcIds = [_],
                ProcsDesc = [words("its only procedure is tabled,")]
            ;
                TabledProcIds = [_, _ | _],
                ProcsDesc = [words("all of its procedures are tabled,")]
            )
        ;
            NormalProcIds = [_ | _],
            ProcsDesc = [words("some of its procedures are tabled,")]
        ),
        TabledPredPieces = describe_one_pred_info_name(yes(color_subject),
            should_not_module_qualify, [], PredInfo0),
        % This incompatability comes from add_pragma_tabling.m adding
        % to the HLDS global target language variables and auxiliary predicates
        % whose names include the original proc_ids of the tabled procedures.
        TabledPieces = [words("Error:")] ++ TabledPredPieces ++
            [words("could have its modes input specialized, but")] ++
            color_as_incorrect(ProcsDesc) ++
            [words("and input specialization and tabling"),
            words("are mutually exclusive."), nl],
        TabledSpec = spec($pred, severity_error, phase_input_spec,
            Context, TabledPieces),
        TabledSpecs = [TabledSpec]
    ;
        TabledProcIds = [],
        TabledSpecs = []
    ),
    (
        Sharing = yes,
        SharingPredPieces = describe_one_pred_info_name(yes(color_subject),
            should_not_module_qualify, [], PredInfo0),
        SharingPieces = [words("Error:")] ++ SharingPredPieces ++
            [words("could have its modes input specialized, but")] ++
            color_as_incorrect(
                [words("it has a structure_sharing pragma,")]) ++
            [words("and input specialization and structure sharing analysis"),
            words("are mutually exclusive."), nl],
        SharingSpec = spec($pred, severity_error, phase_input_spec,
            Context, SharingPieces),
        SharingSpecs = [SharingSpec]
    ;
        Sharing = no,
        SharingSpecs = []
    ),
    (
        Reuse = yes,
        ReusePredPieces = describe_one_pred_info_name(yes(color_subject),
            should_not_module_qualify, [], PredInfo0),
        ReusePieces = [words("Error:")] ++ ReusePredPieces ++
            [words("could have its modes input specialized, but")] ++
            color_as_incorrect([words("it has a structure_reuse pragma,")]) ++
            [words("and input specialization and structure reuse analysis"),
            words("are mutually exclusive."), nl],
        ReuseSpec = spec($pred, severity_error, phase_input_spec,
            Context, ReusePieces),
        ReuseSpecs = [ReuseSpec]
    ;
        Reuse = no,
        ReuseSpecs = []
    ),
    Specs = TabledSpecs ++ SharingSpecs ++ ReuseSpecs.

:- pred acc_proc_eval_methods_structs(proc_id::in, proc_info::in,
    list(proc_id)::in, list(proc_id)::out,
    list(proc_id)::in, list(proc_id)::out,
    bool::in, bool::out, bool::in, bool::out) is det.

acc_proc_eval_methods_structs(ProcId, ProcInfo,
        !Normal, !Tabled, !Sharing, !Reuse) :-
    proc_info_get_eval_method(ProcInfo, EvalMethod),
    (
        EvalMethod = eval_normal,
        !:Normal = [ProcId | !.Normal]
    ;
        EvalMethod = eval_tabled(_),
        !:Tabled = [ProcId | !.Tabled]
    ),
    proc_info_get_sharing_reuse_info(ProcInfo, SharingReuseInfo),
    SharingReuseInfo = sharing_reuse_info(MaybeSharing, MaybeReuse,
        MaybeImportedSharing, MaybeImportedReuse),
    % Technically, only MaybeImportedSharing and MaybeImportedReuse
    % come from pragmas, and MaybeSharing and MaybeReuse should both be
    % simply "no" at this point in the compilation process, but
    % just in case ...
    ( if
        ( MaybeSharing = yes(_)
        ; MaybeImportedSharing = yes(_)
        )
    then
        !:Sharing = yes
    else
        true
    ),
    ( if
        ( MaybeReuse = yes(_)
        ; MaybeImportedReuse = yes(_)
        )
    then
        !:Reuse = yes
    else
        true
    ).

%---------------------------------------------------------------------------%

:- pred input_specialize_in_pred(module_info::in,
    arg_to_specialize::in, list(arg_to_specialize)::in,
    pred_info::in, pred_info::out) is det.

input_specialize_in_pred(ModuleInfo, HeadArgToSpec, TailArgsToSpec,
        !PredInfo) :-
    HeadArgToSpec = arg_to_specialize(ArgNum, InputSpecInfo),
    pred_info_get_proc_table(!.PredInfo, ProcTable0),
    map.to_assoc_list(ProcTable0, ProcIdInfos0),
    mark_procs_as_input_specialized(ProcIdInfos0, ProcInfos1),
    input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum, InputSpecInfo,
        ProcInfos1, ProcInfos, Changed),
    (
        Changed = unchanged
    ;
        Changed = changed,
        rebuild_proc_table_loop(0, ProcInfos, map.init, ProcTable),
        pred_info_set_proc_table(ProcTable, !PredInfo),
        pred_info_get_markers(!.PredInfo, Markers0),
        add_marker(marker_was_input_specialized, Markers0, Markers),
        pred_info_set_markers(Markers, !PredInfo),
        (
            TailArgsToSpec = []
        ;
            TailArgsToSpec = [HeadTailArgToSpec | TailTailArgsToSpec],
            input_specialize_in_pred(ModuleInfo,
                HeadTailArgToSpec, TailTailArgsToSpec, !PredInfo)
        )
    ).

:- pred mark_procs_as_input_specialized(assoc_list(proc_id, proc_info)::in,
    list(proc_info)::out) is det.

mark_procs_as_input_specialized([], []).
mark_procs_as_input_specialized([ProcId - ProcInfo0 | ProcIdsInfos0],
        [ProcInfo | ProcInfos]) :-
    proc_info_set_maybe_input_spec(input_spec_original_proc_kept(ProcId),
        ProcInfo0, ProcInfo),
    mark_procs_as_input_specialized(ProcIdsInfos0, ProcInfos).

%---------------------------------------------------------------------------%

:- pred rebuild_proc_table_loop(int::in, list(proc_info)::in,
    proc_table::in, proc_table::out) is det.

rebuild_proc_table_loop(_, [], !ProcTable).
rebuild_proc_table_loop(ProcNum, [ProcInfo | ProcInfos], !ProcTable) :-
    proc_id_to_int(ProcId, ProcNum),
    map.det_insert(ProcId, ProcInfo, !ProcTable),
    rebuild_proc_table_loop(ProcNum + 1, ProcInfos, !ProcTable).

%---------------------------------------------------------------------------%

:- pred input_specialize_proc_table_in_given_arg(module_info::in,
    int::in, input_spec_info::in,
    list(proc_info)::in, list(proc_info)::out, maybe_changed::out) is det.

input_specialize_proc_table_in_given_arg(_, _, _, [], [], unchanged).
input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum, InputSpecInfo,
        [HeadProcInfo0 | TailProcInfos0], ProcInfos, Changed) :-
    proc_info_get_argmodes(HeadProcInfo0, ArgModes),
    list.det_index1(ArgModes, ArgNum, SelectedArgMode),
    ( if
        mode_get_insts_semidet(ModuleInfo, SelectedArgMode,
            InitInst, FinalInst),
        InitInst = ground(shared, none_or_default_func),
        InitInst = FinalInst
    then
        input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum,
            InputSpecInfo, TailProcInfos0, TailProcInfos, _Changed),
        proc_info_get_maybe_input_spec(HeadProcInfo0, HeadInputSpecProc0),
        (
            HeadInputSpecProc0 = not_involved_in_input_spec,
            % We set this field in ALL of the predicate's proc_infos
            % to one of the other three function symbols.
            unexpected($pred, "not_involved_in_input_spec")
        ;
            ( HeadInputSpecProc0 =
                input_spec_original_proc_logically_deleted(HeadProcId)
            ; HeadInputSpecProc0 = input_spec_original_proc_kept(HeadProcId)
            ; HeadInputSpecProc0 = input_specialized_proc(HeadProcId)
            )
        ),
        InputSpecInfo = input_spec_info(ReplaceOrAdd, OoMInsts, _Context),
        SpecInsts = one_or_more_to_list(OoMInsts),
        create_input_specialized_proc_infos(HeadProcId, HeadProcInfo0, ArgNum,
            ReplaceOrAdd, SpecInsts, SpecProcInfos),
        ProcInfos = SpecProcInfos ++ TailProcInfos,
        Changed = changed
    else
        input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum,
            InputSpecInfo, TailProcInfos0, TailProcInfos, Changed),
        ProcInfos = [HeadProcInfo0 | TailProcInfos]
    ).

:- pred create_input_specialized_proc_infos(proc_id::in, proc_info::in,
    int::in, replace_or_add_in_mode::in, list(mer_inst)::in,
    list(proc_info)::out) is det.

create_input_specialized_proc_infos(OrigProcId, OrigProcInfo, ArgNum,
        ReplaceOrAdd, SpecInsts, SpecProcInfos) :-
    (
        SpecInsts = [],
        (
            ReplaceOrAdd = replace_in_mode,
            InputSpec = input_spec_original_proc_logically_deleted(OrigProcId)
        ;
            ReplaceOrAdd = add_to_in_mode,
            InputSpec = input_spec_original_proc_kept(OrigProcId)
        ),
        proc_info_set_maybe_input_spec(InputSpec,
            OrigProcInfo, SpecOrigProcInfo),
        SpecProcInfos = [SpecOrigProcInfo]
    ;
        SpecInsts = [HeadSpecInst | TailSpecInsts],

        proc_info_get_argmodes(OrigProcInfo, OrigModes),
        HeadSpecArgMode = from_to_mode(HeadSpecInst, HeadSpecInst),
        det_replace_nth_element1(ArgNum, HeadSpecArgMode,
            OrigModes, HeadSpecModes),
        proc_info_set_argmodes(HeadSpecModes,
            OrigProcInfo, HeadSpecProcInfo0),
        proc_info_set_maybe_input_spec(input_specialized_proc(OrigProcId),
            HeadSpecProcInfo0, HeadSpecProcInfo),
        create_input_specialized_proc_infos(OrigProcId, OrigProcInfo, ArgNum,
            ReplaceOrAdd, TailSpecInsts, TailSpecProcInfos),
        SpecProcInfos = [HeadSpecProcInfo | TailSpecProcInfos]
    ).

%---------------------------------------------------------------------------%

:- pred update_exported_proc_id_if_needed(module_info::in,
    set_tree234(pred_id)::in,
    pragma_exported_proc::in, pragma_exported_proc::out) is det.

update_exported_proc_id_if_needed(ModuleInfo, SpecPredIdSet, !ExportedProc) :-
    !.ExportedProc =
        pragma_exported_proc(Lang, PredId, OrigProcId, Name, Ctxt),
    ( if set_tree234.contains(SpecPredIdSet, PredId) then
        module_info_pred_info(ModuleInfo, PredId, PredInfo),
        pred_info_get_proc_table(PredInfo, ProcTable),
        map.to_assoc_list(ProcTable, ProcIdsInfos),
        find_original_proc_id_in_updated_proc_table(OrigProcId, ProcIdsInfos,
            CurProcId),
        % The presence of the PredId/CurProcId pair in this structure
        % in the module_info will protect the procedure from deletion
        % by dead_proc_elim.m, even if this procedure is logically deleted.
        % It should therefore survive to have code generated for it,
        % and for that generated code to be exported to the rest of
        % the target language program.
        !:ExportedProc =
            pragma_exported_proc(Lang, PredId, CurProcId, Name, Ctxt)
    else
        true
    ).

:- pred find_original_proc_id_in_updated_proc_table(proc_id::in,
    assoc_list(proc_id, proc_info)::in, proc_id::out) is det.

find_original_proc_id_in_updated_proc_table(_SearchOrigProcId, [], _) :-
    unexpected($pred, "search failed").
find_original_proc_id_in_updated_proc_table(SearchOrigProcId,
        [ProcId - ProcInfo | ProcIdsInfos], CurProcId) :-
    proc_info_get_maybe_input_spec(ProcInfo, MaybeInputSpec),
    (
        MaybeInputSpec = not_involved_in_input_spec,
        % We put a predicate into SpecPredIdSet only if we replaced
        % the maybe_input_spec field of all its procedures with
        % one of the other three values of this type.
        unexpected($pred, "not_involved_in_input_spec failed")
    ;
        ( MaybeInputSpec = input_spec_original_proc_kept(OrigProcId)
        ; MaybeInputSpec =
            input_spec_original_proc_logically_deleted(OrigProcId)
        ),
        ( if OrigProcId = SearchOrigProcId then
            CurProcId = ProcId
        else
            find_original_proc_id_in_updated_proc_table(SearchOrigProcId,
                ProcIdsInfos, CurProcId)
        )
    ;
        MaybeInputSpec = input_specialized_proc(_),
        find_original_proc_id_in_updated_proc_table(SearchOrigProcId,
            ProcIdsInfos, CurProcId)
    ).

%---------------------------------------------------------------------------%
:- end_module hlds.input_specialization.
%---------------------------------------------------------------------------%
