%---------------------------------------------------------------------------%
% vim: ft=mercury ts=4 sw=4 et
%---------------------------------------------------------------------------%
% Copyright (C) 2026 The Mercury team.
% This file may only be copied under the terms of the GNU General
% Public License - see the file COPYING in the Mercury distribution.
%---------------------------------------------------------------------------%
%
% File: input_specialization.m.
% Author: zs.
%
% This module implements input specialization pragmas.
%
% Given
%
%   :- pragma input_spec(<type>, <replace_or_add>,
%       [inst_name1, ..., inst_nameN]).
%
% in either module M's .m file or its .int file,
%
% - it looks for predicates and/or functions in module M
%   one or more of whose argument types are <type>,
%
% - for each argument position for which that is tue,
%   it looks for modes that specify "in" in that argument position,
%
% - creates copies of those modes that replace "in" with "in(inst_nameI")
%   for all I in 1..N;
%
% - and either replaces the original mode with its modified copies
%   (if <replace_or_add> is replace_in_mode, or adds the modified copies
%   before the original mode (if <replace_or_add> is add_to_in_mode).
%
% If a predicate or function has more than one mode that specifies the "in"
% mode for argument to be input specialized, the same addition or replacement
% will happen for all of them.
%
% If a predicate or function has more than argument that should be input
% specialized, then the input to the process of specializing the Nth such
% argument is the mode list generated by specializing the previous N-1
% arguments. In other words, the final result will be a mode list that
% could be called a "cross product" of all the input specializations.
%
%---------------------------------------------------------------------------%

:- module hlds.input_specialization.

:- interface.

:- import_module hlds.hlds_module.

:- pred input_specialize_in_module(module_info::in, module_info::out) is det.

%---------------------------------------------------------------------------%

:- implementation.

:- import_module hlds.hlds_markers.
:- import_module hlds.hlds_pred.
:- import_module hlds.mode_util.
:- import_module libs.
:- import_module libs.maybe_util.
:- import_module mdbcomp.
:- import_module mdbcomp.builtin_modules.
:- import_module mdbcomp.sym_name.
:- import_module parse_tree.
:- import_module parse_tree.prog_data.
:- import_module parse_tree.prog_item_pragma.

:- import_module int.
:- import_module list.
:- import_module map.
:- import_module one_or_more.
:- import_module require.

%---------------------------------------------------------------------------%

input_specialize_in_module(!ModuleInfo) :-
    module_info_get_input_spec_table(!.ModuleInfo, InputSpecTable),
    module_info_get_valid_pred_ids(!.ModuleInfo, PredIds),
    list.foldl(maybe_input_specialize_in_pred(InputSpecTable), PredIds,
        !ModuleInfo).

:- pred maybe_input_specialize_in_pred(input_spec_table::in, pred_id::in,
    module_info::in, module_info::out) is det.

maybe_input_specialize_in_pred(InputSpecTable, PredId, !ModuleInfo) :-
    module_info_pred_info(!.ModuleInfo, PredId, PredInfo0),
    pred_info_get_module_name(PredInfo0, ModuleName),
    ( if map.search(InputSpecTable, ModuleName, InModuleMap) then
        input_specialize_in_pred_if_possible(!.ModuleInfo, InModuleMap,
            PredInfo0, PredInfo),
        module_info_set_pred_info(PredId, PredInfo, !ModuleInfo)
    else
        true
    ).

:- pred input_specialize_in_pred_if_possible(module_info::in,
    input_spec_in_module_map::in, pred_info::in, pred_info::out) is det.

input_specialize_in_pred_if_possible(ModuleInfo, InModuleMap, !PredInfo) :-
    pred_info_get_arg_types(!.PredInfo, ArgTypes),
    find_args_to_specialize(InModuleMap, 1, ArgTypes, ArgsToSpec),
    (
        ArgsToSpec = []
        % Pieces = [words("Error:")],
        % Spec = spec($pred, severity_error, phase_input_spec, Pieces),
        % !:Specs = [Spec | !.Specs]
    ;
        ArgsToSpec = [HeadArgToSpec | TailArgsToSpec],
        input_specialize_in_pred(ModuleInfo, HeadArgToSpec, TailArgsToSpec,
            !PredInfo)
    ).

:- type arg_to_specialize
    --->    arg_to_specialize(int, input_spec_info).
            % The argument number, and how to specialize it.

:- pred find_args_to_specialize(input_spec_in_module_map::in,
    int::in, list(mer_type)::in, list(arg_to_specialize)::out) is det.

find_args_to_specialize(_, _, [], []).
find_args_to_specialize(InModuleMap, ArgNum, [ArgType | ArgTypes],
        ArgsToSpec) :-
    find_args_to_specialize(InModuleMap, ArgNum + 1, ArgTypes,
        ArgsToSpecTail),
    % This search works only if the types in input_spec pragmas are ground.
    % At the moment, add_pragma_decl.m does require them to be ground.
    ( if map.search(InModuleMap, ArgType, InputSpecInfo) then
        ArgToSpec = arg_to_specialize(ArgNum, InputSpecInfo),
        ArgsToSpec = [ArgToSpec | ArgsToSpecTail]
    else
        ArgsToSpec = ArgsToSpecTail
    ).

%---------------------------------------------------------------------------%

:- pred input_specialize_in_pred(module_info::in,
    arg_to_specialize::in, list(arg_to_specialize)::in,
    pred_info::in, pred_info::out) is det.

input_specialize_in_pred(ModuleInfo, HeadArgToSpec, TailArgsToSpec,
        !PredInfo) :-
    HeadArgToSpec = arg_to_specialize(ArgNum, InputSpecInfo),
    pred_info_get_proc_table(!.PredInfo, ProcTable0),
    map.values(ProcTable0, ProcInfos0),
    input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum, InputSpecInfo,
        ProcInfos0, ProcInfos, _Changed),
    rebuild_proc_table_loop(0, ProcInfos, map.init, ProcTable),
    pred_info_set_proc_table(ProcTable, !PredInfo),
    pred_info_get_markers(!.PredInfo, Markers0),
    add_marker(marker_was_input_specialized, Markers0, Markers),
    pred_info_set_markers(Markers, !PredInfo),
    (
        TailArgsToSpec = []
    ;
        TailArgsToSpec = [HeadTailArgToSpec | TailTailArgsToSpec],
        input_specialize_in_pred(ModuleInfo,
            HeadTailArgToSpec, TailTailArgsToSpec, !PredInfo)
    ).

%---------------------------------------------------------------------------%

:- pred rebuild_proc_table_loop(int::in, list(proc_info)::in,
    proc_table::in, proc_table::out) is det.

rebuild_proc_table_loop(_, [], !ProcTable).
rebuild_proc_table_loop(ProcNum, [ProcInfo | ProcInfos], !ProcTable) :-
    proc_id_to_int(ProcId, ProcNum),
    map.det_insert(ProcId, ProcInfo, !ProcTable),
    rebuild_proc_table_loop(ProcNum + 1, ProcInfos, !ProcTable).

%---------------------------------------------------------------------------%

:- pred input_specialize_proc_table_in_given_arg(module_info::in,
    int::in, input_spec_info::in,
    list(proc_info)::in, list(proc_info)::out, maybe_changed::out) is det.

input_specialize_proc_table_in_given_arg(_, _, _, [], [], unchanged).
input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum, InputSpecInfo,
        [HeadProcInfo0 | TailProcInfos0], ProcInfos, Changed) :-
    proc_info_get_argmodes(HeadProcInfo0, ArgModes),
    list.det_index1(ArgModes, ArgNum, SelectedArgMode),
    ( if
        mode_get_insts_semidet(ModuleInfo, SelectedArgMode,
            InitInst, FinalInst),
        InitInst = FinalInst,
        (
            InitInst = ground(shared, none_or_default_func)
        ;
            InitInst = defined_inst(user_inst(SymName, [])),
            SymName = qualified(mercury_public_builtin_module, Name),
            ( Name = "in" ; Name = "input" )
        )
    then
        input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum,
            InputSpecInfo, TailProcInfos0, TailProcInfos, _Changed),
        InputSpecInfo = input_spec_info(ReplaceOrAdd, OoMInsts, _Context),
        SpecInsts = one_or_more_to_list(OoMInsts),
        create_input_specialized_proc_infos(ArgNum, ReplaceOrAdd, SpecInsts,
            HeadProcInfo0, SpecProcInfos),
        ProcInfos = SpecProcInfos ++ TailProcInfos,
        Changed = changed
    else
        input_specialize_proc_table_in_given_arg(ModuleInfo, ArgNum,
            InputSpecInfo, TailProcInfos0, TailProcInfos, Changed),
        ProcInfos = [HeadProcInfo0 | TailProcInfos]
    ).

:- pred create_input_specialized_proc_infos(int::in,
    replace_or_add_in_mode::in, list(mer_inst)::in,
    proc_info::in, list(proc_info)::out) is det.

create_input_specialized_proc_infos(ArgNum, ReplaceOrAdd, SpecInsts,
        OrigProcInfo, SpecProcInfos) :-
    (
        SpecInsts = [],
        (
            ReplaceOrAdd = replace_in_mode,
            SpecProcInfos = []
        ;
            ReplaceOrAdd = add_to_in_mode,
            SpecProcInfos = [OrigProcInfo]
        )
    ;
        SpecInsts = [HeadSpecInst | TailSpecInsts],

        proc_info_get_argmodes(OrigProcInfo, OrigModes),
        HeadSpecArgMode = from_to_mode(HeadSpecInst, HeadSpecInst),
        det_replace_nth_element1(ArgNum, HeadSpecArgMode,
            OrigModes, HeadSpecModes),
        proc_info_set_argmodes(HeadSpecModes,
            OrigProcInfo, HeadSpecProcInfo),
        create_input_specialized_proc_infos(ArgNum,
            ReplaceOrAdd, TailSpecInsts, OrigProcInfo, TailSpecProcInfos),
        SpecProcInfos = [HeadSpecProcInfo | TailSpecProcInfos]
    ).

%---------------------------------------------------------------------------%

% XXX I (zs) think these should be in library/list.m.

:- pred det_replace_nth_element1(int::in, T::in, list(T)::in, list(T)::out)
    is det.

det_replace_nth_element1(N, NewItem, Items0, Items) :-
    ( if replace_nth_element1(N, NewItem, Items0, ItemsPrime) then
        Items = ItemsPrime
    else
        unexpected($pred, "index out of range")
    ).

:- pred replace_nth_element1(int::in, T::in, list(T)::in, list(T)::out)
    is semidet.

replace_nth_element1(N, NewItem, Items0, Items) :-
    replace_nth_element0(N - 1, NewItem, Items0, Items).

:- pred replace_nth_element0(int::in, T::in, list(T)::in, list(T)::out)
    is semidet.

replace_nth_element0(N, NewItem, [Item0 | Items0], [Item | Items]) :-
    ( if N = 0 then
        Item = NewItem,
        Items = Items0
    else
        Item = Item0,
        replace_nth_element0(N - 1, NewItem, Items0, Items)
    ).

%---------------------------------------------------------------------------%
:- end_module hlds.input_specialization.
%---------------------------------------------------------------------------%
