       1:      1  1 CALL pred aadebug:main/2-0 (det) aadebug.m:11
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred aadebug:p/2-0 (nondet)
mdb> continue
       3:      2  2 CALL pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> finish
      15:      2  2 EXIT pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> dd
q('a', 'a')
Valid? yes
r('a', 10)
Valid? yes
s(10, 30)
Valid? yes
Found incorrect contour:
p('a', 30)
Is this a bug? yes
      15:      2  2 EXIT pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> continue
      18:      2  2 REDO pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> finish
      20:      2  2 EXIT pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> dd
Found incorrect contour:
p('a', 31)
Is this a bug? yes
      20:      2  2 EXIT pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> continue
      23:      2  2 REDO pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> finish
      35:      2  2 EXIT pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> dd
q('a', 'b')
Valid? yes
Call r('b', _)
No solutions.
Complete? yes
Call q('b', _)
No solutions.
Complete? yes
Found incorrect contour:
p('a', 32)
Is this a bug? yes
      35:      2  2 EXIT pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> continue
      38:      2  2 REDO pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> finish
      41:      2  2 FAIL pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> dd
Call q('a', _)
Solutions:
	q('a', 'a')
	q('a', 'b')
Complete? yes
Found partially uncovered atom:
p('a', _)
Is this a bug? yes
      41:      2  2 FAIL pred aadebug:p/2-0 (nondet) aadebug.m:24 (aadebug.m:9)
mdb> continue
no
