       1:      1  1 CALL pred app:main/2-0 (det) app.m:10
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break app
 0: + stop  interface pred app:app/3-0 (det)
mdb> continue
       2:      2  2 CALL pred app:app/3-0 (det) app.m:26 (app.m:13)
mdb> continue
       4:      3  3 CALL pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
       6:      4  4 CALL pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
       8:      5  5 CALL pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> finish -n
      16:      5  5 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> dd
app([|](4, [|](5, [])), [|](6, [|](7, [|]/2)), [|](4, [|](5, [|]/2)))
Valid? yes
No bug found.
      16:      5  5 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      17:      4  4 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      18:      3  3 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      19:      2  2 EXIT pred app:app/3-0 (det) app.m:26 (app.m:13)
mdb> dd
app([|](1, [|](2, [|]/2)), [|](6, [|](7, [|]/2)), [|](1, [|](2, [|]/2)))
Valid? no
app([|](2, [|](3, [|]/2)), [|](6, [|](7, [|]/2)), [|](2, [|](3, [|]/2)))
Valid? no
app([|](3, [|](4, [|]/2)), [|](6, [|](7, [|]/2)), [|](3, [|](4, [|]/2)))
Valid? no
Found incorrect contour:
app([|](3, [|](4, [|]/2)), [|](6, [|](7, [|]/2)), [|](3, [|](4, [|]/2)))
Is this a bug? yes
      17:      4  4 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      18:      3  3 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      19:      2  2 EXIT pred app:app/3-0 (det) app.m:26 (app.m:13)
mdb> continue
append([1, 2, 3, 4, 5], [6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]).
      20:      8  2 CALL pred app:app/3-0 (det) app.m:26 (app.m:18)
mdb> finish -n
      67:      8  2 EXIT pred app:app/3-0 (det) app.m:26 (app.m:18)
mdb> dd
app([|](1, [|](2, [|]/2)), [|](6, [|](7, [|]/2)), [|](1, [|](2, [|]/2)))
Valid? no
app([|](2, [|](3, [|]/2)), [|](6, [|](7, [|]/2)), [|](2, [|](3, [|]/2)))
Valid? no
app([|](3, [|](4, [|]/2)), [|](6, [|](7, [|]/2)), [|](3, [|](4, [|]/2)))
Valid? no
app([|](4, [|](5, [|]/2)), [|](6, [|](7, [|]/2)), [|](4, [|](5, [|]/2)))
Valid? no
app([|](5, [|](6, [|]/2)), [|](6, [|](7, [|]/2)), [|](5, [|](6, [|]/2)))
Valid? no
app([|](6, [|](7, [|]/2)), [|](6, [|](7, [|]/2)), [|](6, [|](7, [|]/2)))
Valid? no
app([|](7, [|](8, [|]/2)), [|](6, [|](7, [|]/2)), [|](7, [|](8, [|]/2)))
Valid? no
app([|](8, [|](9, [|]/2)), [|](6, [|](7, [|]/2)), [|](8, [|](9, [|]/2)))
Valid? no
app([|](9, [|](0, [|]/2)), [|](6, [|](7, [|]/2)), [|](9, [|](0, [|]/2)))
Valid? no
app([|](0, [|](1, [|]/2)), [|](6, [|](7, [|]/2)), [|](0, [|](1, [|]/2)))
Valid? no
Found incorrect contour:
app([|](3, [|](4, [|]/2)), [|](6, [|](7, [|]/2)), [|](3, [|](4, [|]/2)))
Is this a bug? yes
      55:     20 14 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      56:     19 13 EXIT pred app:app/3-0 (det) app.m:26 (app.m:28)
mdb> quit
mdb: are you sure you want to quit? y
