      E1:     C1 CALL pred app.main/2-0 (det) app.m:10
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break app
 0: + stop  interface pred app.app/3-0 (det)
mdb> continue
      E2:     C2 CALL pred app.app/3-0 (det) app.m:26 (app.m:13)
mdb> continue
      E3:     C3 CALL pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E4:     C4 CALL pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E5:     C5 CALL pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> finish -n
      E6:     C5 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> dd
app([4, 5], [6, 7, 8], [4, ...])
Valid? yes
app([3, 4, 5], [6, 7, 8], [3, ...])
Valid? quit
Diagnosis aborted.
      E6:     C5 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E7:     C4 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E8:     C3 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E9:     C2 EXIT pred app.app/3-0 (det) app.m:26 (app.m:13)
mdb> dd
app([1, 2, 3, 4, 5], [6, 7, ...], [|]/2)
Valid? no
app([2, 3, 4, 5], [6, 7, 8], [|]/2)
Valid? no
app([3, 4, 5], [6, 7, 8], [3, ...])
Valid? no
Found incorrect contour:
app([4, 5], [6, 7, 8], [4, ...])
app([3, 4, 5], [6, 7, 8], [3, ...])
Is this a bug? yes
      E7:     C4 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E8:     C3 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
      E9:     C2 EXIT pred app.app/3-0 (det) app.m:26 (app.m:13)
mdb> continue
append([1, 2, 3, 4, 5], [6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]).
     E10:     C6 CALL pred app.app/3-0 (det) app.m:26 (app.m:18)
mdb> finish -n
     E11:     C6 EXIT pred app.app/3-0 (det) app.m:26 (app.m:18)
mdb> dd
app([1, 2, 3, 4, 5, 6, 7, 8, ...], [|]/2, [|]/2)
Valid? no
app([2, 3, 4, 5, 6, 7, 8, 9, ...], [|]/2, [|]/2)
Valid? no
app([3, 4, 5, 6, 7, 8, 9, 0, ...], [|]/2, [|]/2)
Valid? no
app([4, 5, 6, 7, 8, 9, 0, 1, ...], [|]/2, [|]/2)
Valid? no
app([5, 6, 7, 8, 9, 0, 1, 2, ...], [|]/2, [|]/2)
Valid? no
app([6, 7, 8, 9, 0, 1, 2, 3, ...], [|]/2, [|]/2)
Valid? no
app([7, 8, 9, 0, 1, 2, 3, 4, ...], [|]/2, [|]/2)
Valid? no
app([8, 9, 0, 1, 2, 3, 4, 5], [|]/2, [|]/2)
Valid? no
app([9, 0, 1, 2, 3, 4, 5], [6, ...], [|]/2)
Valid? no
app([0, 1, 2, 3, 4, 5], [6, ...], [|]/2)
Valid? no
Found incorrect contour:
app([4, 5], [6, 7, 8], [4, ...])
app([3, 4, 5], [6, 7, 8], [3, ...])
Is this a bug? yes
     E12:     C7 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> continue
     E13:     C8 EXIT pred app.app/3-0 (det) app.m:26 (app.m:28)
mdb> quit
mdb: are you sure you want to quit? y
