      E1:     C1 CALL pred binary_search.main/2-0 (det) binary_search.m:15
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> break a
 0: + stop  interface pred binary_search.a/1-0 (det)
mdb> c
      E2:     C2 CALL pred binary_search.a/1-0 (det)
mdb> f
      E3:     C2 EXIT pred binary_search.a/1-0 (det)
mdb> dd -d 3 -n 7
a(yes)
Valid? b 1
browser> mark
silly_even(0, yes)
Valid? y
sillier_even(504, yes)
Valid? y
silly_even(771, yes)
Valid? n
sillier_even(657, yes)
Valid? n
silly_even(600, yes)
Valid? y
silly_even(627, yes)
Valid? n
silly_even(616, yes)
Valid? y
sillier_even(621, yes)
Valid? n
silly_even(618, yes)
Valid? y
sillier_even(619, yes)
Valid? n
silly_even(619, yes)
Valid? n
Found incorrect contour:
silly_even(618, yes)
silly_even(619, yes)
Is this a bug? y
      E4:     C3 EXIT pred binary_search.silly_even/2-0 (det)
mdb> trust binary_search_1
Trusting module binary_search_1
mdb> break b
 1: + stop  interface pred binary_search.b/1-0 (det)
mdb> delete 0
 0: E stop  interface pred binary_search.a/1-0 (det)
mdb> c
      E5:     C4 CALL pred binary_search.b/1-0 (det)
mdb> f
      E6:     C4 EXIT pred binary_search.b/1-0 (det)
mdb> dd -d 3 -n 7
b(yes)
Valid? b 1
browser> mark
Found incorrect contour:
silly_even(618, yes)
silly_even(619, yes)
Is this a bug? y
      E7:     C5 EXIT pred binary_search.silly_even/2-0 (det)
mdb> delete 1
 1: E stop  interface pred binary_search.b/1-0 (det)
mdb> break add1s
 0: + stop  interface pred binary_search.add1s/2-0 (det)
mdb> c
      E8:     C6 CALL pred binary_search.add1s/2-0 (det)
mdb> delete 0
 0: E stop  interface pred binary_search.add1s/2-0 (det)
mdb> f
      E9:     C6 EXIT pred binary_search.add1s/2-0 (det)
mdb> dd -d 3 -n 7
add1s([1, 2, 3, 4, 5, 6, 7, 8, ...], [|]/2)
Valid? b 2
browser> ls
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
browser> cdr 9 2
browser> ls
[11]
browser> cd 1
browser> mark
add1s([10], [11])
Valid? y
add1s([5, 6, 7, 8, 9, 10], [6, ...])
Valid? n
add1s([7, 8, 9, 10], [8, 9, 10, ...])
Valid? y
add1s([6, 7, 8, 9, 10], [7, 8, ...])
Valid? n
Found incorrect contour:
add1s([7, 8, 9, 10], [8, 9, 10, ...])
add1s([6, 7, 8, 9, 10], [7, 8, ...])
Is this a bug? y
     E10:     C7 EXIT pred binary_search.add1s/2-0 (det)
mdb> c
yesyes[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
