       1:      1  1 CALL pred browse_arg.main/2-0 (det) browse_arg.m:7
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred browse_arg.p/2-0 (det)
mdb> continue
       2:      2  2 CALL pred browse_arg.p/2-0 (det) browse_arg.m:19 (browse_arg.m:8)
mdb> finish
       3:      2  2 EXIT pred browse_arg.p/2-0 (det) browse_arg.m:19 (browse_arg.m:8)
mdb> set depth 10
mdb> set xml_browser_cmd 'cat ./browse_arg.xml.out'
mdb> set xml_tmp_filename './browse_arg.xml.out'
mdb> dd
p(1, baz(1, bar))
Valid? browse 2
browser> ls
baz(1, bar)
browser> quit
p(1, baz(1, bar))
Valid? set format verbose
p
1-1
2-baz
  1-1
  2-bar

Valid? set -B format pretty
p
1-1
2-baz
  1-1
  2-bar

Valid? set -P format pretty
p(1, baz(1, bar))
Valid? b -x 2
Saving term to XML file...
Launching XML browser (this may take some time) ...
<?xml version="1.0"?>
<baz functor="baz" type="browse_arg.foo" arity="2">
	<Int type="int">1</Int>
	<bar functor="bar" type="browse_arg.foo" arity="0" />
</baz>
p(1, baz(1, bar))
Valid? b --xml
Saving term to XML file...
Launching XML browser (this may take some time) ...
<?xml version="1.0"?>
<predicate functor="predicate" type="mdb.browse.xml_predicate_wrapper" arity="2">
	<String type="string" field="predicate_name">browse_arg.p</String>
	<List functor="[|]" field="predicate_arguments" type="list.list(std_util.univ)" arity="2">
		<univ_cons functor="univ_cons" type="std_util.univ" arity="1">
			<Int type="int">1</Int>
		</univ_cons>
		<List functor="[|]" type="list.list(std_util.univ)" arity="2">
			<univ_cons functor="univ_cons" type="std_util.univ" arity="1">
				<baz functor="baz" type="browse_arg.foo" arity="2">
					<Int type="int">1</Int>
					<bar functor="bar" type="browse_arg.foo" arity="0" />
				</baz>
			</univ_cons>
			<Nil functor="[]" type="list.list(std_util.univ)" arity="0" />
		</List>
	</List>
</predicate>
p(1, baz(1, bar))
Valid? no
Found incorrect contour:
p(1, baz(1, bar))
Is this a bug? yes
       3:      2  2 EXIT pred browse_arg.p/2-0 (det) browse_arg.m:19 (browse_arg.m:8)
mdb> continue
baz(1, bar)
