       1:      1  1 CALL pred confirm_abort.main/2-0 (det) confirm_abort.m:7
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred confirm_abort.p/1-0 (det)
mdb> continue
       2:      2  2 CALL pred confirm_abort.p/1-0 (det) confirm_abort.m:15 (confirm_abort.m:8)
mdb> finish
       5:      2  2 EXIT pred confirm_abort.p/1-0 (det) confirm_abort.m:15 (confirm_abort.m:8)
mdb> dd
p(27)
Valid? no
q(27)
Valid? no
Found incorrect contour:
q(27)
Is this a bug? help
Answer one of:
	y	yes		confirm that the suspect is a bug
	n	no		do not accept that the suspect is a bug
	a	abort		abort this diagnosis session and return to mdb
	h, ?	help		this help message
Found incorrect contour:
q(27)
Is this a bug? h
Answer one of:
	y	yes		confirm that the suspect is a bug
	n	no		do not accept that the suspect is a bug
	a	abort		abort this diagnosis session and return to mdb
	h, ?	help		this help message
Found incorrect contour:
q(27)
Is this a bug? ?
Answer one of:
	y	yes		confirm that the suspect is a bug
	n	no		do not accept that the suspect is a bug
	a	abort		abort this diagnosis session and return to mdb
	h, ?	help		this help message
Found incorrect contour:
q(27)
Is this a bug? abort
       5:      2  2 EXIT pred confirm_abort.p/1-0 (det) confirm_abort.m:15 (confirm_abort.m:8)
mdb> dd
p(27)
Valid? [no] n
Found incorrect contour:
q(27)
Is this a bug? a
       5:      2  2 EXIT pred confirm_abort.p/1-0 (det) confirm_abort.m:15 (confirm_abort.m:8)
mdb> dd
p(27)
Valid? [no] n
Found incorrect contour:
q(27)
Is this a bug? y
       4:      3  3 EXIT pred confirm_abort.q/1-0 (det) confirm_abort.m:19 (confirm_abort.m:15)
mdb> quit -y
