       1:      1  1 CALL pred dependency:main/2-0 (cc_multi) dependency.m:11
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> goto 3
       3:      2  2 EXIT pred dependency:turn_on_origin_debug/0-0 (det) dependency.m:69 (dependency.m:12)
mdb> dd
turn_on_origin_debug
Valid? browse 1
Invalid argument number
turn_on_origin_debug
Valid? abort
Diagnosis aborted.
       3:      2  2 EXIT pred dependency:turn_on_origin_debug/0-0 (det) dependency.m:69 (dependency.m:12)
mdb> step
       4:      3  2 CALL pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> finish
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> set depth 20
mdb> set size 201
mdb> set format pretty
mdb> proc_body
	
proc_rep(
  [|](2, []), 
  conj_rep(
    [|](
      atomic_goal_rep(
        det_rep, 
        "dependency.m", 
        20, 
        [|](3, []), 
        plain_call_rep("dependency", "p", [|](3, []))), 
      [|](
        ite_rep(atomic_goal_rep/5, atomic_goal_rep/5, atomic_goal_rep/5), 
        [|](atomic_goal_rep/5, [|](switch_rep([|]/2), [|](disj_rep([|]/2), [])))))))
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^1
browser> mark
Origin: primitive_op("dependency.m", 22)
p(1)
Valid? abort
Diagnosis aborted.
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^2^1
browser> mark
Origin: output(r, any_head_var(4), [1])
r(1, [3, 4], 3 - 4)
Valid? browse 2
browser> print
[3, 4]
browser> mark
Origin: primitive_op("dependency.m", 29)
p(1)
Valid? abort
Diagnosis aborted.
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^2^2^1
browser> mark
Origin: primitive_op("dependency.m", 41)
p(1)
Valid? abort
Diagnosis aborted.
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^2^2^2^1
browser> mark
Origin: primitive_op("dependency.m", 22)
p(1)
Valid? abort
Diagnosis aborted.
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^2^2^2^2^1
browser> mark
Origin: output(r, any_head_var(4), [1])
r(1, [3, 4], 3 - 4)
Valid? abort
Diagnosis aborted.
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^2^2^2^2^2
browser> mark
Origin: primitive_op("dependency.m", 43)
p(1)
Valid? abort
Diagnosis aborted.
      18:      3  2 EXIT pred dependency:test/1-0 (cc_multi) dependency.m:19 (dependency.m:13)
mdb> continue
[1, 3, 6, 1, 3].
