       1:      1  1 CALL pred dependency2:main/2-0 (cc_multi) dependency2.m:11
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break dependency2__test
 0: + stop  interface pred dependency2:test/1-0 (cc_multi)
mdb> continue
       4:      3  2 CALL pred dependency2:test/1-0 (cc_multi) dependency2.m:19 (dependency2.m:13)
mdb> finish
      18:      3  2 EXIT pred dependency2:test/1-0 (cc_multi) dependency2.m:19 (dependency2.m:13)
mdb> dd
test([1, 3, 6, 1, 3])
Valid? browse 1
browser> ^2^1
browser> mark
Origin: output(r, any_head_var(4), [1])
r(1, [3, 4], 3 - 4)
Valid? browse 2
browser> print
[3, 4]
browser> mark
Origin: primitive_op("dependency2.m", 29)
p(1)
Valid? yes
Origin: primitive_op("dependency2.m", 29)
q(no)
Valid? yes
Found incorrect contour:
test([1, 3, 6, 1, 3])
Is this a bug? yes
      18:      3  2 EXIT pred dependency2:test/1-0 (cc_multi) dependency2.m:19 (dependency2.m:13)
mdb> continue
[1, 3, 6, 1, 3].
