      E1:     C1 CALL pred failed_cond.main/2-0 (det) failed_cond.m:12
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> step
      E2:     C2 CALL pred failed_cond.p/1-0 (det)
mdb> finish
      E3:     C2 EXIT pred failed_cond.p/1-0 (det)
mdb> dd -d 3 -n 7
p(b)
Valid? no
q(c, b)
Valid? no
Call r(c)
Unsatisfiable? browse 1
browser> mark
Found inadmissible call:
Parent q(c, _)
Call r(c)
Is this a bug? yes
      E4:     C3 EXIT pred failed_cond.q/2-0 (det)
mdb> quit -y
