       1:      1  1 CALL pred family:main/2-0 (det) family.m:7
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break half_siblings
 0: + stop  interface pred family:half_siblings/2-0 (nondet)
mdb> continue
       3:      2  2 CALL pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> finish
     268:      2  2 EXIT pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> dd
half_siblings(a, b)
Valid? no
siblings(a, b)
Valid? yes
Call full_siblings(_, _)
No solutions.
Complete? no
common_mother(a, b)
Valid? yes
Call common_father(_, _)
No solutions.
Complete? no
parent(m, a)
Valid? yes
Call parent(a, _)
No solutions.
Complete? yes
parent(m, b)
Valid? yes
Call parent(b, _)
No solutions.
Complete? yes
parent(f, a)
Valid? yes
parent(f, b)
Valid? yes
parent(f, c)
Valid? yes
Call parent(c, _)
No solutions.
Complete? yes
parent(s, c)
Valid? yes
Call parent(_, _)
Solutions:
	parent(m, a)
	parent(m, b)
	parent(f, a)
	parent(f, b)
	parent(f, c)
	parent(s, c)
Complete? yes
Found partially uncovered atom:
common_father(_, _)
Is this a bug? yes
      86:     15  4 FAIL pred family:common_father/2-0 (nondet) family.m:58 (family.m:77)
mdb> continue
     268:      2  2 EXIT pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> continue
     269:      2  2 REDO pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> finish
     530:      2  2 EXIT pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> dd
half_siblings(b, a)
Valid? no
Found partially uncovered atom:
common_father(_, _)
Is this a bug? yes
     401:     70  4 FAIL pred family:common_father/2-0 (nondet) family.m:58 (family.m:77)
mdb> continue
     530:      2  2 EXIT pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> continue
     531:      2  2 REDO pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> finish
     695:      2  2 FAIL pred family:half_siblings/2-0 (nondet) family.m:82 (family.m:9)
mdb> dd
Call half_siblings(_, _)
Solutions:
	half_siblings(a, b)
	half_siblings(b, a)
Complete? no
Found partially uncovered atom:
common_father(_, _)
Is this a bug? yes
     401:     70  4 FAIL pred family:common_father/2-0 (nondet) family.m:58 (family.m:77)
mdb> quit -y
