      E1:     C1  1 CALL pred filter:main/2-0 (det) filter.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred filter:p/1-0 (multi)
mdb> continue
      E2:     C2  2 CALL pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      E3:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 9])
Valid? no
s1([1, 2])
Valid? yes
s2([9])
Valid? yes
my_append([1, 2], [9], [1, 2, 9])
Valid? yes
Found incorrect contour:
p([1, 2, 9])
Is this a bug? yes
      E3:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      E4:     C2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      E5:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 7, 8, 9])
Valid? no
s2([7, 8, 9])
Valid? yes
my_append([1, 2], [7, 8, 9], [1, ...])
Valid? yes
Found incorrect contour:
p([1, 2, 7, 8, 9])
Is this a bug? yes
      E5:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      E6:     C2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      E7:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 3, 9])
Valid? no
s1([1, 2, 3])
Valid? yes
my_append([1, 2, 3], [9], [1, 2, ...])
Valid? yes
Found incorrect contour:
p([1, 2, 3, 9])
Is this a bug? yes
      E7:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      E8:     C2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      E9:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 3, 7, 8, 9])
Valid? no
my_append([1, 2, 3], [7, 8, 9], [1, ...])
Valid? yes
Found incorrect contour:
p([1, 2, 3, 7, 8, 9])
Is this a bug? yes
      E9:     C2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
     E10:     C2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
     E11:     C2  2 FAIL pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
Call p(_)
Solutions:
	p([1, 2, 9])
	p([1, 2, 7, 8, 9])
	p([1, 2, 3, 9])
	p([1, 2, 3, 7, 8, 9])
Complete? no
Call s2(_)
Solutions:
	s2([9])
	s2([7, 8, 9])
Complete? yes
Call s1(_)
Solutions:
	s1([1, 2])
	s1([1, 2, 3])
Complete? yes
Found partially uncovered atom:
p(_)
Is this a bug? yes
     E11:     C2  2 FAIL pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
no
