       1:      1  1 CALL pred filter:main/2-0 (det) filter.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred filter:p/1-0 (multi)
mdb> continue
       3:      2  2 CALL pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      12:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 9])
Valid? no
s1([1, 2])
Valid? yes
s2([9])
Valid? yes
my_append([1, 2], [9], [1, 2, 9])
Valid? yes
Found incorrect contour:
p([1, 2, 9])
Is this a bug? yes
      12:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      17:      2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      23:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 7, 8, 9])
Valid? no
s2([7, 8, 9])
Valid? yes
pred my_append
	[1, 2]
	[7, 8, 9]
	[1, 2, 7, 8, 9]
Valid? yes
Found incorrect contour:
p([1, 2, 7, 8, 9])
Is this a bug? yes
      23:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      28:      2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      39:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 3, 9])
Valid? no
s1([1, 2, 3])
Valid? yes
pred my_append
	[1, 2, 3]
	[9]
	[1, 2, 3, 9]
Valid? yes
Found incorrect contour:
p([1, 2, 3, 9])
Is this a bug? yes
      39:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      44:      2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      50:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
p([1, 2, 3, 7, 8, 9])
Valid? no
pred my_append
	[1, 2, 3]
	[7, 8, 9]
	[1, 2, 3, 7, 8, 9]
Valid? yes
Found incorrect contour:
p([1, 2, 3, 7, 8, 9])
Is this a bug? yes
      50:      2  2 EXIT pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
      55:      2  2 REDO pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> finish
      60:      2  2 FAIL pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> dd
Call p(_)
Solutions:
	p([1, 2, 9])
	p([1, 2, 7, 8, 9])
	p([1, 2, 3, 9])
	p([1, 2, 3, 7, 8, 9])
Complete? no
Call s2(_)
Solutions:
	s2([9])
	s2([7, 8, 9])
Complete? yes
Call s1(_)
Solutions:
	s1([1, 2])
	s1([1, 2, 3])
Complete? yes
Found partially uncovered atom:
p(_)
Is this a bug? yes
      60:      2  2 FAIL pred filter:p/1-0 (multi) filter.m:20 (filter.m:10)
mdb> continue
no
