       1:      1  1 CALL pred func_call:main/2-0 (det) func_call.m:8
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break fib
 0: + stop  interface func func_call:fib/1-0 (det)
mdb> continue
       2:      2  2 CALL func func_call:fib/1-0 (det) func_call.m:14 (func_call.m:9)
mdb> finish -n
      69:      2  2 EXIT func func_call:fib/1-0 (det) func_call.m:14 (func_call.m:9)
mdb> dd
fib(6) = 9
Valid? no
fib(5) = 6
Valid? no
fib(4) = 4
Valid? no
fib(3) = 3
Valid? yes
fib(1) = 1
Valid? yes
Found incorrect contour:
fib(4) = 4
Is this a bug? yes
      35:      4  4 EXIT func func_call:fib/1-0 (det) func_call.m:14 (func_call.m:20)
mdb> quit -y
