      E1:     C1 CALL pred ignore.main/2-0 (det) ignore.m:13
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> trust ignore_1
Trusting module ignore_1
mdb> step
      E2:     C2 CALL pred ignore.p/1-0 (det)
mdb> finish
      E3:     C2 EXIT pred ignore.p/1-0 (det)
mdb> dd
p(15)
Valid? b 1
browser> mark
q(1, 0) = 1
Valid? n
Found incorrect contour:
q(1, 0) = 1
Is this a bug? y
      E4:     C3 EXIT func ignore.q/2-0 (det)
mdb> break 15
 0: + stop  linenumber ignore.m:15
mdb> continue
      E5:     C4 CALL pred ignore.p/1-0 (det)
mdb> finish
      E6:     C4 EXIT pred ignore.p/1-0 (det)
mdb> dd
p(15)
Valid? n
Found incorrect contour:
q(1, 0) = 1
Is this a bug? n
q(1, 0) = 1
Valid? [no] y
q(2, 1) = 3
Valid? y
q(3, 3) = 6
Valid? y
q(4, 6) = 10
Valid? y
q(5, 10) = 15
Valid? y
Found incorrect contour:
fold(q, [1, 2, 3, 4, 5], 0) = 15
p(15)
Is this a bug? y
      E6:     C4 EXIT pred ignore.p/1-0 (det)
mdb> quit -y
