      E1:     C1 CALL pred info.main/2-0 (det) info.m:13
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> break info.last
 0: + stop  interface pred info.last/2-0 (semidet)
mdb> c
      E2:     C2 CALL pred info.last/2-0 (semidet)
mdb> delete *
 0: E stop  interface pred info.last/2-0 (semidet)
mdb> f
      E3:     C2 EXIT pred info.last/2-0 (semidet)
mdb> dd -d 3 -n 7 -s divide_and_query
last([1, 2, 3, 4, 5, 6, 7, 8, ...], t/1)
Valid? info
Context of current question   : info.m:43 (info.m:15)
Search mode                   : divide and query     
Estimated questions remaining : 5                    
Number of suspect events      : 30                   
The current question was chosen because this is the node where the `dd'
command was issued.
dd> n
last([6, 7, 8, 9, 10], t(10))
Valid? info
Context of current question   : info.m:43 (info.m:45)
Search mode                   : divide and query     
Estimated questions remaining : 5                    
Number of suspect events      : 30                   
The current question was chosen because this node divides the suspect
area into two regions of 15 and 15 events each.
dd> n
last([9, 10], t(10))
Valid? info
Context of current question   : info.m:43 (info.m:45)
Search mode                   : divide and query     
Estimated questions remaining : 4                    
Number of suspect events      : 15                   
The current question was chosen because this node divides the suspect
area into two regions of 9 and 6 events each.
dd> q
Diagnosis aborted.
      E3:     C2 EXIT pred info.last/2-0 (semidet)
mdb> 
      E4:     C3 CALL pred info.last/2-0 (semidet)
mdb> f
      E5:     C3 EXIT pred info.last/2-0 (semidet)
mdb> dd -d 3 -n 7
last([101, 112, 103, 104, 105, 106, 107, 108], t/1)
Valid? n
last([112, 103, 104, 105, 106, 107, 108], t(108))
Valid? info
Context of current question : info.m:43 (info.m:45)
Search mode                 : top down             
The current question was chosen because this is the next node in the
top-down search.
dd> b 2
browser> mark
last([108], t(108))
Valid? info
Context of current question : info.m:43 (info.m:45)
Search mode                 : top down             
The current question was chosen because the marked subterm was bound by
the unification inside the predicate info.last/2 (info.m:43). The path
to the subterm in the atom is 2.
dd> mode binary
last([105, 106, 107, 108], t(108))
Valid? info
Context of current question : info.m:43 (info.m:45)
Search mode                 : binary search on path
The current question was chosen because this node divides a path of
length 7 into two paths of length 3 and 4.
dd> n
last([107, 108], t(108))
Valid? info
Context of current question : info.m:43 (info.m:45)
Search mode                 : binary search on path
The current question was chosen because this node divides a path of
length 3 into two paths of length 1 and 2.
dd> b 1
browser> cd 1
browser> mark
last([106, 107, 108], t(108))
Valid? info
Context of current question : info.m:43 (info.m:45)
Search mode                 : top down             
The current question was chosen because tracking of the marked subterm
was stopped here, because the binding node lies in a portion of the tree
which has been eliminated.
dd> q
Diagnosis aborted.
      E5:     C3 EXIT pred info.last/2-0 (semidet)
mdb> break q
 0: + stop  interface pred info.q/4-0 (det)
mdb> c
      E6:     C4 CALL pred info.q/4-0 (det)
mdb> delete *
 0: E stop  interface pred info.q/4-0 (det)
mdb> f
      E7:     C4 EXIT pred info.q/4-0 (det)
mdb> dd -d 3 -n 7
q(0, "lala", t(t(t("lala"))), 2)
Valid? b 3
browser> cd 1/1
browser> mark
f(0, "lala") = t(t(t("lala")))
Valid? info
Context of current question : info.m:51 (info.m:34)
Search mode                 : top down             
The current question was chosen because the marked subterm was bound by
the unification inside the function info.f/3 (info.m:52). The path to
the subterm in the atom is 3/1/1.
dd> q
Diagnosis aborted.
      E7:     C4 EXIT pred info.q/4-0 (det)
mdb> 
      E8:     C5 CALL pred info.q/4-0 (det)
mdb> f
      E9:     C5 EXIT pred info.q/4-0 (det)
mdb> dd -d 3 -n 7
q(1, "lala", t(t(t("lala"))), 2)
Valid? b 4
browser> mark
fproc(1) = 2
Valid? info
Context of current question : info.m:57 (info.m:37)
Search mode                 : top down             
The current question was chosen because the marked subterm was bound by
the foreign procedure call inside the function info.fproc/2 (info.m:57).
The path to the subterm in the atom is 2.
dd> n
Found incorrect contour:
fproc(1) = 2
Is this a bug? n
fproc(1) = 2
Valid? [no] info
Context of current question : info.m:57 (info.m:37)
Search mode                 : top down             
The current question was chosen because this question is being
revisited, because of an unsuccessful previous bug search.
dd> q
Diagnosis aborted.
      E9:     C5 EXIT pred info.q/4-0 (det)
mdb> quit -y
