      E1:     C1  1 CALL pred input_term_dep:main/2-0 (det) input_term_dep.m:9
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred input_term_dep:p/3-0 (det)
mdb> break q
 1: + stop  interface pred input_term_dep:q/1-0 (semidet)
mdb> break r
 2: + stop  interface pred input_term_dep:r/2-0 (det)
mdb> break s
 3: + stop  interface pred input_term_dep:s/1-0 (semidet)
mdb> continue
      E2:     C2  3 CALL pred input_term_dep:p/3-0 (det) input_term_dep.m:33 (input_term_dep.m:22)
mdb> finish
      E3:     C2  3 EXIT pred input_term_dep:p/3-0 (det) input_term_dep.m:33 (input_term_dep.m:22)
mdb> dd
p(5, 8, 13)
Valid? browse 3
browser> mark
pc(5, 13)
Valid? browse 1
browser> mark
pa(5)
Valid? yes
pb(8)
Valid? yes
Found incorrect contour:
p(5, 8, 13)
Is this a bug? yes
      E3:     C2  3 EXIT pred input_term_dep:p/3-0 (det) input_term_dep.m:33 (input_term_dep.m:22)
mdb> continue
5
8
13
      E4:     C3  3 CALL pred input_term_dep:q/1-0 (semidet) input_term_dep.m:69 (input_term_dep.m:58)
mdb> finish
      E5:     C3  3 EXIT pred input_term_dep:q/1-0 (semidet) input_term_dep.m:69 (input_term_dep.m:58)
mdb> dd
q([[2, 3], [], [1]])
Valid? browse 1
browser> mark 1/2
qc([[2, ...], [], [1]], [[2, ...], [], [1]])
Valid? browse 1
browser> mark 1/2
qa([[1], [2, 3]])
Valid? yes
qb([])
Valid? yes
Found incorrect contour:
q([[2, 3], [], [1]])
Is this a bug? yes
      E5:     C3  3 EXIT pred input_term_dep:q/1-0 (semidet) input_term_dep.m:69 (input_term_dep.m:58)
mdb> continue
[[2, 3], [], [1]]
      E6:     C4  3 CALL pred input_term_dep:r/2-0 (det) input_term_dep.m:111 (input_term_dep.m:93)
mdb> finish
      E7:     C4  3 EXIT pred input_term_dep:r/2-0 (det) input_term_dep.m:111 (input_term_dep.m:93)
mdb> dd
r(1, 33)
Valid? browse 2
browser> mark
rc(3, 33)
Valid? browse 1
browser> mark
ra(1, 3)
Valid? yes
rb(3)
Valid? yes
Found incorrect contour:
r(1, 33)
Is this a bug? yes
      E7:     C4  3 EXIT pred input_term_dep:r/2-0 (det) input_term_dep.m:111 (input_term_dep.m:93)
mdb> continue
33
      E8:     C5  3 CALL pred input_term_dep:s/1-0 (semidet) input_term_dep.m:146 (input_term_dep.m:135)
mdb> finish
      E9:     C5  3 EXIT pred input_term_dep:s/1-0 (semidet) input_term_dep.m:146 (input_term_dep.m:135)
mdb> dd
s(1)
Valid? no
sa(1, 7)
Valid? skip
sb(7)
Valid? skip
sc(7)
Valid? browse 1
browser> mark
sa(1, 7)
Valid? yes
sb(7)
Valid? yes
Found incorrect contour:
s(1)
Is this a bug? yes
      E9:     C5  3 EXIT pred input_term_dep:s/1-0 (semidet) input_term_dep.m:146 (input_term_dep.m:135)
mdb> continue
yes
