      E1:     C1 CALL pred io_stream_test.main/2-0 (det) io_stream_test.m:16
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> context none
Contexts will not be printed.
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> break io_stream_test__test
 0: + stop  interface pred io_stream_test.test/4-0 (det)
mdb> continue
      E2:     C2 CALL pred io_stream_test.test/4-0 (det)
mdb> print *
       Stream (arg 1)         	stream(0, input, text, file("tabled_read_decl.data"))
mdb> finish -n
      E3:     C2 EXIT pred io_stream_test.test/4-0 (det)
mdb> print *
       Stream (arg 1)         	stream(0, input, text, file("tabled_read_decl.data"))
       N (arg 2)              	1123
mdb> print
test(stream(0, input, text, file("tabled_read_decl.data")), 1123, _, _)
mdb> dd -a
test(stream(0, input, text, file("tabled_read_decl.data")), 1456, _, _)
Valid? print 1-2
stream(0, input, text, file("tabled_read_decl.data"))
1456
test(stream(0, input, text, file("tabled_read_decl.data")), 1456, _, _)
Valid? p io 1-2
No such IO action.
test(stream(0, input, text, file("tabled_read_decl.data")), 1456, _, _)
Valid? no
test_2(stream(0, input, text, file("tabled_read_decl.data")), 1, 1456, _, _)
Valid? yes
Found incorrect contour:
test_2(stream(0, input, text, file("tabled_read_decl.data")), 1, 1456, _, _)
test(stream(0, input, text, file("tabled_read_decl.data")), 1456, _, _)
Is this a bug? yes
      E3:     C2 EXIT pred io_stream_test.test/4-0 (det)
mdb> c -n -S
1789
142
