       1:      1  1 CALL pred lpe_example.main/2-0 (det) lpe_example.m:8
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred lpe_example.p/2-0 (nondet)
mdb> continue
       2:      2  2 CALL pred lpe_example.p/2-0 (nondet)
mdb> finish
      10:      2  2 EXIT pred lpe_example.p/2-0 (nondet)
mdb> dd
p(1, 13)
Valid? no
q(3)
Valid? yes
r(3, 13)
Valid? yes
Found incorrect contour:
p(1, 13)
Is this a bug? yes
      10:      2  2 EXIT pred lpe_example.p/2-0 (nondet)
mdb> continue
      11:      2  2 REDO pred lpe_example.p/2-0 (nondet)
mdb> finish
      15:      2  2 EXIT pred lpe_example.p/2-0 (nondet)
mdb> dd
p(1, 23)
Valid? no
r(3, 23)
Valid? yes
Found incorrect contour:
p(1, 23)
Is this a bug? yes
      15:      2  2 EXIT pred lpe_example.p/2-0 (nondet)
mdb> continue
      16:      2  2 REDO pred lpe_example.p/2-0 (nondet)
mdb> finish
      20:      2  2 EXIT pred lpe_example.p/2-0 (nondet)
mdb> dd
p(1, 3)
Valid? no
Found incorrect contour:
p(1, 3)
Is this a bug? yes
      20:      2  2 EXIT pred lpe_example.p/2-0 (nondet)
mdb> continue
      21:      2  2 REDO pred lpe_example.p/2-0 (nondet)
mdb> finish
      22:      2  2 FAIL pred lpe_example.p/2-0 (nondet)
mdb> dd
Call p(1, _)
Solutions:
	p(1, 13)
	p(1, 23)
	p(1, 3)
Complete? no
Call r(3, _)
Solutions:
	r(3, 13)
	r(3, 23)
Complete? yes
Found partially uncovered atom:
p(1, _)
Is this a bug? yes
      22:      2  2 FAIL pred lpe_example.p/2-0 (nondet)
mdb> continue
[3, 13, 23]
