      E1:     C1 CALL pred mapinit.main/2-0 (det) mapinit.m:28
mdb> echo on
Command echo enabled.
mdb> step
      E2:     C2 CALL pred mapinit.xmap_init/1-0 (det) mapinit.m:37 (mapinit.m:29)
mdb> finish
      E3:     C2 EXIT pred mapinit.xmap_init/1-0 (det) mapinit.m:37 (mapinit.m:29)
mdb> dd
xmap_init(empty)
Valid? a
Diagnosis aborted.
      E3:     C2 EXIT pred mapinit.xmap_init/1-0 (det) mapinit.m:37 (mapinit.m:29)
mdb> c
two(0, "zero", empty, empty)
