       1:      1  1 CALL pred oracle_db:main/2-0 (det) oracle_db.m:12
mdb> echo on
Command echo enabled.
mdb> break a
Registering debuggable procedures... done.
There is one debuggable module, with 3 procedures.
 0: + stop  interface pred oracle_db:a/3-0 (semidet)
mdb> continue
       3:      2  2 CALL pred oracle_db:a/3-0 (semidet) oracle_db.m:19 (oracle_db.m:9)
mdb> finish
      10:      2  2 EXIT pred oracle_db:a/3-0 (semidet) oracle_db.m:19 (oracle_db.m:9)
mdb> dd
atom("a", [univ(99 : int), univ(99 : int), univ(99 : int)])
Valid? no
atom("b", [univ(99 : int)])
Valid? yes
e_bug(dynamic(id('<<c_pointer>>')))
      10:      2  2 EXIT pred oracle_db:a/3-0 (semidet) oracle_db.m:19 (oracle_db.m:9)
mdb> continue
yes.
