       1:      1  1 CALL pred oracle_db:main/2-0 (det) 
mdb> echo on
Command echo enabled.
mdb> goto 9
       9:      2  2 EXIT pred oracle_db:a/3-0 (semidet) 
mdb> dd_wrong
a(99, 99, 99)
Valid? n
b(99)
Valid? y
Incorrect instance found:

a(99, 99, 99) :-
	b(99),
	b(99),
	b(99).

       9:      2  2 EXIT pred oracle_db:a/3-0 (semidet) 
mdb> continue -a
      10:      1  1 THEN pred oracle_db:main/2-0 (det) t;
yes.
      11:      1  1 EXIT pred oracle_db:main/2-0 (det) 
