       1:      1  1 CALL pred oracle_db.main/2-0 (det) oracle_db.m:12
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred oracle_db.a/3-0 (semidet)
mdb> continue
       3:      2  2 CALL pred oracle_db.a/3-0 (semidet) oracle_db.m:19 (oracle_db.m:9)
mdb> finish
      10:      2  2 EXIT pred oracle_db.a/3-0 (semidet) oracle_db.m:19 (oracle_db.m:9)
mdb> dd
a(99, 99, 99)
Valid? no
b(99)
Valid? yes
Found incorrect contour:
a(99, 99, 99)
Is this a bug? yes
      10:      2  2 EXIT pred oracle_db.a/3-0 (semidet) oracle_db.m:19 (oracle_db.m:9)
mdb> continue
yes.
