       1:      1  1 CALL pred output_term_dep:main/2-0 (det) output_term_dep.m:9
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> context none
Contexts will not be printed.
mdb> break p
 0: + stop  interface pred output_term_dep:p/3-0 (det)
mdb> break q
 1: + stop  interface pred output_term_dep:q/1-0 (det)
mdb> break r
 2: + stop  interface pred output_term_dep:r/2-0 (det)
mdb> break s
 3: + stop  interface pred output_term_dep:s/3-0 (nondet)
mdb> break t
 4: + stop  interface pred output_term_dep:t/2-0 (semidet)
mdb> continue
       3:      3  3 CALL pred output_term_dep:p/3-0 (det)
mdb> finish
      10:      3  3 EXIT pred output_term_dep:p/3-0 (det)
mdb> dd
p(5, 8, 13)
Valid? browse 2
browser> mark
pb(8)
Valid? yes
pa(5)
Valid? yes
pc(13)
Valid? yes
Found incorrect contour:
p(5, 8, 13)
Is this a bug? yes
      10:      3  3 EXIT pred output_term_dep:p/3-0 (det)
mdb> continue
5
8
13
      13:      8  3 CALL pred output_term_dep:q/1-0 (det)
mdb> finish
      20:      8  3 EXIT pred output_term_dep:q/1-0 (det)
mdb> dd
q([[1, 2, 3], [], [99]])
Valid? browse 1
browser> mark 2/1
qb([])
Valid? yes
qa([1, 2, 3])
Valid? yes
qc([99])
Valid? yes
Found incorrect contour:
q([[1, 2, 3], [], [99]])
Is this a bug? yes
      20:      8  3 EXIT pred output_term_dep:q/1-0 (det)
mdb> continue
[[1, 2, 3], [], [99]]
      23:     13  3 CALL pred output_term_dep:r/2-0 (det)
mdb> finish
      26:     13  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> dd
r(1, 999)
Valid? browse 2
browser> mark
Found incorrect contour:
r(1, 999)
Is this a bug? yes
      26:     13  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> continue
999
      27:     14  3 CALL pred output_term_dep:r/2-0 (det)
mdb> finish
      39:     14  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> dd
r(2, 43)
Valid? browse 2
browser> mark
ra(2)
Valid? yes
Call rb(2)
No solutions.
Complete? yes
Found incorrect contour:
r(2, 43)
Is this a bug? yes
      39:     14  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> continue
43
      40:     17  3 CALL pred output_term_dep:r/2-0 (det)
mdb> finish
      54:     17  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> dd
r(3, 57)
Valid? browse 2
browser> mark
rc(57)
Valid? yes
ra(3)
Valid? yes
rb(3)
Valid? yes
Found incorrect contour:
r(3, 57)
Is this a bug? yes
      54:     17  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> continue
57
      55:     21  3 CALL pred output_term_dep:r/2-0 (det)
mdb> finish
      64:     21  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> dd
r(4, -1)
Valid? browse 2
browser> mark
rd(-1)
Valid? yes
Call ra(4)
No solutions.
Complete? yes
Found incorrect contour:
r(4, -1)
Is this a bug? yes
      64:     21  3 EXIT pred output_term_dep:r/2-0 (det)
mdb> continue
-1
      68:     25  3 CALL pred output_term_dep:s/3-0 (nondet)
mdb> finish
      76:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> dd
s(1, 7, 7)
Valid? browse 2
browser> mark
sa(7)
Valid? abort
Diagnosis aborted.
      76:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> continue
      79:     25  3 REDO pred output_term_dep:s/3-0 (nondet)
mdb> finish
      83:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> dd
s(1, 7, 155)
Valid? browse 3
browser> mark
sc(155)
Valid? abort
Diagnosis aborted.
      83:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> continue
      86:     25  3 REDO pred output_term_dep:s/3-0 (nondet)
mdb> finish
      93:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> dd
s(1, 38, 7)
Valid? browse 3
browser> mark
sa(7)
Valid? abort
Diagnosis aborted.
      93:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> continue
      96:     25  3 REDO pred output_term_dep:s/3-0 (nondet)
mdb> finish
     100:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> dd
s(1, 38, 155)
Valid? browse 3
browser> mark
sc(155)
Valid? abort
Diagnosis aborted.
     100:     25  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> continue
     103:     25  3 REDO pred output_term_dep:s/3-0 (nondet)
mdb> finish
     104:     25  3 FAIL pred output_term_dep:s/3-0 (nondet)
mdb> continue
no
     107:     36  3 CALL pred output_term_dep:s/3-0 (nondet)
mdb> finish
     114:     36  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> dd
s(2, 7, 38)
Valid? browse 3
browser> mark
sb(38)
Valid? no
Found incorrect contour:
sb(38)
Is this a bug? yes
     113:     38  4 EXIT pred output_term_dep:sb/1-0 (det)
mdb> continue
     114:     36  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> continue
     117:     36  3 REDO pred output_term_dep:s/3-0 (nondet)
mdb> finish
     123:     36  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> dd
s(2, 38, 155)
Valid? browse 2
browser> mark
Found incorrect contour:
sb(38)
Is this a bug? yes
     120:     40  4 EXIT pred output_term_dep:sb/1-0 (det)
mdb> continue
     123:     36  3 EXIT pred output_term_dep:s/3-0 (nondet)
mdb> continue
     126:     36  3 REDO pred output_term_dep:s/3-0 (nondet)
mdb> continue
     127:     36  3 FAIL pred output_term_dep:s/3-0 (nondet)
mdb> continue
no
     132:     44  3 CALL pred output_term_dep:t/2-0 (semidet)
mdb> finish
     143:     44  3 EXIT pred output_term_dep:t/2-0 (semidet)
mdb> dd
t(1, 77)
Valid? browse 2
browser> mark
tb(77)
Valid? yes
Call ta(1)
No solutions.
Complete? yes
Call tc(77)
No solutions.
Complete? yes
Found incorrect contour:
t(1, 77)
Is this a bug? yes
     143:     44  3 EXIT pred output_term_dep:t/2-0 (semidet)
mdb> continue
77
