      E1:     C1 CALL pred partial.main/2-0 (det) partial.m:11
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> step
      E2:     C2 CALL pred partial.p/1-0 (det)
mdb> finish
      E3:     C2 EXIT pred partial.p/1-0 (det)
mdb> dd
p(t(1, 2))
Valid? browse 1
browser> cd 1
browser> mark
a(1)
Valid? info
Context of current question : partial.m:32 (partial.m:25)
Search mode                 : top down                   
The current question was chosen because the marked subterm was bound by
the unification inside the predicate partial.a/1 (partial.m:32). The
path to the subterm in the atom is 1.
dd> undo
p(t(1, 2))
Valid? browse 1
browser> cd 2
browser> mark
b(2)
Valid? info
Context of current question : partial.m:36 (partial.m:26)
Search mode                 : top down                   
The current question was chosen because the marked subterm was bound by
the unification inside the predicate partial.b/1 (partial.m:36). The
path to the subterm in the atom is 1.
dd> quit
Diagnosis aborted.
      E3:     C2 EXIT pred partial.p/1-0 (det)
mdb> quit -y
