       1:      1  1 CALL pred propositional:main/2-0 (det) propositional.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred propositional:a/0-0 (semidet)
mdb> break b
 1: + stop  interface pred propositional:b/0-0 (semidet)
mdb> continue
       3:      2  2 CALL pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> finish
      11:      2  2 EXIT pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> dd
c
Valid? yes
Found incorrect contour:
a
Is this a bug? yes
      11:      2  2 EXIT pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> continue
      12:      5  2 CALL pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> finish
      22:      5  2 EXIT pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> dd
f
Valid? no
i
Valid? yes
Found incorrect contour:
f
Is this a bug? yes
      21:      6  3 EXIT pred propositional:f/0-0 (semidet) propositional.m:35 (propositional.m:29)
mdb> continue
      22:      5  2 EXIT pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> continue
yes
