      E1:     C1  1 CALL pred propositional:main/2-0 (det) propositional.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred propositional:a/0-0 (semidet)
mdb> break b
 1: + stop  interface pred propositional:b/0-0 (semidet)
mdb> continue
      E2:     C2  2 CALL pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> finish
      E3:     C2  2 EXIT pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> dd
a
Valid? no
c
Valid? yes
Found incorrect contour:
a
Is this a bug? yes
      E3:     C2  2 EXIT pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> continue
      E4:     C3  2 CALL pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> finish
      E5:     C3  2 EXIT pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> dd
b
Valid? no
f
Valid? no
i
Valid? yes
Found incorrect contour:
f
Is this a bug? yes
      E6:     C4  3 EXIT pred propositional:f/0-0 (semidet) propositional.m:35 (propositional.m:29)
mdb> continue
      E5:     C3  2 EXIT pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> continue
yes
