       1:      1  1 CALL pred propositional:main/2-0 (det) propositional.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred propositional:a/0-0 (semidet)
mdb> break b
 1: + stop  interface pred propositional:b/0-0 (semidet)
mdb> continue
       3:      2  2 CALL pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> finish
      11:      2  2 EXIT pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> dd
atom("a", [])
Valid? no
atom("c", [])
Valid? yes
Incorrect node found:
wrong_answer(atom("a", []))
      11:      2  2 EXIT pred propositional:a/0-0 (semidet) propositional.m:27 (propositional.m:10)
mdb> continue
      12:      5  2 CALL pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> finish
      22:      5  2 EXIT pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> dd
atom("b", [])
Valid? no
atom("f", [])
Valid? no
atom("i", [])
Valid? yes
Incorrect node found:
wrong_answer(atom("f", []))
      22:      5  2 EXIT pred propositional:b/0-0 (semidet) propositional.m:29 (propositional.m:10)
mdb> continue
yes
