       1:      1  1 CALL pred queens:main/2-0 (cc_multi) queens.m:17
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> dd
mdb: declarative debugging is only available from EXIT, FAIL or EXCP events.
mdb> break queen
 0: + stop  interface pred queens:queen/2-0 (nondet)
mdb> continue
       5:      3  2 CALL pred queens:queen/2-0 (nondet) queens.m:41 (queens.m:15)
mdb> finish
     161:      3  2 FAIL pred queens:queen/2-0 (nondet) queens.m:41 (queens.m:15)
mdb> dd
Call queen([1, 2, 3, 4, 5], _)
No solutions.
Complete? no
Call qperm([1, 2, 3, 4, 5], _)
No solutions.
Complete? no
pred qdelete
	1
	[1, 2, 3, 4, 5]
	[2, 3, 4, 5]
Valid? yes
pred qdelete
	2
	[1, 2, 3, 4, 5]
	[1, 3, 4, 5]
Valid? yes
Call qperm([1, 3, 4, 5], _)
No solutions.
Complete? no
qdelete(1, [1, 3, 4, 5], [3, 4, 5])
Valid? yes
qdelete(3, [1, 3, 4, 5], [1, 4, 5])
Valid? yes
Call qperm([1, 4, 5], _)
No solutions.
Complete? no
qdelete(1, [1, 4, 5], [4, 5])
Valid? yes
qdelete(4, [1, 4, 5], [1, 5])
Valid? yes
Call qperm([1, 5], _)
No solutions.
Complete? no
qdelete(1, [1, 5], [5])
Valid? yes
qdelete(5, [1, 5], [1])
Valid? yes
Call qperm([1], _)
No solutions.
Complete? no
qdelete(1, [1], [])
Valid? yes
Call qdelete(_, [1], _)
Solutions:
	qdelete(1, [1], [])
Complete? yes
Found partially uncovered atom:
qperm([1], _)
Is this a bug? yes
      60:     16  7 FAIL pred queens:qperm/2-0 (nondet) queens.m:45 (queens.m:49)
mdb> continue
     161:      3  2 FAIL pred queens:queen/2-0 (nondet) queens.m:41 (queens.m:15)
mdb> continue
No solution
