       1:      1  1 CALL pred solutions.main/2-0 (det) solutions.m:8
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred solutions.p/2-0 (det)
mdb> continue
       2:      2  2 CALL pred solutions.p/2-0 (det) solutions.m:15 (solutions.m:9)
mdb> finish
      15:      2  2 EXIT pred solutions.p/2-0 (det) solutions.m:15 (solutions.m:9)
mdb> dd
p(1, [1, 2, 3])
Valid? no
q(1, 1)
Valid? yes
q(1, 2)
Valid? yes
q(1, 3)
Valid? yes
Call q(1, _)
Solutions:
	q(1, 1)
	q(1, 2)
	q(1, 3)
Complete? yes
Found incorrect contour:
p(1, [1, 2, 3])
Is this a bug? yes
      15:      2  2 EXIT pred solutions.p/2-0 (det) solutions.m:15 (solutions.m:9)
mdb> quit -y
