      E1:     C1 CALL pred sort.main/2-0 (det) sort.m:27
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> table_io start
I/O tabling started.
mdb> finish
ian
ian
ian
ian
      E2:     C1 EXIT pred sort.main/2-0 (det) sort.m:27
mdb> set format flat
mdb> set size 1
mdb> dd
main(_, _)
16 io actions:
command_line_arguments(["sort.input"])
do_open_text("sort.input", "r", 0, 0, stream(0, input, text, file("sort.input")))
get_stream_db(four/10)
set_stream_db(two/4)
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "ian\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "zoltan\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "rafe\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "julien\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, -1, "")
write_string("ian\n")
write_string("")
write_string("ian\n")
write_string("")
write_string("ian\n")
write_string("")
write_string("ian\n")
Valid? print io 9
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, -1, "")
main(_, _)
16 io actions:
command_line_arguments(["sort.input"])
do_open_text("sort.input", "r", 0, 0, stream(0, input, text, file("sort.input")))
get_stream_db(four/10)
set_stream_db(two/4)
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "ian\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "zoltan\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "rafe\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "julien\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, -1, "")
write_string("ian\n")
write_string("")
write_string("ian\n")
write_string("")
write_string("ian\n")
write_string("")
write_string("ian\n")
Valid? no
open_stream(["sort.input"], ok(stream(0, input, text, file("sort.input"))), _, _)
3 io actions:
do_open_text("sort.input", "r", 0, 0, stream(0, input, text, file("sort.input")))
get_stream_db(four/10)
set_stream_db(two/4)
Valid? yes
read_lines(stream/4, [|]/2, _, _)
5 io actions:
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "ian\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "zoltan\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "rafe\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, 0, "julien\n")
read_line_as_string_2(stream(0, input, text, file("sort.input")), yes, -1, "")
Valid? a
Diagnosis aborted.
      E2:     C1 EXIT pred sort.main/2-0 (det) sort.m:27
mdb> quit -y
