      E1:     C1  1 CALL pred special_term_dep.main/2-0 (det) special_term_dep.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred special_term_dep.p/1-0 (det)
mdb> break q
 1: + stop  interface pred special_term_dep.q/2-0 (semidet)
mdb> continue
      E2:     C2  3 CALL pred special_term_dep.p/1-0 (det) special_term_dep.m:29 (special_term_dep.m:22)
mdb> finish
      E3:     C2  3 EXIT pred special_term_dep.p/1-0 (det) special_term_dep.m:29 (special_term_dep.m:22)
mdb> dd
p([2, 3])
Valid? browse 1
browser> mark
pa([2, 3])
Valid? yes
Found incorrect contour:
p([2, 3])
Is this a bug? yes
      E3:     C2  3 EXIT pred special_term_dep.p/1-0 (det) special_term_dep.m:29 (special_term_dep.m:22)
mdb> continue
[2, 3]
      E4:     C3  3 CALL pred special_term_dep.q/2-0 (semidet) special_term_dep.m:61 (special_term_dep.m:50)
mdb> finish
      E5:     C3  3 EXIT pred special_term_dep.q/2-0 (semidet) special_term_dep.m:61 (special_term_dep.m:50)
mdb> dd
q([1, 2], [3])
Valid? browse 2
browser> mark
qb([1, 2], [3])
Valid? browse 1
browser> mark
qa([1, 2])
Valid? yes
Found incorrect contour:
q([1, 2], [3])
Is this a bug? yes
      E5:     C3  3 EXIT pred special_term_dep.q/2-0 (semidet) special_term_dep.m:61 (special_term_dep.m:50)
mdb> continue
[3]
