      E1:     C1 CALL pred tabled_read_decl.main/2-0 (det) tabled_read_decl.m:17
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> context none
Contexts will not be printed.
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> break tabled_read_decl__test
 0: + stop  interface pred tabled_read_decl.test/4-0 (det)
mdb> continue
      E2:     C2 CALL pred tabled_read_decl.test/4-0 (det)
mdb> finish -n
      E3:     C2 EXIT pred tabled_read_decl.test/4-0 (det)
mdb> print
test('<<c_pointer>>', 1123, _, _)
mdb> dd -a
test('<<c_pointer>>', 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Valid? print 1-2
'<<c_pointer>>'
1123
test('<<c_pointer>>', 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Valid? p io 1-2
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
test('<<c_pointer>>', 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Valid? print io 2-1
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
test('<<c_pointer>>', 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Valid? browse io 4
browser> print
read_char_code('<<c_pointer>>', 10)
browser> set num_io_actions 3
browser> quit
test('<<c_pointer>>', 1123, _, _)
4 io actions: too many to show
Valid? browse 1
browser> set num_io_actions 10
browser> quit
test('<<c_pointer>>', 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Valid? no
test_2('<<c_pointer>>', 1, 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Valid? yes
Found incorrect contour:
test_2('<<c_pointer>>', 1, 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
test('<<c_pointer>>', 1123, _, _)
4 io actions:
read_char_code('<<c_pointer>>', 49)
read_char_code('<<c_pointer>>', 50)
read_char_code('<<c_pointer>>', 51)
read_char_code('<<c_pointer>>', 10)
Is this a bug? yes
      E3:     C2 EXIT pred tabled_read_decl.test/4-0 (det)
mdb> c -n -S
1123
1456
1789
