       1:      1  1 CALL pred unsafe_cast.main/2-0 (det) unsafe_cast.m:11
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> 
       2:      2  2 CALL pred unsafe_cast.p/1-0 (det)
mdb> f
       3:      2  2 EXIT pred unsafe_cast.p/1-0 (det)
mdb> dd
p(42)
Valid? b 1
browser> mark
Found incorrect contour:
p(42)
Is this a bug? yes
       3:      2  2 EXIT pred unsafe_cast.p/1-0 (det)
mdb> c
42
