      E1:     C1 CALL pred args.main/2-0 (cc_multi) args.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred args.p/5-0 (nondet)
mdb> continue
      E2:     C2 CALL pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> finish
      E3:     C2 EXIT pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> dd -d 3 -n 7
p(1, 16, 3, 20, 5)
Valid? no
+(1, 3) = 4
Valid? yes
*(3, 5) = 15
Valid? yes
+(1, 15) = 16
Valid? yes
*(4, 5) = 20
Valid? yes
semidet_succeed
Valid? yes
Found incorrect contour:
+(1, 3) = 4
*(3, 5) = 15
+(1, 15) = 16
*(4, 5) = 20
semidet_succeed
p(1, 16, 3, 20, 5)
Is this a bug? yes
      E3:     C2 EXIT pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> continue
      E4:     C2 REDO pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> finish
      E5:     C2 EXIT pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> dd -d 3 -n 7
p(1, -2, 3, 2, 5)
Valid? no
-(1, 3) = -2
Valid? yes
-(5, 3) = 2
Valid? yes
Found incorrect contour:
-(1, 3) = -2
-(5, 3) = 2
semidet_succeed
p(1, -2, 3, 2, 5)
Is this a bug? yes
      E5:     C2 EXIT pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> continue
      E6:     C2 REDO pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> finish
      E7:     C2 FAIL pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> dd -d 3 -n 7
Call p(1, _, 3, _, 5)
Solutions:
	p(1, 16, 3, 20, 5)
	p(1, -2, 3, 2, 5)
Complete? no
Found partially uncovered atom:
p(1, _, 3, _, 5)
Is this a bug? yes
      E7:     C2 FAIL pred args.p/5-0 (nondet) args.m:29 (args.m:16)
mdb> continue
no.
