       1:      1  1 CALL pred comp_gen.main/2-0 (det) comp_gen.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred comp_gen.p/2-0 (semidet)
mdb> continue
       5:      3  2 CALL pred comp_gen.p/2-0 (semidet) comp_gen.m:30 (comp_gen.m:15)
mdb> step
       6:      4  3 CALL __Unify__ for comp_gen.foo/1-0 (semidet) comp_gen.m:21 (comp_gen.m:30)
mdb> finish
       7:      4  3 FAIL __Unify__ for comp_gen.foo/1-0 (semidet) comp_gen.m:21 (comp_gen.m:30)
mdb> dd -d 3 -n 7
mdb: cannot start declarative debugging at compiler generated procedures.
mdb> continue
       8:      3  2 FAIL pred comp_gen.p/2-0 (semidet) comp_gen.m:30 (comp_gen.m:15)
mdb> dd -d 3 -n 7
Call p(f(1), f(2))
Unsatisfiable? no
Found partially uncovered atom:
p(f(1), f(2))
Is this a bug? yes
       8:      3  2 FAIL pred comp_gen.p/2-0 (semidet) comp_gen.m:30 (comp_gen.m:15)
mdb> continue
no
