      E1:     C1 CALL pred condition_bug.main/2-0 (det) condition_bug.m:23
mdb> mdb> echo on
Command echo enabled.
mdb> untrust 0
mdb> table_io start
I/O tabling started.
mdb> break stream.put/4
 0: + stop  interface pred stream.put/4-0 (det)
mdb> condition 2 = "english"
 0: + stop  interface pred stream.put/4-0 (det)
            2 = "english"
mdb> continue
<?xml version="1.0"?>
<translations>
	<word>
		<      E2:     C2 CALL pred stream.put/4-0 (det) stream.m:NNNN (term_to_xml.m:NNNN)
mdb> finish
english      E3:     C2 EXIT pred stream.put/4-0 (det) stream.m:NNNN (term_to_xml.m:NNNN)
mdb> dd
put(stream(1, output, preopen, stdout), "english", _, <<foreign(state, 0xXXXX)>>)
1 tabled IO action:
do_write_string(<<foreign(stream, 0xXXXX)>>, "english", <<foreign(system_error, 0xXXXX)>>)
Valid? browse 2
browser> track
>critical</english>
		<dutch>kritiek</dutch>
	</word>
	<word>
		<english>mission</english>
		<dutch>missie</dutch>
	</word>
</translations>

translation_pairs_to_xml([-("critical", "kritiek"), -("mission", "missie")]) = [elem("word", [], [|]/2), elem("word", [], [|]/2)]
Valid? info
Context of current question : condition_bug.m:48 (condition_bug.m:44)
Search mode                 : top down                               
The current question was chosen because the marked subterm was bound by
the unification inside the function
condition_bug.translation_pairs_to_xml/2 (condition_bug.m:51). The path
to the subterm in the atom is 2/1/3/1/1.
dd> quit
Diagnosis aborted.
      E3:     C2 EXIT pred stream.put/4-0 (det) stream.m:NNNN (term_to_xml.m:NNNN)
mdb> quit -y
