      E1:     C1 CALL pred explicit_subtree.main/2-0 (det) explicit_subtree.m:15
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> break divide2
 0: + stop  interface pred explicit_subtree.divide2/3-0 (det)
mdb> continue
      E2:     C2 CALL pred explicit_subtree.divide2/3-0 (det)
mdb> finish
      E3:     C2 EXCP pred explicit_subtree.divide2/3-0 (det) t;c3;
mdb> dd -d 3 -n 7 -ad3
Call divide2(10, 0, _)
Throws "zero denominator"
Expected? browse 2
browser> mark
a(0)
Valid? n
q(49, 0, 49)
Valid? y
q(51, 0, 51)
Valid? b 3
browser> mark
q(1, 50, 51)
Valid? n
q(0, 51, 51)
Valid? y
Found incorrect contour:
q(0, 51, 51)
q(1, 50, 51)
Is this a bug? n
q(1, 50, 51)
Valid? [no] y
q(50, 1, 51)
Valid? y
Found incorrect contour:
q(50, 1, 51)
q(51, 0, 51)
Is this a bug? n
q(51, 0, 51)
Valid? y
Found incorrect contour:
q(49, 0, 49)
q(51, 0, 51)
a(0)
Is this a bug? n
a(0)
Valid? [no] 
q(49, 0, 49)
Valid? [yes] b 3
browser> mark
q(1, 48, 49)
Valid? n
q(0, 49, 49)
Valid? n
Found incorrect contour:
q(0, 49, 49)
Is this a bug? n
q(0, 49, 49)
Valid? [no] y
Found incorrect contour:
q(0, 49, 49)
q(1, 48, 49)
Is this a bug? n
q(1, 48, 49)
Valid? [no] y
q(48, 1, 49)
Valid? y
Found incorrect contour:
q(48, 1, 49)
q(49, 0, 49)
Is this a bug? n
q(49, 0, 49)
Valid? y
q(51, 0, 51)
Valid? [yes] 
Found incorrect contour:
q(49, 0, 49)
q(51, 0, 51)
a(0)
Is this a bug? n
a(0)
Valid? [no] y
Call calc(10, _)
Throws "zero denominator"
Expected? y
Call p3(10, _)
Throws "zero denominator"
Expected? y
Call p2(10, _)
Throws "zero denominator"
Expected? b 1
browser> mark
Call main(_, _)
Throws "zero denominator"
Expected? y
No bug found.
      E3:     C2 EXCP pred explicit_subtree.divide2/3-0 (det) t;c3;
mdb> quit -y
