      E1:     C1 CALL pred find_origin.main/2-0 (det) find_origin.m:29
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> 
      E2:     C2 CALL pred find_origin.monotest/2-0 (det)
mdb> f
      E3:     C2 EXIT pred find_origin.monotest/2-0 (det)
mdb> dd -d 3 -n 7
monotest(t(101), 1)
Valid? b 1
browser> mark
monotest4(t(101), t(101))
Valid? n
Call lambda_find_origin_m_84(t(101), t(1))
Unsatisfiable? y
Call lambda_find_origin_m_84(t(101), t(2))
Unsatisfiable? y
lambda_find_origin_m_84(t(101), t(101))
Valid? y
Call lambda_find_origin_m_84(t(101), t(3))
Unsatisfiable? y
Found incorrect contour:
lambda_find_origin_m_84(t(101), t(101))
monotest4(t(101), t(101))
Is this a bug? y
      E4:     C3 EXIT pred find_origin.monotest4/2-0 (det)
mdb> break polytest
 0: + stop  interface pred find_origin.polytest/3-0 (det)
mdb> c
      E5:     C4 CALL pred find_origin.polytest/3-0 (det)
mdb> f
      E6:     C4 EXIT pred find_origin.polytest/3-0 (det)
mdb> dd -d 3 -n 7
polytest("hello", u("hello"), 5)
Valid? b 2
browser> mark
polytest4(u("hello"), u("hello"))
Valid? browse
browser> format pretty
browser> p
find_origin.polytest4(u("hello"), u("hello"))
browser> quit
dd> no
Call lambda_find_origin_m_142(u(string), u(u("hello")), v(u("hello")))
Unsatisfiable? y
lambda_find_origin_m_142(u(string), u(u("hello")), u(u("hello")))
Valid? y
Found incorrect contour:
lambda_find_origin_m_142(u(string), u(u("hello")), u(u("hello")))
polytest4(u("hello"), u("hello"))
Is this a bug? y
      E7:     C5 EXIT pred find_origin.polytest4/2-0 (det)
mdb> delete 0
 0: E stop  interface pred find_origin.polytest/3-0 (det)
mdb> break tracetest
 0: + stop  interface pred find_origin.tracetest/2-0 (det)
mdb> c
      E8:     C6 CALL pred find_origin.tracetest/2-0 (det)
mdb> f
      E9:     C6 EXIT pred find_origin.tracetest/2-0 (det)
mdb> dd -d 3 -n 7
tracetest(t(101), -2)
Valid? b 1
browser> mark
tracetest1(t(101))
Valid? n
Found incorrect contour:
tracetest1(t(101))
Is this a bug? y
     E10:     C7 EXIT pred find_origin.tracetest1/1-0 (det)
mdb> quit -y
