       1:      1  1 CALL pred func_call.main/2-0 (det) func_call.m:15
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break fib
 0: + stop  interface func func_call.fib/1-0 (det)
mdb> continue
       2:      2  2 CALL func func_call.fib/1-0 (det) func_call.m:21 (func_call.m:16)
mdb> finish -n
     151:      2  2 EXIT func func_call.fib/1-0 (det) func_call.m:21 (func_call.m:16)
mdb> dd -d 3 -n 7
fib(6) = 9
Valid? no
Call =<(6, 1)
Unsatisfiable? yes
-(6, 1) = 5
Valid? yes
fib(5) = 6
Valid? no
Call =<(5, 1)
Unsatisfiable? yes
-(5, 1) = 4
Valid? yes
fib(4) = 4
Valid? no
Call =<(4, 1)
Unsatisfiable? yes
-(4, 1) = 3
Valid? yes
fib(3) = 3
Valid? yes
-(4, 3) = 1
Valid? yes
fib(1) = 1
Valid? yes
+(3, 1) = 4
Valid? yes
Found incorrect contour:
-(4, 1) = 3
fib(3) = 3
-(4, 3) = 1
fib(1) = 1
+(3, 1) = 4
fib(4) = 4
Is this a bug? yes
      75:      8  4 EXIT func func_call.fib/1-0 (det) func_call.m:21 (func_call.m:25)
mdb> quit -y
