       1:      1  1 CALL pred gcf.main/2-0 (cc_multi) gcf.m:16
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred gcf.a/1-0 (nondet)
mdb> continue
       3:      2  2 CALL pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> finish
      23:      2  2 EXIT pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> dd -d 3 -n 7
a(11)
Valid? no
g(2)
Valid? yes
c(2, 11)
Valid? yes
f(11)
Valid? yes
Found incorrect contour:
g(2)
c(2, 11)
f(11)
a(11)
Is this a bug? yes
      23:      2  2 EXIT pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> continue
      24:      2  2 REDO pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> finish
      30:      2  2 EXIT pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> dd -d 3 -n 7
a(12)
Valid? no
c(2, 12)
Valid? yes
f(12)
Valid? yes
Found incorrect contour:
g(2)
c(2, 12)
f(12)
a(12)
Is this a bug? yes
      30:      2  2 EXIT pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> continue
      31:      2  2 REDO pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> finish
      42:      2  2 EXIT pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> dd -d 3 -n 7
a(20)
Valid? no
g(3)
Valid? yes
c(3, 20)
Valid? yes
f(20)
Valid? yes
Found incorrect contour:
g(3)
c(3, 20)
f(20)
a(20)
Is this a bug? yes
      42:      2  2 EXIT pred gcf.a/1-0 (nondet) gcf.m:29 (gcf.m:18)
mdb> continue
yes(20)
