       1:      1  1 CALL pred higher_order.main/2-0 (det) higher_order.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred higher_order.p/2-0 (det)
mdb> continue
       2:      2  2 CALL pred higher_order.p/2-0 (det) higher_order.m:21 (higher_order.m:15)
mdb> finish
       7:      2  2 EXIT pred higher_order.p/2-0 (det) higher_order.m:21 (higher_order.m:15)
mdb> dd -d 3 -n 7
p(3, 81)
Valid? no
q(lambda_higher_order_m_22, 3, 81)
Valid? yes
Found incorrect contour:
q(lambda_higher_order_m_22, 3, 81)
p(3, 81)
Is this a bug? yes
       7:      2  2 EXIT pred higher_order.p/2-0 (det) higher_order.m:21 (higher_order.m:15)
mdb> continue
81
