       1:      1  1 CALL pred ho2.main/2-0 (det) ho2.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred ho2.p/3-0 (det)
mdb> continue
       2:      2  2 CALL pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:15)
mdb> finish
       7:      2  2 EXIT pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:15)
mdb> dd -d 3 -n 7
p(0, 3, 27)
Valid? no
q(lambda_ho2_m_28(3), 3, 27)
Valid? yes
Found incorrect contour:
q(lambda_ho2_m_28(3), 3, 27)
p(0, 3, 27)
Is this a bug? yes
       7:      2  2 EXIT pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:15)
mdb> continue
       8:      5  2 CALL pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:16)
mdb> finish
      13:      5  2 EXIT pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:16)
mdb> dd -d 3 -n 7
p(1, 3, 27)
Valid? no
Found incorrect contour:
q(lambda_ho2_m_28(3), 3, 27)
p(1, 3, 27)
Is this a bug? yes
      13:      5  2 EXIT pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:16)
mdb> continue
      14:      8  2 CALL pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:17)
mdb> finish
      19:      8  2 EXIT pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:17)
mdb> dd -d 3 -n 7
p(2, 4, 64)
Valid? no
q(lambda_ho2_m_28(4), 4, 64)
Valid? yes
Found incorrect contour:
q(lambda_ho2_m_28(4), 4, 64)
p(2, 4, 64)
Is this a bug? yes
      19:      8  2 EXIT pred ho2.p/3-0 (det) ho2.m:27 (ho2.m:17)
mdb> continue
27, 27, 64
