       1:      1  1 CALL pred ho_3.main/2-0 (det) ho_3.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred ho_3.p/1-0 (semidet)
mdb> continue
       3:      2  2 CALL pred ho_3.p/1-0 (semidet) ho_3.m:29 (ho_3.m:15)
mdb> finish
      16:      2  2 FAIL pred ho_3.p/1-0 (semidet) ho_3.m:29 (ho_3.m:15)
mdb> dd -d 3 -n 7
Call p(1)
Unsatisfiable? no
q(0, x(0))
Valid? yes
Call x(0, 1)
Unsatisfiable? yes
q(0, y(0))
Valid? yes
Call y(0, 1)
Unsatisfiable? yes
Call q(0, _)
Solutions:
	q(0, x(0))
	q(0, y(0))
Complete? yes
Found partially uncovered atom:
p(1)
Is this a bug? yes
      16:      2  2 FAIL pred ho_3.p/1-0 (semidet) ho_3.m:29 (ho_3.m:15)
mdb> continue
      19:      6  2 CALL pred ho_3.p/1-0 (semidet) ho_3.m:29 (ho_3.m:20)
mdb> finish
      32:      6  2 FAIL pred ho_3.p/1-0 (semidet) ho_3.m:29 (ho_3.m:20)
mdb> dd -d 3 -n 7
Call p(2)
Unsatisfiable? no
Call x(0, 2)
Unsatisfiable? yes
Call y(0, 2)
Unsatisfiable? yes
Found partially uncovered atom:
p(2)
Is this a bug? yes
      32:      6  2 FAIL pred ho_3.p/1-0 (semidet) ho_3.m:29 (ho_3.m:20)
mdb> continue
\+ p(1).
\+ p(2).
