       1:      1  1 CALL pred ho_4.main/2-0 (det) ho_4.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred ho_4.p/1-0 (semidet)
mdb> continue
       3:      2  2 CALL pred ho_4.p/1-0 (semidet) ho_4.m:29 (ho_4.m:15)
mdb> finish
      18:      2  2 FAIL pred ho_4.p/1-0 (semidet) ho_4.m:29 (ho_4.m:15)
mdb> dd -d 3 -n 7
Call p(1)
Unsatisfiable? no
q(r(5), 5)
Valid? yes
q(r(5), 0)
Valid? yes
Call q(r(5), _)
Solutions:
	q(r(5), 5)
	q(r(5), 0)
Complete? yes
Found partially uncovered atom:
p(1)
Is this a bug? yes
      18:      2  2 FAIL pred ho_4.p/1-0 (semidet) ho_4.m:29 (ho_4.m:15)
mdb> continue
      21:      5  2 CALL pred ho_4.p/1-0 (semidet) ho_4.m:29 (ho_4.m:20)
mdb> finish
      36:      5  2 FAIL pred ho_4.p/1-0 (semidet) ho_4.m:29 (ho_4.m:20)
mdb> dd -d 3 -n 7
Call p(2)
Unsatisfiable? no
Found partially uncovered atom:
p(2)
Is this a bug? yes
      36:      5  2 FAIL pred ho_4.p/1-0 (semidet) ho_4.m:29 (ho_4.m:20)
mdb> continue
\+ p(1).
\+ p(2).
