      E1:     C1 CALL pred nodescend_tracking.main/2-0 (det) nodescend_tracking.m:31
mdb> mdb> echo on
Command echo enabled.
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> break run_test
 0: + stop  interface pred nodescend_tracking.run_test/3-0 (det)
mdb> continue
      E2:     C2 CALL pred nodescend_tracking.run_test/3-0 (det) nodescend_tracking.m:38 (nodescend_tracking.m:32)
mdb> delete *
 0: E stop  interface pred nodescend_tracking.run_test/3-0 (det)
mdb> finish

*** called untabled_print ***
      E3:     C2 EXIT pred nodescend_tracking.run_test/3-0 (det) nodescend_tracking.m:38 (nodescend_tracking.m:32)
mdb> dd -d 1 -n 1000 -a

*** called untabled_print ***
run_test([reverse(2, 1), reverse(2, 1), reverse(2, 1), reverse(2, 1), reverse(2, 1), reverse(2, 1), reverse(2, 1), reverse(2, 1), ...], _, _)
Valid? browse 1
browser> cdr 9999 2
browser> cd 1
browser> ls
leave(1, 2)
browser> track
make_test_list(1) = [leave(1, 2)]
Valid? info
Context of current question : nodescend_tracking.m:65 (nodescend_tracking.m:69)
Search mode                 : top down                                         
The current question was chosen because the marked subterm was bound by
the unification inside the function nodescend_tracking.make_test_list/2
(nodescend_tracking.m:67). The path to the subterm in the atom is 2/1.
dd> quit
Diagnosis aborted.

*** called untabled_print ***
      E3:     C2 EXIT pred nodescend_tracking.run_test/3-0 (det) nodescend_tracking.m:38 (nodescend_tracking.m:32)
mdb> quit -y
