      E1:     C1 CALL pred priv_builtin_bug.main/2-0 (det) priv_builtin_bug.m:13
mdb> mdb> I/O tabling started.
mdb> echo on
Command echo enabled.
mdb> break p
 0: + stop  interface pred priv_builtin_bug.p/2-0 (det)
mdb> c
      E2:     C2 CALL pred priv_builtin_bug.p/2-0 (det) priv_builtin_bug.m:32 (priv_builtin_bug.m:25)
mdb> f
      E3:     C2 EXIT pred priv_builtin_bug.p/2-0 (det) priv_builtin_bug.m:32 (priv_builtin_bug.m:25)
mdb> dd
p(2, 2)
Valid? b 1
browser> mark
2
q(1, 2)
Valid? n
Found inadmissible call:
Parent q(1, _)
Call p(2, _)
Is this a bug? y
      E4:     C3 EXIT pred priv_builtin_bug.q/2-0 (det) priv_builtin_bug.m:20 (priv_builtin_bug.m:14)
mdb> quit -y
