      E1:     C1 CALL pred propositional.main/2-0 (det) propositional.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred propositional.a/0-0 (semidet)
mdb> break b
 1: + stop  interface pred propositional.b/0-0 (semidet)
mdb> continue
      E2:     C2 CALL pred propositional.a/0-0 (semidet) propositional.m:31 (propositional.m:15)
mdb> finish
      E3:     C2 EXIT pred propositional.a/0-0 (semidet) propositional.m:31 (propositional.m:15)
mdb> dd -d 3 -n 7
a
Valid? no
c
Valid? yes
Found incorrect contour:
c
a
Is this a bug? yes
      E3:     C2 EXIT pred propositional.a/0-0 (semidet) propositional.m:31 (propositional.m:15)
mdb> continue
      E4:     C3 CALL pred propositional.b/0-0 (semidet) propositional.m:33 (propositional.m:15)
mdb> finish
      E5:     C3 EXIT pred propositional.b/0-0 (semidet) propositional.m:33 (propositional.m:15)
mdb> dd -d 3 -n 7
b
Valid? no
f
Valid? no
i
Valid? yes
Found incorrect contour:
i
f
Is this a bug? yes
      E6:     C4 EXIT pred propositional.f/0-0 (semidet) propositional.m:39 (propositional.m:33)
mdb> continue
      E5:     C3 EXIT pred propositional.b/0-0 (semidet) propositional.m:33 (propositional.m:15)
mdb> continue
yes
