       1:      1  1 CALL pred queens.main/2-0 (cc_multi) queens.m:18
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> dd -d 3 -n 7
mdb: declarative debugging is only available from EXIT, FAIL or EXCP events.
mdb> break queen
 0: + stop  interface pred queens.queen/2-0 (nondet)
mdb> continue
       5:      3  2 CALL pred queens.queen/2-0 (nondet) queens.m:32 (queens.m:20)
mdb> finish
     161:      3  2 FAIL pred queens.queen/2-0 (nondet) queens.m:32 (queens.m:20)
mdb> dd -d 3 -n 7
Call queen([1, 2, 3, 4, 5], _)
Unsatisfiable? no
Call qperm([1, 2, 3, 4, 5], _)
Unsatisfiable? no
qdelete(1, [1, 2, 3, 4, 5], [2, ...])
Valid? yes
qdelete(2, [1, 2, 3, 4, 5], [1, ...])
Valid? yes
Call qperm([1, 3, 4, 5], _)
Unsatisfiable? no
qdelete(1, [1, 3, 4, 5], [3, 4, ...])
Valid? yes
qdelete(3, [1, 3, 4, 5], [1, 4, ...])
Valid? yes
Call qperm([1, 4, 5], _)
Unsatisfiable? no
qdelete(1, [1, 4, 5], [4, 5])
Valid? yes
qdelete(4, [1, 4, 5], [1, 5])
Valid? yes
Call qperm([1, 5], _)
Unsatisfiable? no
qdelete(1, [1, 5], [5])
Valid? yes
qdelete(5, [1, 5], [1])
Valid? yes
Call qperm([1], _)
Unsatisfiable? no
qdelete(1, [1], [])
Valid? yes
Call qdelete(_, [1], _)
Solutions:
	qdelete(1, [1], [])
Complete? yes
Found partially uncovered atom:
qperm([1], _)
Is this a bug? yes
      60:     16  7 FAIL pred queens.qperm/2-0 (nondet) queens.m:38 (queens.m:42)
mdb> continue
     161:      3  2 FAIL pred queens.queen/2-0 (nondet) queens.m:32 (queens.m:20)
mdb> continue
No solution
