       1:      1  1 CALL pred shallow.main/2-0 (det) shallow.m:14
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break shallow__test
 0: + stop  interface pred shallow.test/2-0 (det)
mdb> continue
       2:      2  2 CALL pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:15)
mdb> finish
      15:      2  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:15)
mdb> dd -d 3 -n 7
test(p("t1", 5), 1)
Valid? no
p("t1", 5, 1)
Valid? no
a("t1", 1, 1)
Valid? yes
a("t1", 1, 0)
Valid? yes
Call a("t1", 1, _)
Solutions:
	a("t1", 1, 1)
	a("t1", 1, 0)
Complete? yes
b("t1", 1, 5)
Valid? yes
Found incorrect contour:
b("t1", 1, 5)
p("t1", 5, 1)
Is this a bug? yes
      14:      3  3 EXIT pred shallow_2.p/3-0 (det) shallow_2.m:15 (shallow.m:34)
mdb> continue
      15:      2  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:15)
mdb> continue
      16:      6  2 CALL pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:16)
mdb> finish
      29:      6  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:16)
mdb> dd -d 3 -n 7
test(p("t2", 37), -11)
Valid? no
p("t2", 37, -11)
Valid? no
a("t2", 1, 1)
Valid? yes
a("t2", 1, 0)
Valid? yes
Call a("t2", 1, _)
Solutions:
	a("t2", 1, 1)
	a("t2", 1, 0)
Complete? yes
b("t2", 1, 5)
Valid? yes
Found incorrect contour:
b("t2", 1, 5)
p("t2", 37, -11)
Is this a bug? yes
      28:      7  3 EXIT pred shallow_2.p/3-0 (det) shallow_2.m:15 (shallow.m:34)
mdb> continue
      29:      6  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:16)
mdb> continue
      30:     10  2 CALL pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:17)
mdb> finish
      41:     10  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:17)
mdb> dd -d 3 -n 7
test(q("t3", 2), 2)
Valid? no
q("t3", 2, 2)
Valid? no
a("t3", 2, 2)
Valid? yes
a("t3", 2, 0)
Valid? yes
Call a("t3", 2, _)
Solutions:
	a("t3", 2, 2)
	a("t3", 2, 0)
Complete? yes
Found incorrect contour:
q("t3", 2, 2)
Is this a bug? yes
      40:     11  3 EXIT pred shallow_2.q/3-0 (det) shallow_2.m:29 (shallow.m:34)
mdb> continue
      41:     10  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:17)
mdb> continue
      42:     13  2 CALL pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:18)
mdb> finish
      48:     13  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:18)
mdb> dd -d 3 -n 7
test(q("t4", -1), 11)
Valid? no
q("t4", -1, 11)
Valid? no
a("t4", -1, -1)
Valid? yes
Found incorrect contour:
a("t4", -1, -1)
q("t4", -1, 11)
Is this a bug? yes
      47:     14  3 EXIT pred shallow_2.q/3-0 (det) shallow_2.m:29 (shallow.m:34)
mdb> continue
      48:     13  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:18)
mdb> continue
      49:     16  2 CALL pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:19)
mdb> finish
      62:     16  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:19)
mdb> dd -d 3 -n 7
test(r("t5", 3), 23)
Valid? no
r("t5", 3, 23)
Valid? no
a("t5", 3, 3)
Valid? yes
a("t5", 3, 0)
Valid? yes
Call a("t5", 3, _)
Solutions:
	a("t5", 3, 3)
	a("t5", 3, 0)
Complete? yes
b("t5", 3, 5)
Valid? yes
Found incorrect contour:
b("t5", 3, 5)
r("t5", 3, 23)
Is this a bug? yes
      61:     17  3 EXIT pred shallow_2.r/3-0 (det) shallow_2.m:36 (shallow.m:34)
mdb> continue
      62:     16  2 EXIT pred shallow.test/2-0 (det) shallow.m:33 (shallow.m:19)
mdb> continue
1
-11
2
11
23
