      E1:     C1 CALL pred sort.main/2-0 (det) sort.m:28
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> table_io start
I/O tabling started.
mdb> max_io_actions 30
mdb> finish
ian
ian
ian
ian
      E2:     C1 EXIT pred sort.main/2-0 (det) sort.m:28
mdb> format pretty
mdb> format_param depth 1
mdb> dd
main(...)
25 tabled IO actions:
command_line_arguments(...)
do_open_text(...)
lock_stream_db
get_stream_db(...)
set_stream_db(...)
unlock_stream_db
read_line_as_string_2(...)
read_line_as_string_2(...)
read_line_as_string_2(...)
read_line_as_string_2(...)
read_line_as_string_2(...)
output_stream_2(...)
do_write_string(...)
output_stream_2(...)
do_write_string(...)
output_stream_2(...)
do_write_string(...)
output_stream_2(...)
do_write_string(...)
output_stream_2(...)
do_write_string(...)
output_stream_2(...)
do_write_string(...)
output_stream_2(...)
do_write_string(...)
Valid? depth io 10
dd> print io 9
read_line_as_string_2('<<foreign(stream, 0xNNNN)>>', yes, ok, "rafe\n", 
  '<<foreign(system_error, (nil))>>')
dd> depth io 1
dd> no
open_stream(...)
5 tabled IO actions:
do_open_text(...)
lock_stream_db
get_stream_db(...)
set_stream_db(...)
unlock_stream_db
Valid? yes
read_lines(...)
5 tabled IO actions:
read_line_as_string_2(...)
read_line_as_string_2(...)
read_line_as_string_2(...)
read_line_as_string_2(...)
read_line_as_string_2(...)
Valid? quit
Diagnosis aborted.
      E2:     C1 EXIT pred sort.main/2-0 (det) sort.m:28
mdb> quit -y
