      E1:     C1 CALL pred trust.main/2-0 (cc_multi) trust.m:18
mdb> mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> trust trust_1.
Trusting pred trust_1.w_cmp/3
mdb> trusted
Trusted Objects:
1: predicate trust_1.w_cmp/3
mdb> untrust 1
mdb> trusted
There are no trusted modules, predicates or functions.
mdb> trust trust_2
Trusting module trust_2
mdb> trust trust.
Ambiguous predicate or function specification. The matches are:
0: pred trust.main/2
1: pred trust.dostuff/2

Which predicate or function do you want to trust (0-1 or *)? 0
Trusting pred trust.main/2
mdb> trusted
Trusted Objects:
2: module trust_2
3: predicate trust.main/2
mdb> trust trust_2
Trusting module trust_2
mdb> trusted
Trusted Objects:
2: module trust_2
3: predicate trust.main/2
mdb> untrust 2
mdb> trust trust_1
Trusting module trust_1
mdb> trust no_such_module
mdb: there is no such module, predicate or function.
mdb> trust trust_2.
Trusting pred trust_2.concat/3
mdb> trust std lib
Trusting the Mercury standard library
mdb> trust standard library
Trusting the Mercury standard library
mdb> trusted
Trusted Objects:
3: predicate trust.main/2
4: module trust_1
5: predicate trust_2.concat/3
6: the Mercury standard library
mdb> untrust 3
mdb> trusted
Trusted Objects:
4: module trust_1
5: predicate trust_2.concat/3
6: the Mercury standard library
mdb> untrust 3
mdb: no such trusted object
mdb> untrust 99
mdb: no such trusted object
mdb> untrust 4
mdb> untrust 5
mdb> step
      E2:     C2 CALL pred trust.dostuff/2-0 (cc_multi)
mdb> finish
      E3:     C2 EXIT pred trust.dostuff/2-0 (cc_multi)
mdb> dd -d 3 -n 7
dostuff(w("aaabbb"), '=')
Valid? n
w_cmp('=', w("aaB"), w("aAB"))
Valid? trust
concat(w("aaa"), w("bbb"), w("aaabbb"))
Valid? trust module
Found incorrect contour:
w_cmp('=', w("aaB"), w("aAB"))
concat(w("aaa"), w("bbb"), w("aaabbb"))
dostuff(w("aaabbb"), '=')
Is this a bug? y
      E3:     C2 EXIT pred trust.dostuff/2-0 (cc_multi)
mdb> continue
aaabbb
'='
