#!/bin/sh
# Test whether the termination analysis algorithm of the Mercury compiler
# is working right.
# Return a status of 0 (true) if everything is all right, and 1 otherwise.

set -x

. ../handle_options

mmake $jfactor clean > /dev/null 2>&1
mmake $jfactor depend || exit 1
eval mmake -k $jfactor $gradeopt $flagsopt $cflagsopt check
checkstatus=$?

cat *.trans_opt_res > .allres
if test ! -s .allres -a "$checkstatus" = 0
then
	echo "the tests in the term directory succeeded"
	rm -f .allres
	exit 0
else
	echo "the tests in the term directory failed"
	echo "the differences are:"
	cat .allres
	exit 1
fi
