#!/bin/sh
# Test whether the termination analysis algorithm of the Mercury compiler
# is working right.
# Return a status of 0 (true) if everything is all right, and 1 otherwise.

. ../handle_options
. ../startup

mmake $jfactor depend || exit 1
eval mmake -k $jfactor $gradeopt $flagsopt $cflagsopt check
checkstatus=$?

cat *.trans_opt_res > .allres
if test ! -s .allres -a "$checkstatus" = 0
then
	echo "the tests in the term directory succeeded"
	echo "gradeopt=$gradeopt, flagsopt=$flagsopt, cflagsopt=$cflagsopt"
	rm -f .allres
	. ../shutdown
	exit 0
else
	echo "the tests in the term directory failed"
	echo "gradeopt=$gradeopt, flagsopt=$flagsopt, cflagsopt=$cflagsopt"
	echo "the differences are:"
	cat .allres
	exit 1
fi
