#!/bin/sh
# Test whether the compiler succeeds in generating code for each test.
# Return a status of 0 (true) if everything is all right, and 1 otherwise.

. ../handle_options
. ../startup

eval mmake $mmakeopts depend || exit 1
eval mmake -k $mmakeopts check
checkstatus=$?

objs=`mmake $mmakeopts printobjs`
failed=""
for obj in $objs
do
	if test ! -f "$obj"
	then
		failed="$failed $obj"
	fi
done

if test "$failed" = "" -a "$checkstatus" = 0
then
	echo "the tests in the valid directory succeeded"
	echo "mmakeopts=$mmakeopts"
	. ../shutdown
	exit 0
else
	echo "some tests in the valid directory failed: $failed"
	echo "mmakeopts=$mmakeopts"
	exit 1
fi
