exception: software_error("predicate `string.from_char_list\'/2: Unexpected: null character or surrogate code point in list")
exception: software_error("predicate `string.from_char_list\'/2: Unexpected: null character or surrogate code point in list")
exception: software_error("predicate `string.from_char_list\'/2: Unexpected: null character or surrogate code point in list")
succeeded: 😀

failed
failed
failed
failed
failed
succeeded: 😀
