[mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1), mono(1.1)]
[mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2), mono(2.2)]
[poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3), poly(3.3)]
