
plain call
50.625

higher-order call
50.625

docall
50.625

docall_inline
50.625

get_docall
50.625

get_docall2
50.625

get_docall3
50.625

docall_foreign_poly
50.625

docall_foreign_float
50.625

docall_struct_poly_generic_args
50.625

docall_struct_poly_float_args
50.625

docall_struct_mono
50.625

docall_struct_both
50.625
50.625

docall_pair_poly
50.625

docall_pair_float
50.625

docall_tuple_poly
50.625

docall_tuple_float
50.625

docall_tuple2_float
50.625

get_struct_pred_switch
50.625

get_struct_pred_disj
[50.625, 50.625, 50.625]

get_struct_pred_ite
50.625

meth1
50.625

meth2
50.625

meth3
50.625

meth4
50.625

meth5
50.625

cast_inst
50.625

lost_inst
50.625

map_recursive_type
[50.625, 50.625, 50.625]
