{token_cons(implementation_defined("f"), 1, token_nil), posn(1, 0, 2)}
{token_cons(implementation_defined("foo"), 1, token_nil), posn(1, 0, 4)}
{token_cons(name("$"), 1, token_cons(variable("FOO"), 1, token_nil)), posn(1, 0, 4)}
{token_cons(name("$"), 1, token_nil), posn(1, 0, 1)}
{token_cons(name("$!$"), 1, token_nil), posn(1, 0, 3)}
{token_cons(name("$"), 1, token_cons(comma, 1, token_nil)), posn(1, 0, 2)}
{token_cons(name("$"), 1, token_cons(integer(base_10, i(0, []), signed, size_word), 1, token_nil)), posn(1, 0, 2)}
