*** Testing int8 -> integer conversion ***

int8 = -128, integer = -128
int8 = -64, integer = -64
int8 = -32, integer = -32
int8 = -1, integer = -1
int8 = 0, integer = 0
int8 = 1, integer = 1
int8 = 2, integer = 2
int8 = 4, integer = 4
int8 = 8, integer = 8
int8 = 10, integer = 10
int8 = 16, integer = 16
int8 = 32, integer = 32
int8 = 64, integer = 64
int8 = 127, integer = 127

*** Testing integer -> int8 conversion ***

integer = -9223372036854775808, int8 = <<OUT-OF-RANGE>>
integer = -4294967296, int8 = <<OUT-OF-RANGE>>
integer = -2147483648, int8 = <<OUT-OF-RANGE>>
integer = -2, int8 = -2
integer = -1, int8 = -1
integer = 0, int8 = 0
integer = 1, int8 = 1
integer = 2, int8 = 2
integer = 16383, int8 = <<OUT-OF-RANGE>>
integer = 16384, int8 = <<OUT-OF-RANGE>>
integer = 16385, int8 = <<OUT-OF-RANGE>>
integer = 1073741824, int8 = <<OUT-OF-RANGE>>
integer = 2147483648, int8 = <<OUT-OF-RANGE>>
integer = 4294967295, int8 = <<OUT-OF-RANGE>>
integer = 4294967296, int8 = <<OUT-OF-RANGE>>
integer = 4294967297, int8 = <<OUT-OF-RANGE>>
integer = 9223372036854775808, int8 = <<OUT-OF-RANGE>>
integer = 18446744073709551615, int8 = <<OUT-OF-RANGE>>
integer = 18446744073709551616, int8 = <<OUT-OF-RANGE>>
