*** Testing uint8 -> integer conversion ***

uint8 = 0, integer = 0
uint8 = 1, integer = 1
uint8 = 2, integer = 2
uint8 = 4, integer = 4
uint8 = 8, integer = 8
uint8 = 10, integer = 10
uint8 = 16, integer = 16
uint8 = 32, integer = 32
uint8 = 64, integer = 64
uint8 = 255, integer = 255

*** Testing integer -> uint8 conversion ***

integer = -255, uint8 = <<OUT-OF-RANGE>>
integer = -128, uint8 = <<OUT-OF-RANGE>>
integer = -2, uint8 = <<OUT-OF-RANGE>>
integer = -1, uint8 = <<OUT-OF-RANGE>>
integer = 0, uint8 = 0
integer = 1, uint8 = 1
integer = 2, uint8 = 2
integer = 127, uint8 = 127
integer = 254, uint8 = 254
integer = 255, uint8 = 255
integer = 256, uint8 = <<OUT-OF-RANGE>>
integer = 16383, uint8 = <<OUT-OF-RANGE>>
integer = 16384, uint8 = <<OUT-OF-RANGE>>
integer = 16385, uint8 = <<OUT-OF-RANGE>>
