thing(no, no, 42i8, yes, yes, yes)
thing(no, no, 42i8, yes, yes, no)
three(three(one(thing(no, no, 42i8, yes, yes, yes)), one(thing(no, yes, 43i8, no, yes, yes)), one(thing(no, yes, 43i8, no, yes, no))), three(one(thing(no, no, 42i8, yes, yes, yes)), one(thing(no, yes, 43i8, no, yes, yes)), one(thing(no, yes, 43i8, no, yes, no))), three(one(thing(no, no, 42i8, yes, yes, yes)), one(thing(no, yes, 43i8, no, yes, yes)), one(thing(no, yes, 43i8, no, yes, no))))
