abc_42_def_%x_ghi_HAL_jkl_1111_mno_2222_pqr\
cba_y_def_%143_ghi_IBM    _jkl\
cba_JCN_fed_%z_ghi_241_jkl\
abc_0343_def_%v_ghi_KDO_jkl\

abc_42_def_%a_ghi_WHAL_jkl_3333_mno_4444_pqr\
cba_b_def_%143_ghi_WIBM_jkl\
cba_WJCN_fed_%c_ghi_241_jkl\
abc_  343_def_%d_ghi_ WKDO_jkl\

abc_42_def_%e_ghi_XHAL_jkl_5555_mno_6666_pqr\
cba_f_def_%143_ghi_XIBM_jkl\
cba_XJCN_fed_%g_ghi_241_jkl\
abc_  343_def_%h_ghi_ XKDO_jkl\
