

depth 0, size 0, width 20
[]
array([])
array([])
{}
{...}
{...}
{...}
{...}
map([])
map([])
leaf
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 0, size 0, width 40
[]
array([])
array([])
{}
{...}
{...}
{...}
{...}
map([])
map([])
leaf
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 0, size 0, width 80
[]
array([])
array([])
{}
{...}
{...}
{...}
{...}
map([])
map([])
leaf
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 0, size 1, width 20
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 0, size 1, width 40
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 0, size 1, width 80
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 0, size 3, width 20
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 0, size 3, width 40
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 0, size 3, width 80
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 0, size 5, width 20
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 0, size 5, width 40
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 0, size 5, width 80
[...]
array([...])
array([...])
{}
{...}
{...}
{...}
{...}
map([...])
map([...])
branch/3
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 5, size 0, width 20
[]
array([])
array([])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([])
map([])
leaf
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 5, size 0, width 40
[]
array([])
array([])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([])
map([])
leaf
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 5, size 0, width 80
[]
array([])
array([])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([])
map([])
leaf
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 5, size 1, width 20
[1]
array([[1]])
array([[1]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1]])
map([1 -> [1]])
branch(leaf, 1, 
  leaf)
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 5, size 1, width 40
[1]
array([[1]])
array([[1]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1]])
map([1 -> [1]])
branch(leaf, 1, leaf)
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 5, size 1, width 80
[1]
array([[1]])
array([[1]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1]])
map([1 -> [1]])
branch(leaf, 1, leaf)
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 5, size 3, width 20
[1, 2, 3]
array([[1], [1], 
 [1]])
array([
 [1, 2, ...], 
 [1, 2, ...], 
 [1, 2, ...]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1], 
 2 -> [1], 3 -> [1]])
map([
 1 -> [1, ...], 
 2 -> [1, ...], 
 3 -> [1, ...]])
branch(
  branch(
    branch(leaf, 
      1, ...), 2, 
    branch(leaf, 
      1, ...)), 3, 
  branch(
    branch(leaf, 
      1, ...), 2, 
    branch(leaf, 
      1, ...)))
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 5, size 3, width 40
[1, 2, 3]
array([[1], [1], [1]])
array([[1, 2, ...], [1, 2, ...], 
 [1, 2, ...]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1], 2 -> [1], 3 -> [1]])
map([1 -> [1, ...], 2 -> [1, ...], 
 3 -> [1, ...]])
branch(
  branch(branch(leaf, 1, ...), 2, 
    branch(leaf, 1, ...)), 3, 
  branch(branch(leaf, 1, ...), 2, 
    branch(leaf, 1, ...)))
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 5, size 3, width 80
[1, 2, 3]
array([[1], [1], [1]])
array([[1, 2, ...], [1, 2, ...], [1, 2, ...]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1], 2 -> [1], 3 -> [1]])
map([1 -> [1, ...], 2 -> [1, ...], 3 -> [1, ...]])
branch(branch(branch(leaf, 1, ...), 2, branch(leaf, 1, ...)), 3, 
  branch(branch(leaf, 1, ...), 2, branch(leaf, 1, ...)))
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 5, size 5, width 20
[1, 2, 3, 4, ...]
array([[1], [1], 
 [1], ...])
array([
 [1, 2, ...], 
 [1, 2, ...], 
 [1, 2, ...], ...])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1], 
 2 -> [1], 
 3 -> [1], ...])
map([
 1 -> [1, ...], 
 2 -> [1, ...], 
 3 -> [1, ...], ...])
branch(
  branch(
    branch(
      branch(
        branch(...), 
        ...), 3, 
      ...), 4, 
    branch(
      branch(
        branch(...), 
        ...), 3, 
      ...)), 5, 
  branch(
    branch(
      branch(
        branch(...), 
        ...), 3, 
      ...), 4, 
    branch(
      branch(
        branch(...), 
        ...), 3, 
      ...)))
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 5, size 5, width 40
[1, 2, 3, 4, ...]
array([[1], [1], [1], ...])
array([[1, 2, ...], [1, 2, ...], 
 [1, 2, ...], ...])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1], 2 -> [1], 3 -> [1], ...])
map([1 -> [1, ...], 2 -> [1, ...], 
 3 -> [1, ...], ...])
branch(
  branch(
    branch(branch(branch(...), ...), 
      3, ...), 4, 
    branch(branch(branch(...), ...), 
      3, ...)), 5, 
  branch(
    branch(branch(branch(...), ...), 
      3, ...), 4, 
    branch(branch(branch(...), ...), 
      3, ...)))
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 5, size 5, width 80
[1, 2, 3, 4, ...]
array([[1], [1], [1], ...])
array([[1, 2, ...], [1, 2, ...], [1, 2, ...], ...])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, ...}
map([1 -> [1], 2 -> [1], 3 -> [1], ...])
map([1 -> [1, ...], 2 -> [1, ...], 3 -> [1, ...], ...])
branch(
  branch(branch(branch(branch(...), ...), 3, ...), 4, 
    branch(branch(branch(...), ...), 3, ...)), 5, 
  branch(branch(branch(branch(...), ...), 3, ...), 4, 
    branch(branch(branch(...), ...), 3, ...)))
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 1000, size 0, width 20
[]
array([])
array([])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 
 7, 8, 9, 10}
map([])
map([])
leaf
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 1000, size 0, width 40
[]
array([])
array([])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([])
map([])
leaf
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 1000, size 0, width 80
[]
array([])
array([])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([])
map([])
leaf
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 1000, size 1, width 20
[1]
array([[1]])
array([[1]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 
 7, 8, 9, 10}
map([1 -> [1]])
map([1 -> [1]])
branch(leaf, 1, 
  leaf)
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 1000, size 1, width 40
[1]
array([[1]])
array([[1]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([1 -> [1]])
map([1 -> [1]])
branch(leaf, 1, leaf)
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 1000, size 1, width 80
[1]
array([[1]])
array([[1]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([1 -> [1]])
map([1 -> [1]])
branch(leaf, 1, leaf)
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 1000, size 3, width 20
[1, 2, 3]
array([[1], [1], 
 [1]])
array([[1, 2, 3], 
 [1, 2, 3], 
 [1, 2, 3]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 
 7, 8, 9, 10}
map([1 -> [1], 
 2 -> [1], 3 -> [1]])
map([
 1 -> [1, 2, 3], 
 2 -> [1, 2, 3], 
 3 -> [1, 2, 3]])
branch(
  branch(
    branch(leaf, 
      1, leaf), 2, 
    branch(leaf, 
      1, leaf)), 
  3, 
  branch(
    branch(leaf, 
      1, leaf), 2, 
    branch(leaf, 
      1, leaf)))
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 1000, size 3, width 40
[1, 2, 3]
array([[1], [1], [1]])
array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([1 -> [1], 2 -> [1], 3 -> [1]])
map([1 -> [1, 2, 3], 2 -> [1, 2, 3], 
 3 -> [1, 2, 3]])
branch(
  branch(branch(leaf, 1, leaf), 2, 
    branch(leaf, 1, leaf)), 3, 
  branch(branch(leaf, 1, leaf), 2, 
    branch(leaf, 1, leaf)))
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 1000, size 3, width 80
[1, 2, 3]
array([[1], [1], [1]])
array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([1 -> [1], 2 -> [1], 3 -> [1]])
map([1 -> [1, 2, 3], 2 -> [1, 2, 3], 3 -> [1, 2, 3]])
branch(branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)), 3, 
  branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)))
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!


depth 1000, size 5, width 20
[1, 2, 3, 4, 5]
array([[1], [1], 
 [1], [1], [1]])
array([
 [1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 
 7, 8, 9, 10}
map([1 -> [1], 
 2 -> [1], 
 3 -> [1], 
 4 -> [1], 5 -> [1]])
map([
 1 -> 
   [1, 2, 3, 4, 5], 
 2 -> 
   [1, 2, 3, 4, 5], 
 3 -> 
   [1, 2, 3, 4, 5], 
 4 -> 
   [1, 2, 3, 4, 5], 
 5 -> 
   [1, 2, 3, 4, 5]])
branch(
  branch(
    branch(
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf)), 
      3, 
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf))), 
    4, 
    branch(
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf)), 
      3, 
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf)))), 
  5, 
  branch(
    branch(
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf)), 
      3, 
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf))), 
    4, 
    branch(
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf)), 
      3, 
      branch(
        branch(
          leaf, 1, 
          leaf), 
        2, 
        branch(
          leaf, 1, 
          leaf)))))
In Xanadu did 
Kubla Khan A 
stately 
pleasure-dome 
decree: Where 
Alph, the sacred 
river, ran Through 
caverns 
measureless to man 
Down to a sunless 
sea. So twice five 
miles of fertile 
ground With walls 
and towers were 
girdled round: And 
here were gardens 
bright with 
sinuous rills 
Where blossomed 
many an 
incense-bearing 
tree; And here 
were forests 
ancient as the 
hills, Enfolding 
sunny spots of 
greenery. But oh! 
that deep romantic 
chasm which 
slanted Down the 
green hill athwart 
a cedarn cover! A 
savage place! as 
holy and enchanted 
As e'er beneath a 
waning moon was 
haunted By woman 
wailing for her 
demon-lover!


depth 1000, size 5, width 40
[1, 2, 3, 4, 5]
array([[1], [1], [1], [1], [1]])
array([[1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([1 -> [1], 2 -> [1], 3 -> [1], 
 4 -> [1], 5 -> [1]])
map([1 -> [1, 2, 3, 4, 5], 
 2 -> [1, 2, 3, 4, 5], 
 3 -> [1, 2, 3, 4, 5], 
 4 -> [1, 2, 3, 4, 5], 
 5 -> [1, 2, 3, 4, 5]])
branch(
  branch(
    branch(
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf))), 4, 
    branch(
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf)))), 5, 
  branch(
    branch(
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf))), 4, 
    branch(
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, 
        branch(leaf, 1, leaf)))))
In Xanadu did Kubla Khan A stately 
pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns 
measureless to man Down to a sunless 
sea. So twice five miles of fertile 
ground With walls and towers were 
girdled round: And here were gardens 
bright with sinuous rills Where 
blossomed many an incense-bearing 
tree; And here were forests ancient as 
the hills, Enfolding sunny spots of 
greenery. But oh! that deep romantic 
chasm which slanted Down the green 
hill athwart a cedarn cover! A savage 
place! as holy and enchanted As e'er 
beneath a waning moon was haunted By 
woman wailing for her demon-lover!


depth 1000, size 5, width 80
[1, 2, 3, 4, 5]
array([[1], [1], [1], [1], [1]])
array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], 
 [1, 2, 3, 4, 5]])
{}
{1}
{1, 2}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
map([1 -> [1], 2 -> [1], 3 -> [1], 4 -> [1], 5 -> [1]])
map([1 -> [1, 2, 3, 4, 5], 2 -> [1, 2, 3, 4, 5], 3 -> [1, 2, 3, 4, 5], 
 4 -> [1, 2, 3, 4, 5], 5 -> [1, 2, 3, 4, 5]])
branch(
  branch(
    branch(branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf))), 4, 
    branch(branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)))), 5, 
  branch(
    branch(branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf))), 4, 
    branch(branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)), 3, 
      branch(branch(leaf, 1, leaf), 2, branch(leaf, 1, leaf)))))
In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the 
sacred river, ran Through caverns measureless to man Down to a sunless sea. So 
twice five miles of fertile ground With walls and towers were girdled round: 
And here were gardens bright with sinuous rills Where blossomed many an 
incense-bearing tree; And here were forests ancient as the hills, Enfolding 
sunny spots of greenery. But oh! that deep romantic chasm which slanted Down 
the green hill athwart a cedarn cover! A savage place! as holy and enchanted 
As e'er beneath a waning moon was haunted By woman wailing for her demon-lover!
