foo(-2147483648)
foo(2147483647)
io.read: the term read did not have the right type
io.read: the term read did not have the right type
io.read: the term read did not have the right type
io.read: the term read did not have the right type

foo(-2147483648)
foo(2147483647)
io.read: the term read did not have the right type
io.read: the term read did not have the right type
io.read: the term read did not have the right type
io.read: the term read did not have the right type
