Rel =
"a" - "b"
"b" - "c"
"c" - "d"
"l1" - "l2"
"l2" - "l3"
"l3" - "l1"
"x" - "x"

tc of Rel =
"a" - "b"
"a" - "c"
"a" - "d"
"b" - "c"
"b" - "d"
"c" - "d"
"l1" - "l1"
"l1" - "l2"
"l1" - "l3"
"l2" - "l1"
"l2" - "l2"
"l2" - "l3"
"l3" - "l1"
"l3" - "l2"
"l3" - "l3"
"x" - "x"

rtc of Rel =
"a" - "a"
"a" - "b"
"a" - "c"
"a" - "d"
"b" - "b"
"b" - "c"
"b" - "d"
"c" - "c"
"c" - "d"
"d" - "d"
"l1" - "l1"
"l1" - "l2"
"l1" - "l3"
"l2" - "l1"
"l2" - "l2"
"l2" - "l3"
"l3" - "l1"
"l3" - "l2"
"l3" - "l3"
"x" - "x"

Rel2 =
"a" - "a1"
"b" - "b1"
"c" - "c1"
"d" - "d1"

composition of Rel1 and Rel2 =
"a" - "b1"
"b" - "c1"
"c" - "d1"

relation__is_dag(Rel) failed as expected
relation__is_dag(Rel) succeeded
