Rel =
"a" - "b"
	"b" - "c"
	"c" - "d"
	"l1" - "l2"
	"l2" - "l3"
	"l3" - "l1"
	"x" - "x"

tc =
"a" - "b"
	"a" - "c"
	"a" - "d"
	"b" - "c"
	"b" - "d"
	"c" - "d"
	"l1" - "l1"
	"l1" - "l2"
	"l1" - "l3"
	"l2" - "l1"
	"l2" - "l2"
	"l2" - "l3"
	"l3" - "l1"
	"l3" - "l2"
	"l3" - "l3"
	"x" - "x"

rtc =
"a" - "a"
	"a" - "b"
	"a" - "c"
	"a" - "d"
	"b" - "b"
	"b" - "c"
	"b" - "d"
	"c" - "c"
	"c" - "d"
	"d" - "d"
	"l1" - "l1"
	"l1" - "l2"
	"l1" - "l3"
	"l2" - "l1"
	"l2" - "l2"
	"l2" - "l3"
	"l3" - "l1"
	"l3" - "l2"
	"l3" - "l3"
	"x" - "x"

sc =
"a" - "b"
	"b" - "a"
	"b" - "c"
	"c" - "b"
	"c" - "d"
	"d" - "c"
	"l1" - "l2"
	"l1" - "l3"
	"l2" - "l1"
	"l2" - "l3"
	"l3" - "l1"
	"l3" - "l2"
	"x" - "x"

dfs =
["d", "c", "b", "a", "l3", "l2", "l1", "x"]
atsort =
[["x"], ["l1", "l2", "l3"], ["a"], ["b"], ["c"], ["d"]]
tsort failed
is_dag failed
Rel2 =
"a" - "a1"
	"b" - "b1"
	"c" - "c1"
	"d" - "d1"

tc =
"a" - "a1"
	"b" - "b1"
	"c" - "c1"
	"d" - "d1"

rtc =
"a" - "a"
	"a" - "a1"
	"a1" - "a1"
	"b" - "b"
	"b" - "b1"
	"b1" - "b1"
	"c" - "c"
	"c" - "c1"
	"c1" - "c1"
	"d" - "d"
	"d" - "d1"
	"d1" - "d1"

sc =
"a" - "a1"
	"a1" - "a"
	"b" - "b1"
	"b1" - "b"
	"c" - "c1"
	"c1" - "c"
	"d" - "d1"
	"d1" - "d"

dfs =
["a1", "a", "b1", "b", "c1", "c", "d1", "d"]
atsort =
[["d"], ["d1"], ["c"], ["c1"], ["b"], ["b1"], ["a"], ["a1"]]
tsort =
["d", "d1", "c", "c1", "b", "b1", "a", "a1"]
is_dag succeeded
composition of Rel and Rel2 =
"a" - "b1"
	"b" - "c1"
	"c" - "d1"

