:- module rtc_bug.
:- interface.
:- import_module io.
:- pred main(state::di, state::uo) is det.

:- implementation.
:- import_module relation, pair, list.

main -->
	{ l(L) },
	io__print("L:"), io__nl,
	io__write_list(L, "\n", io__print), io__nl, io__nl,
	{ relation__from_assoc_list(L, R) },
	{ relation__rtc(R, RTC_R) },
	{ relation__to_assoc_list(RTC_R, RTC_L0) },
	{ list__sort(RTC_L0, RTC_L) },
	io__print("RTC_L:"), io__nl,
	io__write_list(RTC_L, "\n", io__print), io__nl, io__nl,
	[].

:- pred l(list(pair(string)) :: out) is det.
l(["varset" - "mercury_builtin",
"varset" - "list",
"varset" - "assoc_list",
"varset" - "map",
"varset" - "term",
"term" - "mercury_builtin",
"term" - "list",
"term" - "std_util",
"term" - "map",
"store" - "mercury_builtin",
"stack" - "mercury_builtin",
"stack" - "list",
"set_unordlist" - "mercury_builtin",
"set_unordlist" - "list",
"set_unordlist" - "bool",
"set_ordlist" - "mercury_builtin",
"set_ordlist" - "list",
"set_ordlist" - "bool",
"require" - "mercury_builtin",
"set_bbbtree" - "mercury_builtin",
"set_bbbtree" - "list",
"set_bbbtree" - "bool",
"relation" - "mercury_builtin",
"relation" - "list",
"relation" - "assoc_list",
"relation" - "set",
"relation" - "set_bbbtree",
"rbtree" - "mercury_builtin",
"rbtree" - "list",
"rbtree" - "assoc_list",
"random" - "mercury_builtin",
"random" - "list",
"queue" - "mercury_builtin",
"queue" - "list",
"prolog" - "mercury_builtin",
"prolog" - "list",
"prolog" - "std_util",
"pqueue" - "mercury_builtin",
"pqueue" - "assoc_list",
"term_io" - "mercury_builtin",
"term_io" - "char",
"term_io" - "io",
"term_io" - "term",
"term_io" - "varset",
"parser" - "mercury_builtin",
"parser" - "io",
"parser" - "term_io",
"multi_map" - "mercury_builtin",
"multi_map" - "list",
"multi_map" - "assoc_list",
"multi_map" - "map",
"multi_map" - "set",
"math" - "mercury_builtin",
"tree234" - "mercury_builtin",
"tree234" - "list",
"tree234" - "assoc_list",
"library" - "mercury_builtin",
"lexer" - "mercury_builtin",
"lexer" - "char",
"lexer" - "io",
"ops" - "mercury_builtin",
"string" - "mercury_builtin",
"string" - "list",
"string" - "char",
"io" - "mercury_builtin",
"io" - "list",
"io" - "std_util",
"io" - "char",
"io" - "string",
"io" - "ops",
"group" - "mercury_builtin",
"group" - "list",
"group" - "assoc_list",
"group" - "set",
"graph" - "mercury_builtin",
"graph" - "list",
"graph" - "std_util",
"graph" - "set",
"getopt" - "mercury_builtin",
"getopt" - "list",
"getopt" - "std_util",
"getopt" - "map",
"getopt" - "bool",
"getopt" - "char",
"float" - "mercury_builtin",
"set" - "mercury_builtin",
"set" - "list",
"set" - "bool",
"eqvclass" - "mercury_builtin",
"eqvclass" - "list",
"eqvclass" - "set",
"dir" - "mercury_builtin",
"debugger_interface" - "mercury_builtin",
"char" - "mercury_builtin",
"int" - "mercury_builtin",
"bt_array" - "mercury_builtin",
"bt_array" - "list",
"bt_array" - "int",
"bool" - "mercury_builtin",
"bool" - "list",
"bintree_set" - "mercury_builtin",
"bintree_set" - "list",
"bintree" - "mercury_builtin",
"bintree" - "list",
"bintree" - "assoc_list",
"map" - "mercury_builtin",
"map" - "list",
"map" - "assoc_list",
"map" - "set",
"map" - "tree234",
"bimap" - "mercury_builtin",
"bimap" - "list",
"bimap" - "assoc_list",
"bimap" - "map",
"benchmarking" - "mercury_builtin",
"bag" - "mercury_builtin",
"bag" - "list",
"bag" - "assoc_list",
"assoc_list" - "mercury_builtin",
"assoc_list" - "list",
"assoc_list" - "std_util",
"std_util" - "mercury_builtin",
"std_util" - "list",
"std_util" - "set",
"list" - "mercury_builtin",
"list" - "int",
"mercury_builtin" - "mercury_builtin",
"array" - "mercury_builtin",
"array" - "list",
"array" - "std_util"]).

:- end_module rtc_bug.

