
!
hello:world:how:are:you!
hello<tab>world<tab>how<tab>are<tab><tab>you!
user<tab>group<tab>id1<tab>id2
x<tab>ay<tab>az
x<tab>a <tab>aax <tab> x
col1<tab>col2:val2<tab>col3<tab>

"line1"
"line2"
"line3"
"line4"

"line1"
"line2"
"line3"
"line4nonl"

split_into_lines("") = []
split_into_lines("a") = ["a"]
split_into_lines("a\n") = ["a"]
split_into_lines("\n") = [""]
split_into_lines("a\n\nb") = ["a", "", "b"]
split_into_lines(" ") = [" "]
split_into_lines("\r") = ["\r"]
split_into_lines("\r\n") = ["\r"]
split_into_lines("a\r") = ["a\r"]
split_into_lines("a\r\n") = ["a\r"]
split_into_lines("\a\b\e\f\t\v\n") = ["\a\b\e\f\t\v"]
split_into_lines("a\034\b") = ["a\034\b"]
split_into_lines("a\035\b") = ["a\035\b"]
split_into_lines("a\036\b") = ["a\036\b"]
split_into_lines("a\205\b") = ["a\205\b"]

