Test list and rev_list
empty_cord
[]
[]
nonempty_cord(unit_node(1))
[1]
[1]
nonempty_cord(list_node(2, [3, 4]))
[2, 3, 4]
[4, 3, 2]
nonempty_cord(branch_node(unit_node(1), unit_node(1)))
[1, 1]
[1, 1]
nonempty_cord(branch_node(unit_node(1), list_node(2, [3, 4])))
[1, 2, 3, 4]
[4, 3, 2, 1]
nonempty_cord(branch_node(unit_node(1), branch_node(unit_node(1), unit_node(1))))
[1, 1, 1]
[1, 1, 1]
nonempty_cord(branch_node(unit_node(1), branch_node(unit_node(1), list_node(2, [3, 4]))))
[1, 1, 2, 3, 4]
[4, 3, 2, 1, 1]
nonempty_cord(branch_node(unit_node(1), branch_node(list_node(2, [3, 4]), unit_node(1))))
[1, 2, 3, 4, 1]
[1, 4, 3, 2, 1]
nonempty_cord(branch_node(unit_node(1), branch_node(list_node(2, [3, 4]), list_node(2, [3, 4]))))
[1, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 1]
nonempty_cord(branch_node(list_node(2, [3, 4]), unit_node(1)))
[2, 3, 4, 1]
[1, 4, 3, 2]
nonempty_cord(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])))
[2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(list_node(2, [3, 4]), branch_node(unit_node(1), unit_node(1))))
[2, 3, 4, 1, 1]
[1, 1, 4, 3, 2]
nonempty_cord(branch_node(list_node(2, [3, 4]), branch_node(unit_node(1), list_node(2, [3, 4]))))
[2, 3, 4, 1, 2, 3, 4]
[4, 3, 2, 1, 4, 3, 2]
nonempty_cord(branch_node(list_node(2, [3, 4]), branch_node(list_node(2, [3, 4]), unit_node(1))))
[2, 3, 4, 2, 3, 4, 1]
[1, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(list_node(2, [3, 4]), branch_node(list_node(2, [3, 4]), list_node(2, [3, 4]))))
[2, 3, 4, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(branch_node(unit_node(1), unit_node(1)), unit_node(1)))
[1, 1, 1]
[1, 1, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), unit_node(1)), list_node(2, [3, 4])))
[1, 1, 2, 3, 4]
[4, 3, 2, 1, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), unit_node(1)), branch_node(unit_node(1), unit_node(1))))
[1, 1, 1, 1]
[1, 1, 1, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), unit_node(1)), branch_node(unit_node(1), list_node(2, [3, 4]))))
[1, 1, 1, 2, 3, 4]
[4, 3, 2, 1, 1, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), unit_node(1)), branch_node(list_node(2, [3, 4]), unit_node(1))))
[1, 1, 2, 3, 4, 1]
[1, 4, 3, 2, 1, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), unit_node(1)), branch_node(list_node(2, [3, 4]), list_node(2, [3, 4]))))
[1, 1, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 1, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), list_node(2, [3, 4])), unit_node(1)))
[1, 2, 3, 4, 1]
[1, 4, 3, 2, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), list_node(2, [3, 4])), list_node(2, [3, 4])))
[1, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), list_node(2, [3, 4])), branch_node(unit_node(1), unit_node(1))))
[1, 2, 3, 4, 1, 1]
[1, 1, 4, 3, 2, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), list_node(2, [3, 4])), branch_node(unit_node(1), list_node(2, [3, 4]))))
[1, 2, 3, 4, 1, 2, 3, 4]
[4, 3, 2, 1, 4, 3, 2, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), list_node(2, [3, 4])), branch_node(list_node(2, [3, 4]), unit_node(1))))
[1, 2, 3, 4, 2, 3, 4, 1]
[1, 4, 3, 2, 4, 3, 2, 1]
nonempty_cord(branch_node(branch_node(unit_node(1), list_node(2, [3, 4])), branch_node(list_node(2, [3, 4]), list_node(2, [3, 4]))))
[1, 2, 3, 4, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 4, 3, 2, 1]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), unit_node(1)), unit_node(1)))
[2, 3, 4, 1, 1]
[1, 1, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), unit_node(1)), list_node(2, [3, 4])))
[2, 3, 4, 1, 2, 3, 4]
[4, 3, 2, 1, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), unit_node(1)), branch_node(unit_node(1), unit_node(1))))
[2, 3, 4, 1, 1, 1]
[1, 1, 1, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), unit_node(1)), branch_node(unit_node(1), list_node(2, [3, 4]))))
[2, 3, 4, 1, 1, 2, 3, 4]
[4, 3, 2, 1, 1, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), unit_node(1)), branch_node(list_node(2, [3, 4]), unit_node(1))))
[2, 3, 4, 1, 2, 3, 4, 1]
[1, 4, 3, 2, 1, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), unit_node(1)), branch_node(list_node(2, [3, 4]), list_node(2, [3, 4]))))
[2, 3, 4, 1, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 1, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])), unit_node(1)))
[2, 3, 4, 2, 3, 4, 1]
[1, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])), list_node(2, [3, 4])))
[2, 3, 4, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])), branch_node(unit_node(1), unit_node(1))))
[2, 3, 4, 2, 3, 4, 1, 1]
[1, 1, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])), branch_node(unit_node(1), list_node(2, [3, 4]))))
[2, 3, 4, 2, 3, 4, 1, 2, 3, 4]
[4, 3, 2, 1, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])), branch_node(list_node(2, [3, 4]), unit_node(1))))
[2, 3, 4, 2, 3, 4, 2, 3, 4, 1]
[1, 4, 3, 2, 4, 3, 2, 4, 3, 2]
nonempty_cord(branch_node(branch_node(list_node(2, [3, 4]), list_node(2, [3, 4])), branch_node(list_node(2, [3, 4]), list_node(2, [3, 4]))))
[2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4]
[4, 3, 2, 4, 3, 2, 4, 3, 2, 4, 3, 2]

Test folds
done.

Test cord_list_to_cord and cord_list_to_list
done.
