Empty =
[]

One =
[[1]]
One ^ elem(0, 0) = 1

Two =
[[1, 0]
 [0, 2]]
Two ^ elem(0, 0) = 1
Two ^ elem(0, 1) = 0
Two ^ elem(1, 0) = 0
Two ^ elem(1, 1) = 2

Empty is empty
One is not empty
Two is not empty

Two_a =
[[1, 3]
 [0, 2]]

Two_b =
[[1, 3]
 [4, 2]]

Zeroes =
[[0, 0, 0]
 [0, 0, 0]
 [0, 0, 0]]

Empty ^ elem(0, 0) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))
Zeroes ^ elem(-1, 0) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))
Zeroes ^ elem(0, -1) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))
Zeroes ^ elem(-1, -1) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))
Zeroes ^ elem(3, 0) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))
Zeroes ^ elem(0, 3) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))
Zeroes ^ elem(3, 3) = exception(univ_cons(software_error("function `array2d.lookup\'/3: indices out of bounds")))

[11, 12, 13, 14, 15, 16]
[21, 22, 23, 24, 25, 26]
[31, 32, 33, 34, 35, 36]
[41, 42, 43, 44, 45, 46]
