unify:
node({nil, fruit("apple")}) =  node({nil, fruit("apple")})
node({nil, fruit("apple")}) \= node({nil, fruit("peach")})
node({nil, fruit("peach")}) \= node({nil, fruit("apple")})
node({nil, fruit("peach")}) =  node({nil, fruit("peach")})

compare:
node({nil, fruit("apple")}) = node({nil, fruit("apple")})
node({nil, fruit("apple")}) < node({nil, fruit("peach")})
node({nil, fruit("peach")}) > node({nil, fruit("apple")})
node({nil, fruit("peach")}) = node({nil, fruit("peach")})
