func/1 [float, float]
func/1 [int, int]
func/2 [int, int, int]
pred/1 [int]
pred/2 [int, int]
{}/1 [string]
{}/3 [string, int, float]
list:list/1 [float]
list:list/1 [int]
tree234:tree234/2 [float, int]
tree234:tree234/2 [int, float]
tree234:tree234/2 [int, int]
func(float) = float = func(float) = float
func(float) = float < func(int) = int
func(float) = float < func(int, int) = int
func(float) = float < pred(int)
func(float) = float < pred(int, int)
func(float) = float < {string}
func(float) = float < {string, int, float}
func(float) = float < list:list(float)
func(float) = float < list:list(int)
func(float) = float < tree234:tree234(float, int)
func(float) = float < tree234:tree234(int, float)
func(float) = float < tree234:tree234(int, int)
func(int) = int > func(float) = float
func(int) = int = func(int) = int
func(int) = int < func(int, int) = int
func(int) = int < pred(int)
func(int) = int < pred(int, int)
func(int) = int < {string}
func(int) = int < {string, int, float}
func(int) = int < list:list(float)
func(int) = int < list:list(int)
func(int) = int < tree234:tree234(float, int)
func(int) = int < tree234:tree234(int, float)
func(int) = int < tree234:tree234(int, int)
func(int, int) = int > func(float) = float
func(int, int) = int > func(int) = int
func(int, int) = int = func(int, int) = int
func(int, int) = int < pred(int)
func(int, int) = int < pred(int, int)
func(int, int) = int < {string}
func(int, int) = int < {string, int, float}
func(int, int) = int < list:list(float)
func(int, int) = int < list:list(int)
func(int, int) = int < tree234:tree234(float, int)
func(int, int) = int < tree234:tree234(int, float)
func(int, int) = int < tree234:tree234(int, int)
pred(int) > func(float) = float
pred(int) > func(int) = int
pred(int) > func(int, int) = int
pred(int) = pred(int)
pred(int) < pred(int, int)
pred(int) < {string}
pred(int) < {string, int, float}
pred(int) < list:list(float)
pred(int) < list:list(int)
pred(int) < tree234:tree234(float, int)
pred(int) < tree234:tree234(int, float)
pred(int) < tree234:tree234(int, int)
pred(int, int) > func(float) = float
pred(int, int) > func(int) = int
pred(int, int) > func(int, int) = int
pred(int, int) > pred(int)
pred(int, int) = pred(int, int)
pred(int, int) < {string}
pred(int, int) < {string, int, float}
pred(int, int) < list:list(float)
pred(int, int) < list:list(int)
pred(int, int) < tree234:tree234(float, int)
pred(int, int) < tree234:tree234(int, float)
pred(int, int) < tree234:tree234(int, int)
{string} > func(float) = float
{string} > func(int) = int
{string} > func(int, int) = int
{string} > pred(int)
{string} > pred(int, int)
{string} = {string}
{string} < {string, int, float}
{string} < list:list(float)
{string} < list:list(int)
{string} < tree234:tree234(float, int)
{string} < tree234:tree234(int, float)
{string} < tree234:tree234(int, int)
{string, int, float} > func(float) = float
{string, int, float} > func(int) = int
{string, int, float} > func(int, int) = int
{string, int, float} > pred(int)
{string, int, float} > pred(int, int)
{string, int, float} > {string}
{string, int, float} = {string, int, float}
{string, int, float} < list:list(float)
{string, int, float} < list:list(int)
{string, int, float} < tree234:tree234(float, int)
{string, int, float} < tree234:tree234(int, float)
{string, int, float} < tree234:tree234(int, int)
list:list(float) > func(float) = float
list:list(float) > func(int) = int
list:list(float) > func(int, int) = int
list:list(float) > pred(int)
list:list(float) > pred(int, int)
list:list(float) > {string}
list:list(float) > {string, int, float}
list:list(float) = list:list(float)
list:list(float) < list:list(int)
list:list(float) < tree234:tree234(float, int)
list:list(float) < tree234:tree234(int, float)
list:list(float) < tree234:tree234(int, int)
list:list(int) > func(float) = float
list:list(int) > func(int) = int
list:list(int) > func(int, int) = int
list:list(int) > pred(int)
list:list(int) > pred(int, int)
list:list(int) > {string}
list:list(int) > {string, int, float}
list:list(int) > list:list(float)
list:list(int) = list:list(int)
list:list(int) < tree234:tree234(float, int)
list:list(int) < tree234:tree234(int, float)
list:list(int) < tree234:tree234(int, int)
tree234:tree234(float, int) > func(float) = float
tree234:tree234(float, int) > func(int) = int
tree234:tree234(float, int) > func(int, int) = int
tree234:tree234(float, int) > pred(int)
tree234:tree234(float, int) > pred(int, int)
tree234:tree234(float, int) > {string}
tree234:tree234(float, int) > {string, int, float}
tree234:tree234(float, int) > list:list(float)
tree234:tree234(float, int) > list:list(int)
tree234:tree234(float, int) = tree234:tree234(float, int)
tree234:tree234(float, int) < tree234:tree234(int, float)
tree234:tree234(float, int) < tree234:tree234(int, int)
tree234:tree234(int, float) > func(float) = float
tree234:tree234(int, float) > func(int) = int
tree234:tree234(int, float) > func(int, int) = int
tree234:tree234(int, float) > pred(int)
tree234:tree234(int, float) > pred(int, int)
tree234:tree234(int, float) > {string}
tree234:tree234(int, float) > {string, int, float}
tree234:tree234(int, float) > list:list(float)
tree234:tree234(int, float) > list:list(int)
tree234:tree234(int, float) > tree234:tree234(float, int)
tree234:tree234(int, float) = tree234:tree234(int, float)
tree234:tree234(int, float) < tree234:tree234(int, int)
tree234:tree234(int, int) > func(float) = float
tree234:tree234(int, int) > func(int) = int
tree234:tree234(int, int) > func(int, int) = int
tree234:tree234(int, int) > pred(int)
tree234:tree234(int, int) > pred(int, int)
tree234:tree234(int, int) > {string}
tree234:tree234(int, int) > {string, int, float}
tree234:tree234(int, int) > list:list(float)
tree234:tree234(int, int) > list:list(int)
tree234:tree234(int, int) > tree234:tree234(float, int)
tree234:tree234(int, int) > tree234:tree234(int, float)
tree234:tree234(int, int) = tree234:tree234(int, int)
func/1 = func/1
func/1 < func/2
func/1 < pred/1
func/1 < pred/2
func/1 < {}/1
func/1 < {}/3
func/1 < list:list/1
func/1 < tree234:tree234/2
func/2 > func/1
func/2 = func/2
func/2 < pred/1
func/2 < pred/2
func/2 < {}/1
func/2 < {}/3
func/2 < list:list/1
func/2 < tree234:tree234/2
pred/1 > func/1
pred/1 > func/2
pred/1 = pred/1
pred/1 < pred/2
pred/1 < {}/1
pred/1 < {}/3
pred/1 < list:list/1
pred/1 < tree234:tree234/2
pred/2 > func/1
pred/2 > func/2
pred/2 > pred/1
pred/2 = pred/2
pred/2 < {}/1
pred/2 < {}/3
pred/2 < list:list/1
pred/2 < tree234:tree234/2
{}/1 > func/1
{}/1 > func/2
{}/1 > pred/1
{}/1 > pred/2
{}/1 = {}/1
{}/1 < {}/3
{}/1 < list:list/1
{}/1 < tree234:tree234/2
{}/3 > func/1
{}/3 > func/2
{}/3 > pred/1
{}/3 > pred/2
{}/3 > {}/1
{}/3 = {}/3
{}/3 < list:list/1
{}/3 < tree234:tree234/2
list:list/1 > func/1
list:list/1 > func/2
list:list/1 > pred/1
list:list/1 > pred/2
list:list/1 > {}/1
list:list/1 > {}/3
list:list/1 = list:list/1
list:list/1 < tree234:tree234/2
tree234:tree234/2 > func/1
tree234:tree234/2 > func/2
tree234:tree234/2 > pred/1
tree234:tree234/2 > pred/2
tree234:tree234/2 > {}/1
tree234:tree234/2 > {}/3
tree234:tree234/2 > list:list/1
tree234:tree234/2 = tree234:tree234/2
