********************
** Standard input **
********************

read_char:
ok('啕')

putback_char:
ok('啕')

read_word:
ok(['a', 'ß', 'ξ', '啕', '𐀀', '.'])
ok(['☿', '.'])

read_line:
ok(['a', 'ß', 'ξ', '啕', '𐀀', '.', ' ', '☿', '.', '\n'])

read_line_as_string:
ok("aßξ啕𐀀. ☿.\n")

write_char:
ßξ啕

format:
ß.ξ.啕
<  ß><  ξ><啕  >
<  aß><ξ   >

read_file_as_string:
ok("aßξ啕𐀀. ☿.\naßξ啕𐀀. ☿.\n")

***********************
** Text stream input **
***********************

read_char:
ok('啕')

putback_char:
ok('啕')

read_word:
ok(['a', 'ß', 'ξ', '啕', '𐀀', '.'])
ok(['☿', '.'])

read_line:
ok(['a', 'ß', 'ξ', '啕', '𐀀', '.', ' ', '☿', '.', '\n'])

read_line_as_string:
ok("aßξ啕𐀀. ☿.\n")

write_char:
ßξ啕

format:
ß.ξ.啕
<  ß><  ξ><啕  >
<  aß><ξ   >

read_file_as_string:
ok("aßξ啕𐀀. ☿.\naßξ啕𐀀. ☿.\n")
