       1:      1  1 CALL pred all_solutions.main/2-0 (det) all_solutions.m:26
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break hello
 0: + stop  interface pred all_solutions.hello/1-0 (multi)
mdb> continue
       2:      2  2 CALL pred all_solutions.hello/1-0 (multi)
mdb> stack
   0       pred all_solutions.hello/1-0 (multi)
reached unknown label.
mdb> retry 1
cannot retry across non-debuggable region
mdb> retry 2
cannot retry across non-debuggable region
mdb> retry 3
cannot retry across non-debuggable region
mdb> continue -n -S
Hello again, world
Hello, world
