       1:      1  1 CALL pred breakpoints:main/2-0 (cc_multi) 
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break data
 0: + stop  interface pred breakpoints:data/1-0 (det)
mdb> continue
       2:      2  2 CALL pred breakpoints:data/1-0 (det) 
mdb> disable 0
 0: - stop  interface pred breakpoints:data/1-0 (det)
mdb> break info
 0: - stop  interface pred breakpoints:data/1-0 (det)
mdb> break qperm
 1: + stop  interface pred breakpoints:qperm/2-0 (nondet)
mdb> break safe
 2: + stop  interface pred breakpoints:safe/1-0 (semidet)
mdb> break -e qperm
 3: + stop      entry pred breakpoints:qperm/2-0 (nondet)
mdb> break -a qperm
 4: + stop        all pred breakpoints:qperm/2-0 (nondet)
mdb> break info
 0: - stop  interface pred breakpoints:data/1-0 (det)
 1: + stop  interface pred breakpoints:qperm/2-0 (nondet)
 2: + stop  interface pred breakpoints:safe/1-0 (semidet)
 3: + stop      entry pred breakpoints:qperm/2-0 (nondet)
 4: + stop        all pred breakpoints:qperm/2-0 (nondet)
mdb> delete 0
 0: D stop  interface pred breakpoints:data/1-0 (det)
mdb> break info
 1: + stop  interface pred breakpoints:qperm/2-0 (nondet)
 2: + stop  interface pred breakpoints:safe/1-0 (semidet)
 3: + stop      entry pred breakpoints:qperm/2-0 (nondet)
 4: + stop        all pred breakpoints:qperm/2-0 (nondet)
mdb> disable 3
 3: - stop      entry pred breakpoints:qperm/2-0 (nondet)
mdb> break nodiag
 0: + stop  interface pred breakpoints:nodiag/3-0 (semidet)
mdb> continue
       5:      4  3 CALL pred breakpoints:qperm/2-0 (nondet) 
mdb> continue
       6:      4  3 SWTC pred breakpoints:qperm/2-0 (nondet) s1;
mdb> finish -N
      10:      6  4 CALL pred breakpoints:qperm/2-0 (nondet) 
mdb> finish -n
      36:      6  4 EXIT pred breakpoints:qperm/2-0 (nondet) 
mdb> continue
      37:      4  3 EXIT pred breakpoints:qperm/2-0 (nondet) 
mdb> continue
      38:     15  3 CALL pred breakpoints:safe/1-0 (semidet) 
mdb> finish
      40:     16  4 CALL pred breakpoints:nodiag/3-0 (semidet) 
      44:     15  3 FAIL pred breakpoints:safe/1-0 (semidet) 
mdb> delete *
 0: E stop  interface pred breakpoints:nodiag/3-0 (semidet)
 1: E stop  interface pred breakpoints:qperm/2-0 (nondet)
 2: E stop  interface pred breakpoints:safe/1-0 (semidet)
 3: D stop      entry pred breakpoints:qperm/2-0 (nondet)
 4: E stop        all pred breakpoints:qperm/2-0 (nondet)
mdb> break info
There are no break points.
mdb> delete *
There are no break points.
mdb> continue
[1, 3, 5, 2, 4]
