       1:      1  1 CALL pred browser_test:main/2-0 (det) browser_test.m:11
mdb> echo on
Command echo enabled.
mdb> goto 3
       3:      2  2 EXIT pred browser_test:big_data/1-0 (det) browser_test.m:18 (browser_test.m:12)
mdb> set format pretty
mdb> print *
       HeadVar__1             	
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big/3), 6, small))
mdb> set -A format verbose
mdb> print *
       HeadVar__1             	
big
1-big
| 1-big
| | 1-small
| | 2-1

mdb> browse 1; ls; quit
big(
  big(big(small, 1, small), 2, small), 
  3, 
  big(big(small, 4, big(small, 5, small)), 6, small))
mdb> set -AP format flat
mdb> print -f 1
       HeadVar__1             	big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big/3), 6, small))
mdb> print -r 1
       HeadVar__1             	
big(big(big(...), ...), 3, ...)
mdb> print -v 1
       HeadVar__1             	
big
1-big
| 1-big
| | 1-small
| | 2-1
| | 3-small
| 2-2
| 3-small
2-3
3-big
  1-big
  | 1-small
  | 2-4
  | 3-big/3
  2-6
  3-small

mdb> print -p 1
       HeadVar__1             	
big(
  big(big(small, 1, small), 2, small), 
  3, 
  big(big(small, 4, big(small, 5, small)), 6, small))
mdb> print --xyzzy 1
print: unrecognized option `--xyzzy'
mdb: print: usage error -- type `help print' for help.
mdb> browse 1; print; quit
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big/3), 6, small))
mdb> browse -f 1; ls; quit
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big(small, 5, small)), 6, small))
mdb> browse HeadVar__1
browser> ls
big(
  big(big(small, 1, small), 2, small), 
  3, 
  big(big(small, 4, big(small, 5, small)), 6, small))
browser> cd /1
browser> ls
big(big(small, 1, small), 2, small)
browser> cd /1/2
browser> ls
2
browser> cd /3
browser> ls
big(big(small, 4, big(small, 5, small)), 6, small)
browser> cd 1/3/2
browser> ls
5
browser> cd
browser> ls
big(
  big(big(small, 1, small), 2, small), 
  3, 
  big(big(small, 4, big(small, 5, small)), 6, small))
browser> quit
mdb> set -A -f depth 1
mdb> print *
       HeadVar__1             	big(big/3, 3, big/3)
mdb> print HeadVar__1/1
       HeadVar__1             	big(big(small, 1, small), 2, small)
mdb> set -f depth 3
mdb> print 1
       HeadVar__1             	big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big/3), 6, small))
mdb> print HeadVar__1/1/2
       HeadVar__1             	2
mdb> print 1^1^2^3
mdb: the path 3 does not exist.
mdb> retry
       2:      2  2 CALL pred browser_test:big_data/1-0 (det) browser_test.m:18 (browser_test.m:12)
mdb> continue -a
       3:      2  2 EXIT pred browser_test:big_data/1-0 (det) browser_test.m:18 (browser_test.m:12)
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big(small, 5, small)), 6, small)).
       4:      1  1 EXIT pred browser_test:main/2-0 (det) browser_test.m:11
