       1:      1  1 CALL pred browser_test:main/2-0 (det) 
mdb> echo on
Command echo enabled.
mdb> goto 3
       3:      2  2 EXIT pred browser_test:big_data/1-0 (det) 
mdb> print *
       HeadVar__1             	big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big/3), 6, small))
mdb> browse 1
browser> print
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big/3), 6, small))
browser> quit
mdb> browse HeadVar__1
browser> ls
big
1-big
| 1-big
| | 1-small
| | 2-1
| | 3-small
| 2-2
| 3-small
2-3
3-big
  1-big
  | 1-small
  | 2-4
  | 3-big/3
  2-6
  3-small

browser> cd /1
browser> ls
big
1-big
| 1-small
| 2-1
| 3-small
2-2
3-small

browser> cd /1/2
browser> ls
2

browser> cd /3
browser> ls
big
1-big
| 1-small
| 2-4
| 3-big
|   1-small
|   2-5
|   3-small
2-6
3-small

browser> cd 1/3/2
browser> ls
5

browser> cd
browser> ls
big
1-big
| 1-big
| | 1-small
| | 2-1
| | 3-small
| 2-2
| 3-small
2-3
3-big
  1-big
  | 1-small
  | 2-4
  | 3-big/3
  2-6
  3-small

browser> quit
mdb> retry
       2:      2  2 CALL pred browser_test:big_data/1-0 (det) 
mdb> continue -a
       3:      2  2 EXIT pred browser_test:big_data/1-0 (det) 
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big(small, 5, small)), 6, small)).
       4:      1  1 EXIT pred browser_test:main/2-0 (det) 
