       1:      1  1 CALL pred completion.main/2-0 (det) completion.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> 
?                    enable               procedures
P                    exception            query
alias                excp                 quit
all_class_decls      f                    r
all_procedures       finish               register
all_regs             flag                 retry
all_type_ctors       forward              return
b                    g                    s
break                gen_stack            save
break_print          goal_paths           save_to_file
browse               goto                 scope
c                    h                    scroll
cc_query             held_vars            set
class_decl           help                 source
clear_histogram      histogram_all        stack
condition            histogram_exp        stack_default_limit
consumer             hold                 stack_regs
context              ignore               step
continue             io_query             subgoal
current              label_stats          table
cut_stack            level                table_io
d                    maxdepth             term_size
dd                   mindepth             trust
dd_dd                mm_stacks            trusted
debug_vars           mmc_options          type_ctor
delete               modules              unalias
dice                 next                 unhide_events
diff                 nondet_stack         untrust
disable              p                    up
document             pneg_stack           v
document_category    print                var_details
down                 print_optionals      var_name_stats
e                    printlevel           vars
echo                 proc_stats           view
h              help           histogram_exp  
held_vars      histogram_all  hold           
var_details     var_name_stats  vars            view
var_details     var_name_stats  vars            
 help vars 
vars
     Prints the names of all the known variables in the current
     environment, together with an ordinal number for each variable.
mdb> 
*          --pretty   -f         -v         goal       
--flat     --verbose  -p         exception  
p --flat D
mdb: there is no such variable.
mdb> 
stack                stack_default_limit  stack_regs
stack --detailed 
   0       1       1    1 pred completion.main/2-0 (det) (completion.m:13) (empty)
mdb> 
proc_stats  procedures  
completion            completion.sub2       
completion.sub1       completion.sub2.sub3  
completion.sub1       completion.sub2       completion.sub2.sub3
procedures completion.sub1
List of procedures in module `completion.sub1'
pred completion.sub1.zp/1-0 (det)
func completion.sub1.z1/0-0 (det)
mdb> set --flat format pretty 
mdb> unalias excp 
Alias `excp' removed.
mdb> b zabc3 
 0: + stop  interface func completion.sub2.sub3.zabc3/0-0 (det)
mdb> 
func*completion.            func*completion.sub2.
func*completion.sub1.       func*completion.sub2.sub3.
func*completion.z   func*completion.zz  
b func*completion.z
 1: + stop  interface func completion.z/0-0 (det)
mdb> 
completion.            completion.sub2.       
completion.sub1.       completion.sub2.sub3.  
completion.sub1.       completion.sub2.       completion.sub2.sub3.
completion.sub1.z1  completion.sub1.zp  
b completion.sub1.z1
 2: + stop  interface func completion.sub1.z1/0-0 (det)
mdb> 
completion.            completion.sub2.       
completion.sub1.       completion.sub2.sub3.  
completion.sub1.       completion.sub2.       completion.sub2.sub3.
completion.sub2.       completion.sub2.sub3.  
b completion.sub2.sub3.zabc3 
 3: + stop  interface func completion.sub2.sub3.zabc3/0-0 (det)
mdb> 
2d                  2delete             2document
2dd                 2dice               2document_category
2dd_dd              2diff               2down
2debug_vars         2disable            
2debug_vars  2delete      
2delete 
 2: E stop  interface func completion.sub1.z1/0-0 (det)
mdb> c
ok
