       1:      1  1 CALL pred completion.main/2-0 (det) completion.m:13
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> 
?                  document_category  level              save
P                  down               maxdepth           scope
alias              e                  mindepth           scroll
all_regs           echo               mmc_options        set
b                  enable             modules            source
break              exception          next               stack
browse             excp               nondet_stack       stack_regs
c                  f                  p                  step
cc_query           finish             pneg_stack         subgoal
clear_histogram    flag               print              table
consumer           forward            print_optionals    table_io
context            g                  printlevel         term_size
continue           gen_stack          proc_stats         unalias
current            goto               procedures         unhide_events
cut_stack          h                  query              up
d                  help               quit               v
dd                 histogram_all      r                  vars
dd_dd              histogram_exp      register           view
delete             ignore             retry              
disable            io_query           return             
document           label_stats        s                  
h              help           histogram_all  histogram_exp  
vars  view  
help vars 
vars
     Prints the names of all the known variables in the current
     environment, together with an ordinal number for each variable.
mdb> 
*          --pretty   -f         -v         exception  
--flat     --verbose  -p         DCG_0      goal       
p --flat DCG_0 
       DCG_0 (arg 1)          	state('<<c_pointer>>')
mdb> 
stack       stack_regs  
stack --detailed 
   0       1       1    1 pred completion.main/2-0 (det) (completion.m:13) (empty)
mdb> 
proc_stats  procedures  
completion            completion.sub2       
completion.sub1       completion.sub2.sub3  
completion.sub1       completion.sub2       completion.sub2.sub3
procedures completion.sub1
List of procedures in module `completion.sub1'
pred completion.sub1.zp/1-0 (det)
func completion.sub1.z1/0-0 (det)
mdb> set --flat format pretty 
mdb> unalias excp 
Alias `excp' removed.
mdb> b zabc3 
 0: + stop  interface func completion.sub2.sub3.zabc3/0-0 (det)
mdb> 
func*completion.            func*completion.sub2.
func*completion.sub1.       func*completion.sub2.sub3.
func*completion.z   func*completion.zz  
b func*completion.z
 1: + stop  interface func completion.z/0-0 (det)
mdb> 
completion.            completion.sub2.       
completion.sub1.       completion.sub2.sub3.  
completion.sub1.       completion.sub2.       completion.sub2.sub3.
completion.sub1.z1  completion.sub1.zp  
b completion.sub1.z1
 2: + stop  interface func completion.sub1.z1/0-0 (det)
mdb> 
completion.            completion.sub2.       
completion.sub1.       completion.sub2.sub3.  
completion.sub1.       completion.sub2.       completion.sub2.sub3.
completion.sub2.       completion.sub2.sub3.  
b completion.sub2.sub3.zabc3 
 3: + stop  interface func completion.sub2.sub3.zabc3/0-0 (det)
mdb> 
2d                  2delete             2document_category
2dd                 2disable            2down
2dd_dd              2document           
2delete 
 2: E stop  interface func completion.sub1.z1/0-0 (det)
mdb> c
ok
