       1:      1  1 CALL pred debugger_regs.main/2-0 (det) debugger_regs.m:19
mdb> echo on
Command echo enabled.
mdb> 
       2:      2  2 CALL pred debugger_regs.data/41-0 (det) debugger_regs.m:88 (debugger_regs.m:28)
mdb> 
       3:      2  2 EXIT pred debugger_regs.data/41-0 (det) debugger_regs.m:88 (debugger_regs.m:28)
mdb> print NoSuchVar
mdb: there is no such variable.
mdb> print *
       HeadVar__1             	[1, 2, 3, 4, 5]
       HeadVar__2             	"a0"
       HeadVar__3             	"a1"
       HeadVar__4             	"a2"
       HeadVar__5             	"a3"
       HeadVar__6             	"a4"
       HeadVar__7             	"a5"
       HeadVar__8             	"a6"
       HeadVar__9             	"a7"
       HeadVar__10            	"a8"
       HeadVar__11            	"a9"
       HeadVar__12            	"b0"
       HeadVar__13            	"b1"
       HeadVar__14            	"b2"
       HeadVar__15            	"b3"
       HeadVar__16            	"b4"
       HeadVar__17            	"b5"
       HeadVar__18            	"b6"
       HeadVar__19            	"b7"
       HeadVar__20            	"b8"
       HeadVar__21            	"b9"
       HeadVar__22            	"c0"
       HeadVar__23            	"c1"
       HeadVar__24            	"c2"
       HeadVar__25            	"c3"
       HeadVar__26            	"c4"
       HeadVar__27            	"c5"
       HeadVar__28            	"c6"
       HeadVar__29            	"c7"
       HeadVar__30            	"c8"
       HeadVar__31            	"c9"
       HeadVar__32            	"d0"
       HeadVar__33            	"d1"
       HeadVar__34            	"d2"
       HeadVar__35            	"d3"
       HeadVar__36            	"d4"
       HeadVar__37            	"d5"
       HeadVar__38            	"d6"
       HeadVar__39            	"d7"
       HeadVar__40            	"d8"
       HeadVar__41            	"d9"
mdb> continue
a0a1a2a3a4a5a6a7a8a9
b0b1b2b3b4b5b6b7b8b9
c0c1c2c3c4c5c6c7c8c9
d0d1d2d3d4d5d6d7d8d9
