      E1:     C1 CALL pred dice.main/2-0 (det) dice.m:32
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> dice -f dice.fail -p dice.passes -m dice
Procedure                Path/Port            File:Line Pass (3) Fail Suspicion
pred dice.main/2-0       CALL                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       EXIT                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       <c2;?;>              dice.m:34    3 (3)    1      0.25
pred dice.main/2-0       <c2;t;>              dice.m:35    3 (3)    1      0.25
pred dice.merge/3-0      CALL                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      EXIT                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      <s1-2;>              dice.m:73    8 (3)    3      0.27
pred dice.merge/3-0      <s1-2;s2-2;>         dice.m:75    8 (3)    3      0.27
pred dice.merge/3-0      <s2-2;>              dice.m:74   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;>      dice.m:76   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;?;> dice.m:77   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;t;> dice.m:78   10 (3)    3      0.23
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;e;> dice.m:81    0 (0)    1      1.00
pred dice.merge_sort/2-0 CALL                 dice.m:44    3 (3)    1      0.25
pred dice.merge_sort/2-0 EXIT                 dice.m:44    3 (3)    1      0.25
pred dice.msort_n/4-0    CALL                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    EXIT                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    <?;>                 dice.m:51   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;>                 dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;?;>               dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;t;>               dice.m:59   11 (3)    4      0.27
pred dice.msort_n/4-0    <e;t;s2-2;>          dice.m:56   11 (3)    4      0.27
pred dice.msort_n/4-0    <e;e;>               dice.m:64    8 (3)    3      0.27
mdb> fail_trace_counts dice.fail
mdb> pass_trace_counts dice.passes
mdb> dice -sS -m dice
Procedure                Path/Port            File:Line Pass (3) Fail Suspicion
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;e;> dice.m:81    0 (0)    1      1.00
pred dice.merge/3-0      <s2-2;>              dice.m:74   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;>      dice.m:76   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;?;> dice.m:77   10 (3)    4      0.29
pred dice.merge/3-0      CALL                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      EXIT                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      <s1-2;>              dice.m:73    8 (3)    3      0.27
pred dice.merge/3-0      <s1-2;s2-2;>         dice.m:75    8 (3)    3      0.27
pred dice.msort_n/4-0    <e;e;>               dice.m:64    8 (3)    3      0.27
pred dice.msort_n/4-0    CALL                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    EXIT                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    <?;>                 dice.m:51   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;>                 dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;?;>               dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;t;>               dice.m:59   11 (3)    4      0.27
pred dice.msort_n/4-0    <e;t;s2-2;>          dice.m:56   11 (3)    4      0.27
pred dice.main/2-0       CALL                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       EXIT                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       <c2;?;>              dice.m:34    3 (3)    1      0.25
pred dice.main/2-0       <c2;t;>              dice.m:35    3 (3)    1      0.25
pred dice.merge_sort/2-0 CALL                 dice.m:44    3 (3)    1      0.25
pred dice.merge_sort/2-0 EXIT                 dice.m:44    3 (3)    1      0.25
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;t;> dice.m:78   10 (3)    3      0.23
mdb> dice -sSF -m dice
Procedure                Path/Port            File:Line Pass (3) Fail Suspicion
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;e;> dice.m:81    0 (0)    1      1.00
pred dice.merge/3-0      <s2-2;>              dice.m:74   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;>      dice.m:76   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;?;> dice.m:77   10 (3)    4      0.29
pred dice.merge/3-0      CALL                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      EXIT                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      <s1-2;>              dice.m:73    8 (3)    3      0.27
pred dice.merge/3-0      <s1-2;s2-2;>         dice.m:75    8 (3)    3      0.27
pred dice.msort_n/4-0    <e;e;>               dice.m:64    8 (3)    3      0.27
pred dice.msort_n/4-0    CALL                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    EXIT                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    <?;>                 dice.m:51   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;>                 dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;?;>               dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;t;>               dice.m:59   11 (3)    4      0.27
pred dice.msort_n/4-0    <e;t;s2-2;>          dice.m:56   11 (3)    4      0.27
pred dice.main/2-0       CALL                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       EXIT                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       <c2;?;>              dice.m:34    3 (3)    1      0.25
pred dice.main/2-0       <c2;t;>              dice.m:35    3 (3)    1      0.25
pred dice.merge_sort/2-0 CALL                 dice.m:44    3 (3)    1      0.25
pred dice.merge_sort/2-0 EXIT                 dice.m:44    3 (3)    1      0.25
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;t;> dice.m:78   10 (3)    3      0.23
mdb> dice -n 3 -s P -m dice
Procedure             Path/Port File:Line Pass (3) Fail Suspicion
pred dice.msort_n/4-0 CALL      dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0 EXIT      dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0 <?;>      dice.m:51   19 (3)    7      0.27
mdb> dice -s Fp -m dice
Procedure                Path/Port            File:Line Pass (3) Fail Suspicion
pred dice.merge/3-0      CALL                 dice.m:73   18 (3)    7      0.28
pred dice.merge/3-0      EXIT                 dice.m:73   18 (3)    7      0.28
pred dice.msort_n/4-0    CALL                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    EXIT                 dice.m:50   19 (3)    7      0.27
pred dice.msort_n/4-0    <?;>                 dice.m:51   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;>                 dice.m:54   19 (3)    7      0.27
pred dice.msort_n/4-0    <e;?;>               dice.m:54   19 (3)    7      0.27
pred dice.merge/3-0      <s2-2;>              dice.m:74   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;>      dice.m:76   10 (3)    4      0.29
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;?;> dice.m:77   10 (3)    4      0.29
pred dice.msort_n/4-0    <e;t;>               dice.m:59   11 (3)    4      0.27
pred dice.msort_n/4-0    <e;t;s2-2;>          dice.m:56   11 (3)    4      0.27
pred dice.merge/3-0      <s1-2;>              dice.m:73    8 (3)    3      0.27
pred dice.merge/3-0      <s1-2;s2-2;>         dice.m:75    8 (3)    3      0.27
pred dice.msort_n/4-0    <e;e;>               dice.m:64    8 (3)    3      0.27
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;t;> dice.m:78   10 (3)    3      0.23
pred dice.merge/3-0      <s2-2;c2;s2-2;c4;e;> dice.m:81    0 (0)    1      1.00
pred dice.main/2-0       CALL                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       EXIT                 dice.m:32    3 (3)    1      0.25
pred dice.main/2-0       <c2;?;>              dice.m:34    3 (3)    1      0.25
pred dice.main/2-0       <c2;t;>              dice.m:35    3 (3)    1      0.25
pred dice.merge_sort/2-0 CALL                 dice.m:44    3 (3)    1      0.25
pred dice.merge_sort/2-0 EXIT                 dice.m:44    3 (3)    1      0.25
mdb> dice -sS -n 1 --module dice
Procedure           Path/Port            File:Line Pass (3) Fail Suspicion
pred dice.merge/3-0 <s2-2;c2;s2-2;c4;e;> dice.m:81    0 (0)    1      1.00
mdb> break dice.m:81
 0: + stop  linenumber dice.m:81
mdb> c
      E2:     C2 ELSE pred dice.merge/3-0 (det) s2-2;c2;s2-2;c4;e;
mdb> quit -y
