       1:      1  1 CALL pred exception_value:main/2-0 (cc_multi) exception_value.m:12
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break p
 0: + stop  interface pred exception_value:p/1-0 (det)
mdb> break q
 1: + stop  interface pred exception_value:q/1-0 (det)
mdb> continue
       3:      3  3 CALL pred exception_value:p/1-0 (det) exception_value.m:30
mdb> finish
       4:      3  3 EXCP pred exception_value:p/1-0 (det) c3; exception_value.m:31
mdb> print exception
	"p exception"
mdb> continue
mdb: warning: reached unknown label
This may result in some exception events
being omitted from the trace.
exception(univ("p exception" : string))
       7:      5  3 CALL pred exception_value:q/1-0 (det) exception_value.m:35
mdb> finish
       8:      5  3 EXCP pred exception_value:q/1-0 (det) c16; exception_value.m:36
mdb> browse exception
browser> set depth 9
browser> set size 99
browser> ls
-
1-"q oops"
2-.
  1-1
  2-.
    1-2
    2-.
      1-3
      2-[]

browser> quit
mdb> continue
mdb: warning: reached unknown label
This may result in some exception events
being omitted from the trace.
exception(univ("q oops" - [1, 2, 3] : std_util:pair(string, list:list(int))))
