       1:      1  1 CALL pred exported_eqv_type.main/2-0 (det) exported_eqv_type.m:18
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break p
 0: + stop  interface func exported_eqv_type.p/2-0 (det)
mdb> continue
       2:      2  2 CALL func exported_eqv_type.p/2-0 (det)
mdb> finish
       3:      2  2 EXIT func exported_eqv_type.p/2-0 (det)
mdb> print *
       Num (arg 1)            	2
       Item (arg 2)           	55
       Dups (arg 3)           	[55, 55]
mdb> continue
       4:      3  2 CALL func exported_eqv_type.p/2-0 (det)
mdb> finish
       5:      3  2 EXIT func exported_eqv_type.p/2-0 (det)
mdb> print *
       Num (arg 1)            	3
       Item (arg 2)           	"a"
       Dups (arg 3)           	["a", "a", "a"]
mdb> continue -S
[55, 55]
["a", "a", "a"]
