      E1:     C1 CALL pred implied_instance.main/2-0 (det) implied_instance.m:30
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> context none
Contexts will not be printed.
mdb> alias P print *
P      =>    print *
mdb> goto 2
      E2:     C2 CALL pred implied_instance.p/2-0 (det)
mdb> P
       HeadVar__1             	2
mdb> 
      E3:     C3 CALL pred implied_instance.ClassMethod_for_implied_instance__sumable____int__arity0______implied_instance__p_2/2-0 (det)
mdb> P
       HeadVar__1             	2
mdb> break -e p
 0: + stop  entry     pred implied_instance.p/2-0 (det)
mdb> continue -a
      E4:     C4 CALL pred implied_instance.copy_int/2-0 (det)
      E5:     C4 EXIT pred implied_instance.copy_int/2-0 (det)
      E6:     C3 EXIT pred implied_instance.ClassMethod_for_implied_instance__sumable____int__arity0______implied_instance__p_2/2-0 (det)
      E7:     C2 EXIT pred implied_instance.p/2-0 (det)
      E8:     C5 CALL pred implied_instance.p/2-0 (det)
mdb> P
       HeadVar__1             	[42, 24, 1, 2, 3]
mdb> 
      E9:     C6 CALL pred implied_instance.ClassMethod_for_implied_instance__sumable____list__list__arity1______implied_instance__p_2/2-0 (det)
mdb> P
       HeadVar__1             	[42, 24, 1, 2, 3]
mdb> 
     E10:     C7 CALL pred implied_instance.sum_int_list/2-0 (det)
mdb> P
       HeadVar__1             	[42, 24, 1, 2, 3]
mdb> continue -a
     E11:     C7 SWTC pred implied_instance.sum_int_list/2-0 (det) s2-2;
     E12:     C8 CALL pred implied_instance.p/2-0 (det)
mdb> P
       HeadVar__1             	42
mdb> 
     E13:     C9 CALL pred implied_instance.ClassMethod_for_implied_instance__sumable____int__arity0______implied_instance__p_2/2-0 (det)
mdb> P
       HeadVar__1             	42
mdb> continue -S
2
72
