       1:      1  1 CALL DET   interpreter_lib:main/2-0 
mtrace> valid commands are:
a, EOF:			abort the current execution.
b <module> <name>:	set a breakpoint on the predicate
			or function <module>:<name>.
c:			continue to end of program, not printing the trace.
C:			continue to end of program, printing the trace.
f:			finish this call, not printing the trace.
F:			finish this call, printing the trace.
<N> g:			go to event #N, not printing the trace.
<N> G:			go to event #N, printing the trace.
v:			list the names of the variables live at this point.
l <n>:			set ancestor level to <n>
p <n>:			print variable #n (or all vars if <n> is '*')
r:			continue until forward execution is resumed.
[<N>] [s]:		skip N events, not printing the trace (default: N=1).
[<N>] S:		skip N events, printing the trace (default: N=1).
?:			list all the breakpoints.
+ <N>:			enable breakpoint #N.
- <N>:			disable breakpoint #N.
mtrace> Pure Prolog Interpreter.

Consulting file `interpreter_lib.m'...
      46:     21  5 CALL DET   term_io:read_term/3-0 
mtrace>         0 HeadVar__2
mtrace>           HeadVar__2           		state('<<c_pointer>>')
mtrace>  0: + interpreter_lib:database_assert_clause
mtrace>    13446:   5011  6 CALL DET   interpreter_lib:database_assert_clause/4-0 
mtrace>           HeadVar__1           		[]
          HeadVar__2           		varset(0, empty, empty)
          HeadVar__3           		functor(atom(":-"), [functor(atom("module"), [functor(atom("interpreter_lib"), [], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))
mtrace>    13447:   5011  6 ELSE DET   interpreter_lib:database_assert_clause/4-0 e;
   13448:   5012  7 CALL DET   term:context_init/1-0 
   13449:   5012  7 EXIT DET   term:context_init/1-0 
   13450:   5011  6 EXIT DET   interpreter_lib:database_assert_clause/4-0 
mtrace>           HeadVar__1           		[]
          HeadVar__2           		varset(0, empty, empty)
          HeadVar__3           		functor(atom(":-"), [functor(atom("module"), [functor(atom("interpreter_lib"), [], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))
          HeadVar__4           		[clause(varset(0, empty, empty), functor(atom(":-"), [functor(atom("module"), [functor(atom("interpreter_lib"), [], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22)), functor(atom("true"), [], context("", 0)))]
mtrace>    13451:   5013  6 CALL DET   interpreter_lib:consult_until_eof/4-0 
mtrace>   368828:   5013  6 EXIT DET   interpreter_lib:consult_until_eof/4-0 
mtrace>   368829:   5010  5 EXIT DET   interpreter_lib:consult_until_eof_2/5-0 
mtrace>   368830:     20  4 EXIT DET   interpreter_lib:consult_until_eof/4-0 
mtrace> ?- 