Melbourne Mercury Debugger, mdb version 0.8.
Copyright 1998 University of Melbourne, Australia.
mdb is free software, covered by the GNU General Public License.
There is absolutely no warranty for mdb.
       1:      1  1 CALL pred interpreter_lib:main/2-0 (det) 
mdb> Command echo enabled
mdb> 45step
Pure Prolog Interpreter.

Consulting file `interpreter_lib.m'...
      46:     21  5 CALL pred term_io:read_term/3-0 (det) 
mdb> vars
        0 HeadVar__2
mdb> print *
       HeadVar__2           		state('<<c_pointer>>')
mdb> break database_assert_clause
Registering all debuggable procedures... done
 0: + stop  interface pred interpreter_lib:database_assert_clause/4-0 (det)
mdb> continue
   13446:   5011  6 CALL pred interpreter_lib:database_assert_clause/4-0 (det) 
mdb> print *
       HeadVar__1           		[]
       HeadVar__2           		varset(0, empty, empty)
       HeadVar__3           		functor(atom(":-"), [functor(atom("module"), [functor(atom("interpreter_lib"), [], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))
mdb> finish -a
   13447:   5011  6 ELSE pred interpreter_lib:database_assert_clause/4-0 (det) e;
   13448:   5012  7 CALL pred term:context_init/1-0 (det) 
   13449:   5012  7 EXIT pred term:context_init/1-0 (det) 
   13450:   5011  6 EXIT pred interpreter_lib:database_assert_clause/4-0 (det) 
mdb> print *
       HeadVar__1           		[]
       HeadVar__2           		varset(0, empty, empty)
       HeadVar__3           		functor(atom(":-"), [functor(atom("module"), [functor(atom("interpreter_lib"), [], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))
       HeadVar__4           		[clause(varset(0, empty, empty), functor(atom(":-"), [functor(atom("module"), [functor(atom("interpreter_lib"), [], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22))], context("interpreter_lib.m", 22)), functor(atom("true"), [], context("", 0)))]
mdb> 
   13451:   5013  6 CALL pred interpreter_lib:consult_until_eof/4-0 (det) 
mdb> finish -n
  368828:   5013  6 EXIT pred interpreter_lib:consult_until_eof/4-0 (det) 
mdb> 
  368829:   5010  5 EXIT pred interpreter_lib:consult_until_eof_2/5-0 (det) 
mdb> 
  368830:     20  4 EXIT pred interpreter_lib:consult_until_eof/4-0 (det) 
mdb> continue -S
?- 