      E1:     C1 CALL pred label_layout.main/2-0 (det) label_layout.m:12
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred label_layout.a/2-0 (det)
mdb> continue
      E2:     C2 CALL pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:15)
mdb> finish
      E3:     C2 EXIT pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:15)
mdb> continue
      E4:     C3 CALL pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:17)
mdb> finish
      E5:     C3 EXIT pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:17)
mdb> quit -y
