       1:      1  1 CALL pred label_layout.main/2-0 (det) label_layout.m:12
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> break a
 0: + stop  interface pred label_layout.a/2-0 (det)
mdb> continue
       4:      2  2 CALL pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:15)
mdb> finish
       5:      2  2 EXIT pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:15)
mdb> continue
       7:      3  2 CALL pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:17)
mdb> finish
       8:      3  2 EXIT pred label_layout.a/2-0 (det) label_layout.m:28 (label_layout.m:17)
mdb> quit -y
