      E1:     C1  1 CALL pred lambda_expr.main/2-0 (det) lambda_expr.m:17
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> step
      E2:     C2  2 CALL pred lambda_expr.IntroducedFrom__pred__main__18__1/2-0 (det)
mdb> print
IntroducedFrom__pred__main__18__1(1, _)
mdb> up
Ancestor level set to 1:
   1  pred lambda_expr.main/2-0 (det)
mdb> print P
       P                      	'IntroducedFrom__pred__main__18__1'
mdb> finish ; print
      E3:     C2  2 EXIT pred lambda_expr.IntroducedFrom__pred__main__18__1/2-0 (det)
IntroducedFrom__pred__main__18__1(1, 2)
mdb> retry
      E2:     C2  2 CALL pred lambda_expr.IntroducedFrom__pred__main__18__1/2-0 (det)
mdb> print
IntroducedFrom__pred__main__18__1(1, _)
mdb> finish
      E3:     C2  2 EXIT pred lambda_expr.IntroducedFrom__pred__main__18__1/2-0 (det)
mdb> print
IntroducedFrom__pred__main__18__1(1, 2)
mdb> continue
2
