      E1:     C1 CALL pred lambda_expr.main/2-0 (det) lambda_expr.m:17
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> step
      E2:     C2 CALL pred lambda_expr.lambda_lambda_expr_18/2-0 (det)
mdb> print
lambda_lambda_expr_18(1, _)
mdb> up
Ancestor level set to 1:
   1  pred lambda_expr.main/2-0 (det)
mdb> print P
       P                      	lambda_lambda_expr_18
mdb> finish ; print
      E3:     C2 EXIT pred lambda_expr.lambda_lambda_expr_18/2-0 (det)
lambda_lambda_expr_18(1, 2)
mdb> retry
      E2:     C2 CALL pred lambda_expr.lambda_lambda_expr_18/2-0 (det)
mdb> print
lambda_lambda_expr_18(1, _)
mdb> finish
      E3:     C2 EXIT pred lambda_expr.lambda_lambda_expr_18/2-0 (det)
mdb> print
lambda_lambda_expr_18(1, 2)
mdb> continue
2
