       1:      1  1 CALL pred loopcheck:main/2-0 (det) loopcheck.m:13
mdb> echo on
Command echo enabled.
mdb> context nextline
Contexts will be printed on the next line.
mdb> continue -a
       2:      2  2 CALL pred loopcheck:loop/1-0 (erroneous)
                         loopcheck.m:21 (from loopcheck.m:14)
       3:      2  2 ELSE pred loopcheck:loop/1-0 (erroneous) c2;e;
                         loopcheck.m:21
       4:      2  2 ELSE pred loopcheck:loop/1-0 (erroneous) c2;e;e;
                         loopcheck.m:21
       5:      3  3 CALL pred loopcheck:loop/1-0 (erroneous)
                         loopcheck.m:21 (from loopcheck.m:21)
       6:      3  3 ELSE pred loopcheck:loop/1-0 (erroneous) c2;e;
                         loopcheck.m:21
       7:      3  3 THEN pred loopcheck:loop/1-0 (erroneous) c2;e;t;
                         loopcheck.m:21
       8:      3  3 EXCP pred loopcheck:loop/1-0 (erroneous)
                         loopcheck.m:21 (from loopcheck.m:21)
       9:      2  2 EXCP pred loopcheck:loop/1-0 (erroneous)
                         loopcheck.m:21 (from loopcheck.m:14)
      10:      1  1 EXCP pred loopcheck:main/2-0 (det)
                         loopcheck.m:14
Uncaught Mercury exception:
Software Error: detected infinite recursion in pred loopcheck:loop/1
Last trace event was event #10.
Last trace event before the unhandled exception was event #7.
