       1:      1  1 CALL pred no_inline_builtins.main/2-0 (det) no_inline_builtins.m:11
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break int.+/2-0
 0: + stop  interface func int.+/2-0 (det)
mdb> continue
       2:      2  2 CALL func int.+/2-0 (det)
mdb> print 1
       HeadVar__1             	40
mdb> print 2
       HeadVar__2             	2
mdb> continue
       3:      2  2 EXIT func int.+/2-0 (det)
mdb> continue -n
42
