      E1:     C1 CALL pred no_inline_builtins.main/2-0 (det) no_inline_builtins.m:15
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break int.+/2-0
 0: + stop  interface func int.+/2-0 (det)
mdb> continue
      E2:     C2 CALL func int.+/2-0 (det)
mdb> print 1
       HeadVar__1             	40
mdb> print 2
       HeadVar__2             	2
mdb> continue
      E3:     C2 EXIT func int.+/2-0 (det)
mdb> continue -n
42
