       1:      1  1 CALL pred output_term_dep.main/2-0 (det) output_term_dep.m:9
mdb> echo on
Command echo enabled.
mdb> scroll off
Scroll control disabled.
mdb> continue -a
       2:      2  2 CALL pred output_term_dep.test1/2-0 (det) output_term_dep.m:22 (output_term_dep.m:13)
       3:      3  3 CALL pred output_term_dep.p/3-0 (det) output_term_dep.m:34 (output_term_dep.m:23)
       4:      4  4 CALL pred output_term_dep.pa/1-0 (det) output_term_dep.m:42 (output_term_dep.m:35)
       5:      4  4 EXIT pred output_term_dep.pa/1-0 (det) output_term_dep.m:42 (output_term_dep.m:35)
       6:      5  4 CALL pred output_term_dep.pb/1-0 (det) output_term_dep.m:47 (output_term_dep.m:36)
       7:      5  4 EXIT pred output_term_dep.pb/1-0 (det) output_term_dep.m:47 (output_term_dep.m:36)
       8:      6  4 CALL pred output_term_dep.pc/1-0 (det) output_term_dep.m:52 (output_term_dep.m:37)
       9:      6  4 EXIT pred output_term_dep.pc/1-0 (det) output_term_dep.m:52 (output_term_dep.m:37)
      10:      3  3 EXIT pred output_term_dep.p/3-0 (det) output_term_dep.m:34 (output_term_dep.m:23)
5
8
13
      11:      2  2 EXIT pred output_term_dep.test1/2-0 (det) output_term_dep.m:22 (output_term_dep.m:13)
      12:      7  2 CALL pred output_term_dep.test2/2-0 (det) output_term_dep.m:57 (output_term_dep.m:14)
      13:      8  3 CALL pred output_term_dep.q/1-0 (det) output_term_dep.m:65 (output_term_dep.m:58)
      14:      9  4 CALL pred output_term_dep.qa/1-0 (det) output_term_dep.m:73 (output_term_dep.m:66)
      15:      9  4 EXIT pred output_term_dep.qa/1-0 (det) output_term_dep.m:73 (output_term_dep.m:66)
      16:     10  4 CALL pred output_term_dep.qb/1-0 (det) output_term_dep.m:78 (output_term_dep.m:67)
      17:     10  4 EXIT pred output_term_dep.qb/1-0 (det) output_term_dep.m:78 (output_term_dep.m:67)
      18:     11  4 CALL pred output_term_dep.qc/1-0 (det) output_term_dep.m:83 (output_term_dep.m:68)
      19:     11  4 EXIT pred output_term_dep.qc/1-0 (det) output_term_dep.m:83 (output_term_dep.m:68)
      20:      8  3 EXIT pred output_term_dep.q/1-0 (det) output_term_dep.m:65 (output_term_dep.m:58)
[[1, 2, 3], [], [99]]
      21:      7  2 EXIT pred output_term_dep.test2/2-0 (det) output_term_dep.m:57 (output_term_dep.m:14)
      22:     12  2 CALL pred output_term_dep.test3/2-0 (det) output_term_dep.m:88 (output_term_dep.m:15)
      23:     13  3 CALL pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:89)
      24:     13  3 THEN pred output_term_dep.r/2-0 (det) t; output_term_dep.m:109
      25:     13  3 EXIT pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:89)
999
      26:     14  3 CALL pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:92)
      27:     14  3 ELSE pred output_term_dep.r/2-0 (det) e; output_term_dep.m:120
      28:     15  4 CALL pred output_term_dep.ra/1-0 (semidet) output_term_dep.m:127 (output_term_dep.m:111)
      29:     15  4 SWTC pred output_term_dep.ra/1-0 (semidet) s1; output_term_dep.m:127
      30:     15  4 EXIT pred output_term_dep.ra/1-0 (semidet) output_term_dep.m:127 (output_term_dep.m:111)
      31:     14  3 THEN pred output_term_dep.r/2-0 (det) e;t; output_term_dep.m:117
      32:     16  4 CALL pred output_term_dep.rb/1-0 (semidet) output_term_dep.m:133 (output_term_dep.m:114)
      33:     16  4 FAIL pred output_term_dep.rb/1-0 (semidet) output_term_dep.m:133 (output_term_dep.m:114)
      34:     14  3 ELSE pred output_term_dep.r/2-0 (det) e;t;e; output_term_dep.m:118
      35:     14  3 EXIT pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:92)
43
      36:     17  3 CALL pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:95)
      37:     17  3 ELSE pred output_term_dep.r/2-0 (det) e; output_term_dep.m:120
      38:     18  4 CALL pred output_term_dep.ra/1-0 (semidet) output_term_dep.m:127 (output_term_dep.m:111)
      39:     18  4 SWTC pred output_term_dep.ra/1-0 (semidet) s2; output_term_dep.m:128
      40:     18  4 EXIT pred output_term_dep.ra/1-0 (semidet) output_term_dep.m:127 (output_term_dep.m:111)
      41:     17  3 THEN pred output_term_dep.r/2-0 (det) e;t; output_term_dep.m:117
      42:     19  4 CALL pred output_term_dep.rb/1-0 (semidet) output_term_dep.m:133 (output_term_dep.m:114)
      43:     19  4 EXIT pred output_term_dep.rb/1-0 (semidet) output_term_dep.m:133 (output_term_dep.m:114)
      44:     17  3 THEN pred output_term_dep.r/2-0 (det) e;t;t; output_term_dep.m:116
      45:     20  4 CALL pred output_term_dep.rc/1-0 (det) output_term_dep.m:138 (output_term_dep.m:116)
      46:     20  4 EXIT pred output_term_dep.rc/1-0 (det) output_term_dep.m:138 (output_term_dep.m:116)
      47:     17  3 EXIT pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:95)
57
      48:     21  3 CALL pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:98)
      49:     21  3 ELSE pred output_term_dep.r/2-0 (det) e; output_term_dep.m:120
      50:     22  4 CALL pred output_term_dep.ra/1-0 (semidet) output_term_dep.m:127 (output_term_dep.m:111)
      51:     22  4 FAIL pred output_term_dep.ra/1-0 (semidet) output_term_dep.m:127 (output_term_dep.m:111)
      52:     21  3 ELSE pred output_term_dep.r/2-0 (det) e;e; output_term_dep.m:121
      53:     23  4 CALL pred output_term_dep.rd/1-0 (det) output_term_dep.m:143 (output_term_dep.m:121)
      54:     23  4 EXIT pred output_term_dep.rd/1-0 (det) output_term_dep.m:143 (output_term_dep.m:121)
      55:     21  3 EXIT pred output_term_dep.r/2-0 (det) output_term_dep.m:110 (output_term_dep.m:98)
-1
      56:     12  2 EXIT pred output_term_dep.test3/2-0 (det) output_term_dep.m:88 (output_term_dep.m:15)
      57:     24  2 CALL pred output_term_dep.test4/2-0 (det) output_term_dep.m:148 (output_term_dep.m:16)
      58:     25  3 CALL pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      59:     25  3 SWTC pred output_term_dep.s/3-0 (nondet) s1; output_term_dep.m:169
      60:     25  3 DISJ pred output_term_dep.s/3-0 (nondet) s1;c1;d1; output_term_dep.m:171
      61:     26  4 CALL pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:171)
      62:     26  4 EXIT pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:171)
      63:     25  3 DISJ pred output_term_dep.s/3-0 (nondet) s1;c2;d1; output_term_dep.m:176
      64:     27  4 CALL pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:176)
      65:     27  4 EXIT pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:176)
      66:     25  3 EXIT pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      67:     28  3 CALL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      68:     28  3 FAIL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      69:     25  3 REDO pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      70:     25  3 DISJ pred output_term_dep.s/3-0 (nondet) s1;c2;d2; output_term_dep.m:178
      71:     29  4 CALL pred output_term_dep.sc/1-0 (det) output_term_dep.m:202 (output_term_dep.m:178)
      72:     29  4 EXIT pred output_term_dep.sc/1-0 (det) output_term_dep.m:202 (output_term_dep.m:178)
      73:     25  3 EXIT pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      74:     30  3 CALL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      75:     30  3 FAIL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      76:     25  3 REDO pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      77:     25  3 DISJ pred output_term_dep.s/3-0 (nondet) s1;c1;d2; output_term_dep.m:173
      78:     31  4 CALL pred output_term_dep.sb/1-0 (det) output_term_dep.m:197 (output_term_dep.m:173)
      79:     31  4 EXIT pred output_term_dep.sb/1-0 (det) output_term_dep.m:197 (output_term_dep.m:173)
      80:     25  3 DISJ pred output_term_dep.s/3-0 (nondet) s1;c2;d1; output_term_dep.m:176
      81:     32  4 CALL pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:176)
      82:     32  4 EXIT pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:176)
      83:     25  3 EXIT pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      84:     33  3 CALL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      85:     33  3 FAIL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      86:     25  3 REDO pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      87:     25  3 DISJ pred output_term_dep.s/3-0 (nondet) s1;c2;d2; output_term_dep.m:178
      88:     34  4 CALL pred output_term_dep.sc/1-0 (det) output_term_dep.m:202 (output_term_dep.m:178)
      89:     34  4 EXIT pred output_term_dep.sc/1-0 (det) output_term_dep.m:202 (output_term_dep.m:178)
      90:     25  3 EXIT pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      91:     35  3 CALL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      92:     35  3 FAIL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:151)
      93:     25  3 REDO pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      94:     25  3 FAIL pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:150)
      95:     24  2 ELSE pred output_term_dep.test4/2-0 (det) c1;e; output_term_dep.m:155
no
      96:     36  3 CALL pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:158)
      97:     36  3 SWTC pred output_term_dep.s/3-0 (nondet) s2; output_term_dep.m:184
      98:     36  3 DISJ pred output_term_dep.s/3-0 (nondet) s2;d1; output_term_dep.m:182
      99:     37  4 CALL pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:182)
     100:     37  4 EXIT pred output_term_dep.sa/1-0 (det) output_term_dep.m:192 (output_term_dep.m:182)
     101:     38  4 CALL pred output_term_dep.sb/1-0 (det) output_term_dep.m:197 (output_term_dep.m:183)
     102:     38  4 EXIT pred output_term_dep.sb/1-0 (det) output_term_dep.m:197 (output_term_dep.m:183)
     103:     36  3 EXIT pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:158)
     104:     39  3 CALL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:159)
     105:     39  3 FAIL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:159)
     106:     36  3 REDO pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:158)
     107:     36  3 DISJ pred output_term_dep.s/3-0 (nondet) s2;d2; output_term_dep.m:185
     108:     40  4 CALL pred output_term_dep.sb/1-0 (det) output_term_dep.m:197 (output_term_dep.m:185)
     109:     40  4 EXIT pred output_term_dep.sb/1-0 (det) output_term_dep.m:197 (output_term_dep.m:185)
     110:     41  4 CALL pred output_term_dep.sc/1-0 (det) output_term_dep.m:202 (output_term_dep.m:186)
     111:     41  4 EXIT pred output_term_dep.sc/1-0 (det) output_term_dep.m:202 (output_term_dep.m:186)
     112:     36  3 EXIT pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:158)
     113:     42  3 CALL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:159)
     114:     42  3 FAIL pred output_term_dep.sd/1-0 (semidet) output_term_dep.m:207 (output_term_dep.m:159)
     115:     36  3 REDO pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:158)
     116:     36  3 FAIL pred output_term_dep.s/3-0 (nondet) output_term_dep.m:169 (output_term_dep.m:158)
     117:     24  2 ELSE pred output_term_dep.test4/2-0 (det) c2;e; output_term_dep.m:163
no
     118:     24  2 EXIT pred output_term_dep.test4/2-0 (det) output_term_dep.m:148 (output_term_dep.m:16)
     119:     43  2 CALL pred output_term_dep.test5/2-0 (det) output_term_dep.m:218 (output_term_dep.m:17)
     120:     44  3 CALL pred output_term_dep.t/2-0 (semidet) output_term_dep.m:225 (output_term_dep.m:214)
     121:     45  4 CALL pred output_term_dep.ta/1-0 (semidet) output_term_dep.m:233 (output_term_dep.m:226)
     122:     45  4 FAIL pred output_term_dep.ta/1-0 (semidet) output_term_dep.m:233 (output_term_dep.m:226)
     123:     46  4 CALL pred output_term_dep.tb/1-0 (det) output_term_dep.m:238 (output_term_dep.m:227)
     124:     46  4 EXIT pred output_term_dep.tb/1-0 (det) output_term_dep.m:238 (output_term_dep.m:227)
     125:     47  4 CALL pred output_term_dep.tc/1-0 (semidet) output_term_dep.m:243 (output_term_dep.m:228)
     126:     47  4 FAIL pred output_term_dep.tc/1-0 (semidet) output_term_dep.m:243 (output_term_dep.m:228)
     127:     44  3 EXIT pred output_term_dep.t/2-0 (semidet) output_term_dep.m:225 (output_term_dep.m:214)
     128:     43  2 THEN pred output_term_dep.test5/2-0 (det) t; output_term_dep.m:216
77
     129:     43  2 EXIT pred output_term_dep.test5/2-0 (det) output_term_dep.m:218 (output_term_dep.m:17)
     130:      1  1 EXIT pred output_term_dep.main/2-0 (det) output_term_dep.m:9
