      E1:     C1 CALL pred poly_io_retry.main/2-0 (det) poly_io_retry.m:13
mdb> mdb> Contexts will not be printed.
mdb> echo on
Command echo enabled.
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> break polycall
Ambiguous procedure specification. The matches are:
0: pred poly_io_retry.polycall/3-1 (det)
1: pred poly_io_retry.polycall/3-0 (det)

Which do you want to put a breakpoint on (0-1 or *)? *
 0: + stop  interface pred poly_io_retry.polycall/3-1 (det)
 1: + stop  interface pred poly_io_retry.polycall/3-0 (det)
mdb> c
      E2:     C2 CALL pred poly_io_retry.polycall/3-0 (det)
mdb> f
1
      E3:     C2 EXIT pred poly_io_retry.polycall/3-0 (det)
mdb> retry -a
      E2:     C2 CALL pred poly_io_retry.polycall/3-0 (det)
mdb> f
      E3:     C2 EXIT pred poly_io_retry.polycall/3-0 (det)
mdb> c
      E4:     C3 CALL pred poly_io_retry.polycall/3-1 (det)
mdb> f
      E5:     C3 EXIT pred poly_io_retry.polycall/3-1 (det)
mdb> retry
Cannot perform retry because the values of some input arguments are missing.
mdb> quit -y
