       1:      1  1 CALL pred print_goal:main/2-0 (det) print_goal.m:12
mdb> Registering debuggable procedures... done.
There is one debuggable module, with 5 procedures.
 0: + stop  interface pred print_goal:big_data/1-0 (det)
mdb>  1: + stop  interface pred print_goal:print_goal/8-0 (det)
mdb>        2:      2  2 CALL pred print_goal:big_data/1-0 (det) print_goal.m:24 (print_goal.m:13)
mdb> big_data('_')
mdb>        3:      2  2 EXIT pred print_goal:big_data/1-0 (det) print_goal.m:24 (print_goal.m:13)
mdb> big_data(big(big(big/3, 2, small), 3, big(big/3, 6, small)))
mdb> big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big(small, 5, small)), 6, small)).
       4:      3  2 CALL pred print_goal:print_goal/8-0 (det) print_goal.m:54 (print_goal.m:16)
mdb> print_goal(100, 101, '_', '_', 102, '_', state('<<c_pointer>>'), '_')
mdb>        5:      3  2 EXIT pred print_goal:print_goal/8-0 (det) print_goal.m:54 (print_goal.m:16)
mdb> print_goal(100, 101, 102, 103, 102, 103, _, state(<<c_pointer>>))
mdb> 103.
103.
