       1:      1  1 CALL pred print_goal:main/2-0 (det) print_goal.m:12
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> b big_data
 0: + stop  interface pred print_goal:big_data/1-0 (det)
mdb> b print_goal
 1: + stop  interface pred print_goal:print_goal/8-0 (det)
mdb> c
       2:      2  2 CALL pred print_goal:big_data/1-0 (det)
mdb> p goal
big_data('_')
mdb> finish
       3:      2  2 EXIT pred print_goal:big_data/1-0 (det)
mdb> p goal
big_data(big(big(big/3, 2, small), 3, big(big/3, 6, small)))
mdb> c
big(big(big(small, 1, small), 2, small), 3, big(big(small, 4, big(small, 5, small)), 6, small)).
       4:      3  2 CALL pred print_goal:print_goal/8-0 (det)
mdb> p goal
print_goal(100, 101, '_', '_', 102, '_', state('<<c_pointer>>'), '_')
mdb> finish
       5:      3  2 EXIT pred print_goal:print_goal/8-0 (det)
mdb> p goal
print_goal(100, 101, 102, 103, 102, 103, _, state(<<c_pointer>>))
mdb> c
103.
103.
