       1:      1  1 CALL pred queens_lib:main/2-0 (cc_multi) 
mdb> echo on
Command echo enabled
mdb> print *
       HeadVar__1           		state('<<c_pointer>>')
mdb> 
       2:      2  2 CALL pred queens_lib:data/1-0 (det) 
mdb> print *
mdb: there are no live variables
mdb> 
       3:      2  2 EXIT pred queens_lib:data/1-0 (det) 
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
       4:      3  2 CALL pred queens_lib:queen/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
       5:      4  3 CALL pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
       6:      4  3 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
       7:      5  4 CALL pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__2           		[1, 2, 3, 4, 5]
mdb> 
       8:      5  4 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
mdb> print *
       HeadVar__2           		[1, 2, 3, 4, 5]
       V_10                 		[2, 3, 4, 5]
       V_11                 		1
mdb> level 1
Ancestor level set to 1
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> up 1
Ancestor level set to 2
mdb> vars
        0 HeadVar__1
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
       9:      5  4 EXIT pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__1           		1
       HeadVar__2           		[1, 2, 3, 4, 5]
       HeadVar__3           		[2, 3, 4, 5]
mdb> 
      10:      6  4 CALL pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[2, 3, 4, 5]
mdb> 
      11:      6  4 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
mdb> print *
       HeadVar__1           		[2, 3, 4, 5]
mdb> 
      12:      7  5 CALL pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__2           		[2, 3, 4, 5]
mdb> 
      13:      7  5 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
mdb> print *
       HeadVar__2           		[2, 3, 4, 5]
       V_10                 		[3, 4, 5]
       V_11                 		2
mdb> 
      14:      7  5 EXIT pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__1           		2
       HeadVar__2           		[2, 3, 4, 5]
       HeadVar__3           		[3, 4, 5]
mdb> 
      15:      8  5 CALL pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[3, 4, 5]
mdb> 
      16:      8  5 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
mdb> print *
       HeadVar__1           		[3, 4, 5]
mdb> 
      17:      9  6 CALL pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__2           		[3, 4, 5]
mdb> 
      18:      9  6 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
mdb> print *
       HeadVar__2           		[3, 4, 5]
       V_10                 		[4, 5]
       V_11                 		3
mdb> 
      19:      9  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__1           		3
       HeadVar__2           		[3, 4, 5]
       HeadVar__3           		[4, 5]
mdb> 
      20:     10  6 CALL pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[4, 5]
mdb> 
      21:     10  6 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
mdb> print *
       HeadVar__1           		[4, 5]
mdb> 
      22:     11  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__2           		[4, 5]
mdb> 
      23:     11  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
mdb> print *
       HeadVar__2           		[4, 5]
       V_10                 		[5]
       V_11                 		4
mdb> 
      24:     11  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__1           		4
       HeadVar__2           		[4, 5]
       HeadVar__3           		[5]
mdb> 
      25:     12  7 CALL pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[5]
mdb> 
      26:     12  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
mdb> print *
       HeadVar__1           		[5]
mdb> 
      27:     13  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__2           		[5]
mdb> 
      28:     13  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
mdb> print *
       HeadVar__2           		[5]
       V_10                 		[]
       V_11                 		5
mdb> 
      29:     13  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
mdb> print *
       HeadVar__1           		5
       HeadVar__2           		[5]
       HeadVar__3           		[]
mdb> 
      30:     14  8 CALL pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[]
mdb> 
      31:     14  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
mdb> print *
mdb> 
      32:     14  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[]
       HeadVar__2           		[]
mdb> 
      33:     12  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[5]
       HeadVar__2           		[5]
mdb> 
      34:     10  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[4, 5]
       HeadVar__2           		[4, 5]
mdb> 
      35:      8  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[3, 4, 5]
       HeadVar__2           		[3, 4, 5]
mdb> 
      36:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[2, 3, 4, 5]
       HeadVar__2           		[2, 3, 4, 5]
mdb> 
      37:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
       HeadVar__2           		[1, 2, 3, 4, 5]
mdb> 
      38:     15  3 CALL pred queens_lib:safe/1-0 (semidet) 
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
      39:     15  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
mdb> print *
       HeadVar__1           		[1, 2, 3, 4, 5]
mdb> 
      40:     16  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
mdb> print *
       HeadVar__1           		1
       HeadVar__2           		1
       HeadVar__3           		[2, 3, 4, 5]
mdb> 
      41:     16  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
mdb> print *
       HeadVar__1           		1
       HeadVar__2           		1
       HeadVar__3           		[2, 3, 4, 5]
mdb> continue -a -N
      42:     16  4 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
      43:     16  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
      44:     15  3 FAIL pred queens_lib:safe/1-0 (semidet) 
      45:     14  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
      46:     13  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
      47:     17  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
      48:     17  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      49:     13  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      50:     12  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
      51:     11  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
      52:     18  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
      53:     18  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
      54:     18  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
      55:     11  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
      56:     19  7 CALL pred queens_lib:qperm/2-0 (nondet) 
      57:     19  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
      58:     20  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
      59:     20  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
      60:     20  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
      61:     21  8 CALL pred queens_lib:qperm/2-0 (nondet) 
      62:     21  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
      63:     21  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
      64:     19  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
      65:     10  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
      66:      8  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
      67:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
      68:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
      69:     22  3 CALL pred queens_lib:safe/1-0 (semidet) 
      70:     22  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
      71:     23  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
      72:     23  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
      73:     23  4 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
      74:     23  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
      75:     22  3 FAIL pred queens_lib:safe/1-0 (semidet) 
      76:     21  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
      77:     20  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
      78:     24  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
      79:     24  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      80:     20  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      81:     19  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
      82:     18  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
      83:     25  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
      84:     25  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      85:     18  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      86:     11  7 FAIL pred queens_lib:qdelete/3-0 (nondet) 
      87:     10  6 FAIL pred queens_lib:qperm/2-0 (nondet) 
      88:      9  6 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
      89:     26  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
      90:     26  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
      91:     26  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
      92:      9  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
      93:     27  6 CALL pred queens_lib:qperm/2-0 (nondet) 
      94:     27  6 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
      95:     28  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
      96:     28  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
      97:     28  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
      98:     29  7 CALL pred queens_lib:qperm/2-0 (nondet) 
      99:     29  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     100:     30  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     101:     30  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     102:     30  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     103:     31  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     104:     31  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     105:     31  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     106:     29  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     107:     27  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     108:      8  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     109:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     110:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     111:     32  3 CALL pred queens_lib:safe/1-0 (semidet) 
     112:     32  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     113:     33  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     114:     33  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     115:     33  4 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     116:     33  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     117:     32  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     118:     31  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     119:     30  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     120:     34  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     121:     34  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     122:     30  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     123:     29  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     124:     28  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     125:     35  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     126:     35  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     127:     35  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     128:     28  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     129:     36  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     130:     36  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     131:     37  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     132:     37  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     133:     37  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     134:     38  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     135:     38  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     136:     38  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     137:     36  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     138:     27  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     139:      8  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     140:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     141:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     142:     39  3 CALL pred queens_lib:safe/1-0 (semidet) 
     143:     39  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     144:     40  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     145:     40  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     146:     40  4 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     147:     40  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     148:     39  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     149:     38  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     150:     37  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     151:     41  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     152:     41  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     153:     37  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     154:     36  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     155:     35  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     156:     42  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     157:     42  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     158:     35  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     159:     28  7 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     160:     27  6 FAIL pred queens_lib:qperm/2-0 (nondet) 
     161:     26  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     162:     43  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     163:     43  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     164:     43  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     165:     26  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     166:      9  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     167:     44  6 CALL pred queens_lib:qperm/2-0 (nondet) 
     168:     44  6 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     169:     45  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
     170:     45  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     171:     45  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     172:     46  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     173:     46  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     174:     47  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     175:     47  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     176:     47  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     177:     48  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     178:     48  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     179:     48  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     180:     46  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     181:     44  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     182:      8  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     183:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     184:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     185:     49  3 CALL pred queens_lib:safe/1-0 (semidet) 
     186:     49  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     187:     50  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     188:     50  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     189:     50  4 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     190:     50  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     191:     49  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     192:     48  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     193:     47  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     194:     51  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     195:     51  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     196:     47  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     197:     46  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     198:     45  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     199:     52  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     200:     52  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     201:     52  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     202:     45  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     203:     53  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     204:     53  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     205:     54  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     206:     54  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     207:     54  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     208:     55  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     209:     55  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     210:     55  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     211:     53  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     212:     44  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     213:      8  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     214:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     215:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     216:     56  3 CALL pred queens_lib:safe/1-0 (semidet) 
     217:     56  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     218:     57  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     219:     57  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     220:     57  4 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     221:     57  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     222:     56  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     223:     55  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     224:     54  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     225:     58  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     226:     58  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     227:     54  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     228:     53  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     229:     52  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     230:     59  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     231:     59  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     232:     52  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     233:     45  7 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     234:     44  6 FAIL pred queens_lib:qperm/2-0 (nondet) 
     235:     43  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     236:     60  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     237:     60  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     238:     43  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     239:     26  7 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     240:      9  6 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     241:      8  5 FAIL pred queens_lib:qperm/2-0 (nondet) 
     242:      7  5 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     243:     61  6 CALL pred queens_lib:qdelete/3-0 (nondet) 
     244:     61  6 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     245:     61  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     246:      7  5 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     247:     62  5 CALL pred queens_lib:qperm/2-0 (nondet) 
     248:     62  5 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     249:     63  6 CALL pred queens_lib:qdelete/3-0 (nondet) 
     250:     63  6 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     251:     63  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     252:     64  6 CALL pred queens_lib:qperm/2-0 (nondet) 
     253:     64  6 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     254:     65  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
     255:     65  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     256:     65  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     257:     66  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     258:     66  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     259:     67  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     260:     67  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     261:     67  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     262:     68  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     263:     68  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     264:     68  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     265:     66  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     266:     64  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     267:     62  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     268:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     269:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     270:     69  3 CALL pred queens_lib:safe/1-0 (semidet) 
     271:     69  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     272:     70  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     273:     70  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     274:     70  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     275:     70  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     276:     71  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     277:     71  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     278:     71  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     279:     71  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     280:     72  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     281:     72  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     282:     72  6 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     283:     72  6 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     284:     71  5 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     285:     70  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     286:     69  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     287:     68  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     288:     67  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     289:     73  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     290:     73  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     291:     67  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     292:     66  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     293:     65  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     294:     74  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     295:     74  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     296:     74  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     297:     65  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     298:     75  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     299:     75  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     300:     76  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     301:     76  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     302:     76  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     303:     77  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     304:     77  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     305:     77  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     306:     75  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     307:     64  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     308:     62  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     309:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     310:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     311:     78  3 CALL pred queens_lib:safe/1-0 (semidet) 
     312:     78  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     313:     79  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     314:     79  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     315:     79  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     316:     79  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     317:     80  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     318:     80  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     319:     80  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     320:     80  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     321:     81  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     322:     81  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     323:     81  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     324:     81  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     325:     82  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     326:     82  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     327:     82  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     328:     82  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     329:     83  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     330:     83  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     331:     83  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     332:     82  7 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     333:     81  6 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     334:     80  5 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     335:     79  4 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     336:     84  4 CALL pred queens_lib:safe/1-0 (semidet) 
     337:     84  4 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     338:     85  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     339:     85  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     340:     85  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     341:     85  5 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;t;
     342:     85  5 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     343:     84  4 FAIL pred queens_lib:safe/1-0 (semidet) 
     344:     78  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     345:     77  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     346:     76  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     347:     86  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     348:     86  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     349:     76  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     350:     75  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     351:     74  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     352:     87  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     353:     87  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     354:     74  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     355:     65  7 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     356:     64  6 FAIL pred queens_lib:qperm/2-0 (nondet) 
     357:     63  6 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     358:     88  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
     359:     88  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     360:     88  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     361:     63  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     362:     89  6 CALL pred queens_lib:qperm/2-0 (nondet) 
     363:     89  6 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     364:     90  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
     365:     90  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     366:     90  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     367:     91  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     368:     91  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     369:     92  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     370:     92  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     371:     92  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     372:     93  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     373:     93  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     374:     93  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     375:     91  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     376:     89  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     377:     62  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     378:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     379:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     380:     94  3 CALL pred queens_lib:safe/1-0 (semidet) 
     381:     94  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     382:     95  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     383:     95  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     384:     95  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     385:     95  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     386:     96  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     387:     96  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     388:     96  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     389:     96  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     390:     97  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     391:     97  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     392:     97  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     393:     97  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     394:     98  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     395:     98  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     396:     98  7 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     397:     98  7 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     398:     97  6 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     399:     96  5 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     400:     95  4 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     401:     94  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     402:     93  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     403:     92  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     404:     99  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     405:     99  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     406:     92  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     407:     91  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     408:     90  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     409:    100  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     410:    100  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     411:    100  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     412:     90  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     413:    101  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     414:    101  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     415:    102  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     416:    102  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     417:    102  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     418:    103  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     419:    103  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     420:    103  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     421:    101  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     422:     89  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     423:     62  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     424:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     425:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     426:    104  3 CALL pred queens_lib:safe/1-0 (semidet) 
     427:    104  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     428:    105  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     429:    105  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     430:    105  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     431:    105  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     432:    106  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     433:    106  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     434:    106  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     435:    106  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     436:    107  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     437:    107  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     438:    107  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     439:    107  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     440:    108  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     441:    108  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     442:    108  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     443:    108  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     444:    109  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     445:    109  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     446:    109  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     447:    108  7 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     448:    107  6 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     449:    106  5 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     450:    105  4 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     451:    110  4 CALL pred queens_lib:safe/1-0 (semidet) 
     452:    110  4 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     453:    111  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     454:    111  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     455:    111  5 THEN pred queens_lib:nodiag/3-0 (semidet) s1;c4;t;
     456:    111  5 FAIL pred queens_lib:nodiag/3-0 (semidet) 
     457:    110  4 FAIL pred queens_lib:safe/1-0 (semidet) 
     458:    104  3 FAIL pred queens_lib:safe/1-0 (semidet) 
     459:    103  8 FAIL pred queens_lib:qperm/2-0 (nondet) 
     460:    102  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     461:    112  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     462:    112  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     463:    102  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     464:    101  7 FAIL pred queens_lib:qperm/2-0 (nondet) 
     465:    100  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     466:    113  9 CALL pred queens_lib:qdelete/3-0 (nondet) 
     467:    113  9 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     468:    100  8 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     469:     90  7 FAIL pred queens_lib:qdelete/3-0 (nondet) 
     470:     89  6 FAIL pred queens_lib:qperm/2-0 (nondet) 
     471:     88  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d2;
     472:    114  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     473:    114  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     474:    114  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     475:     88  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     476:     63  6 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     477:    115  6 CALL pred queens_lib:qperm/2-0 (nondet) 
     478:    115  6 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     479:    116  7 CALL pred queens_lib:qdelete/3-0 (nondet) 
     480:    116  7 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     481:    116  7 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     482:    117  7 CALL pred queens_lib:qperm/2-0 (nondet) 
     483:    117  7 SWTC pred queens_lib:qperm/2-0 (nondet) s1;
     484:    118  8 CALL pred queens_lib:qdelete/3-0 (nondet) 
     485:    118  8 DISJ pred queens_lib:qdelete/3-0 (nondet) c2;d1;
     486:    118  8 EXIT pred queens_lib:qdelete/3-0 (nondet) 
     487:    119  8 CALL pred queens_lib:qperm/2-0 (nondet) 
     488:    119  8 SWTC pred queens_lib:qperm/2-0 (nondet) s2;
     489:    119  8 EXIT pred queens_lib:qperm/2-0 (nondet) 
     490:    117  7 EXIT pred queens_lib:qperm/2-0 (nondet) 
     491:    115  6 EXIT pred queens_lib:qperm/2-0 (nondet) 
     492:     62  5 EXIT pred queens_lib:qperm/2-0 (nondet) 
     493:      6  4 EXIT pred queens_lib:qperm/2-0 (nondet) 
     494:      4  3 EXIT pred queens_lib:qperm/2-0 (nondet) 
     495:    120  3 CALL pred queens_lib:safe/1-0 (semidet) 
     496:    120  3 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     497:    121  4 CALL pred queens_lib:nodiag/3-0 (semidet) 
     498:    121  4 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     499:    121  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     500:    121  4 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     501:    122  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     502:    122  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     503:    122  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     504:    122  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     505:    123  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     506:    123  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     507:    123  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     508:    123  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     509:    124  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     510:    124  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     511:    124  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     512:    124  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     513:    125  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     514:    125  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     515:    125  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     516:    124  7 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     517:    123  6 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     518:    122  5 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     519:    121  4 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     520:    126  4 CALL pred queens_lib:safe/1-0 (semidet) 
     521:    126  4 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     522:    127  5 CALL pred queens_lib:nodiag/3-0 (semidet) 
     523:    127  5 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     524:    127  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     525:    127  5 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     526:    128  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     527:    128  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     528:    128  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     529:    128  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     530:    129  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     531:    129  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     532:    129  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     533:    129  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     534:    130  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     535:    130  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     536:    130  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     537:    129  7 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     538:    128  6 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     539:    127  5 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     540:    131  5 CALL pred queens_lib:safe/1-0 (semidet) 
     541:    131  5 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     542:    132  6 CALL pred queens_lib:nodiag/3-0 (semidet) 
     543:    132  6 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     544:    132  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     545:    132  6 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     546:    133  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     547:    133  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     548:    133  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     549:    133  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     550:    134  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     551:    134  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     552:    134  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     553:    133  7 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     554:    132  6 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     555:    135  6 CALL pred queens_lib:safe/1-0 (semidet) 
     556:    135  6 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     557:    136  7 CALL pred queens_lib:nodiag/3-0 (semidet) 
     558:    136  7 SWTC pred queens_lib:nodiag/3-0 (semidet) s1;
     559:    136  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;
     560:    136  7 ELSE pred queens_lib:nodiag/3-0 (semidet) s1;c4;e;e;
     561:    137  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     562:    137  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     563:    137  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     564:    136  7 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     565:    138  7 CALL pred queens_lib:safe/1-0 (semidet) 
     566:    138  7 SWTC pred queens_lib:safe/1-0 (semidet) s1;
     567:    139  8 CALL pred queens_lib:nodiag/3-0 (semidet) 
     568:    139  8 SWTC pred queens_lib:nodiag/3-0 (semidet) s2;
     569:    139  8 EXIT pred queens_lib:nodiag/3-0 (semidet) 
     570:    140  8 CALL pred queens_lib:safe/1-0 (semidet) 
     571:    140  8 SWTC pred queens_lib:safe/1-0 (semidet) s2;
     572:    140  8 EXIT pred queens_lib:safe/1-0 (semidet) 
     573:    138  7 EXIT pred queens_lib:safe/1-0 (semidet) 
     574:    135  6 EXIT pred queens_lib:safe/1-0 (semidet) 
     575:    131  5 EXIT pred queens_lib:safe/1-0 (semidet) 
     576:    126  4 EXIT pred queens_lib:safe/1-0 (semidet) 
     577:    120  3 EXIT pred queens_lib:safe/1-0 (semidet) 
     578:      3  2 EXIT pred queens_lib:queen/2-0 (nondet) 
     579:      1  1 THEN pred queens_lib:main/2-0 (cc_multi) t;
     580:    141  2 CALL pred queens_lib:print_list/3-0 (det) 
     581:    141  2 ELSE pred queens_lib:print_list/3-0 (det) e;
     582:    142  3 CALL pred io:write_string/3-0 (det) 
[     583:    142  3 EXIT pred io:write_string/3-0 (det) 
     584:    143  3 CALL pred queens_lib:print_list_2/3-0 (det) 
     585:    143  3 SWTC pred queens_lib:print_list_2/3-0 (det) s1;
     586:    144  4 CALL pred io:write_int/3-0 (det) 
1     587:    144  4 EXIT pred io:write_int/3-0 (det) 
     588:    143  3 ELSE pred queens_lib:print_list_2/3-0 (det) s1;c3;e;
     589:    145  4 CALL pred io:write_string/3-0 (det) 
,      590:    145  4 EXIT pred io:write_string/3-0 (det) 
     591:    146  4 CALL pred queens_lib:print_list_2/3-0 (det) 
     592:    146  4 SWTC pred queens_lib:print_list_2/3-0 (det) s1;
     593:    147  5 CALL pred io:write_int/3-0 (det) 
3     594:    147  5 EXIT pred io:write_int/3-0 (det) 
     595:    146  4 ELSE pred queens_lib:print_list_2/3-0 (det) s1;c3;e;
     596:    148  5 CALL pred io:write_string/3-0 (det) 
,      597:    148  5 EXIT pred io:write_string/3-0 (det) 
     598:    149  5 CALL pred queens_lib:print_list_2/3-0 (det) 
     599:    149  5 SWTC pred queens_lib:print_list_2/3-0 (det) s1;
     600:    150  6 CALL pred io:write_int/3-0 (det) 
5     601:    150  6 EXIT pred io:write_int/3-0 (det) 
     602:    149  5 ELSE pred queens_lib:print_list_2/3-0 (det) s1;c3;e;
     603:    151  6 CALL pred io:write_string/3-0 (det) 
,      604:    151  6 EXIT pred io:write_string/3-0 (det) 
     605:    152  6 CALL pred queens_lib:print_list_2/3-0 (det) 
     606:    152  6 SWTC pred queens_lib:print_list_2/3-0 (det) s1;
     607:    153  7 CALL pred io:write_int/3-0 (det) 
2     608:    153  7 EXIT pred io:write_int/3-0 (det) 
     609:    152  6 ELSE pred queens_lib:print_list_2/3-0 (det) s1;c3;e;
     610:    154  7 CALL pred io:write_string/3-0 (det) 
,      611:    154  7 EXIT pred io:write_string/3-0 (det) 
     612:    155  7 CALL pred queens_lib:print_list_2/3-0 (det) 
     613:    155  7 SWTC pred queens_lib:print_list_2/3-0 (det) s1;
     614:    156  8 CALL pred io:write_int/3-0 (det) 
4     615:    156  8 EXIT pred io:write_int/3-0 (det) 
     616:    155  7 THEN pred queens_lib:print_list_2/3-0 (det) s1;c3;t;
     617:    155  7 EXIT pred queens_lib:print_list_2/3-0 (det) 
     618:    152  6 EXIT pred queens_lib:print_list_2/3-0 (det) 
     619:    149  5 EXIT pred queens_lib:print_list_2/3-0 (det) 
     620:    146  4 EXIT pred queens_lib:print_list_2/3-0 (det) 
     621:    143  3 EXIT pred queens_lib:print_list_2/3-0 (det) 
     622:    157  3 CALL pred io:write_string/3-0 (det) 
]
     623:    157  3 EXIT pred io:write_string/3-0 (det) 
     624:    141  2 EXIT pred queens_lib:print_list/3-0 (det) 
     625:      1  1 EXIT pred queens_lib:main/2-0 (cc_multi) 
