      E1:     C1  1 CALL pred resume_typeinfos.main/2-0 (det) resume_typeinfos.m:NNNN
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> goto 4
      E2:     C2  3 CALL pred resume_typeinfos.introduce_new_typeinfo/2-0 (det)
mdb> print *
       HeadVar__1             	[1, 2]
mdb> goto 6
      E3:     C3  2 COND pred resume_typeinfos.test/2-0 (semidet) c2;?;
mdb> finish
      E4:     C3  2 FAIL pred resume_typeinfos.test/2-0 (semidet)
mdb> print *
       TestList (arg 1)       	[1, 2]
mdb> continue
no solution.
