       1:      1  1 CALL pred resume_typeinfos:main/2-0 (det) resume_typeinfos.m:NNNN
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> goto 3
       3:      3  3 CALL pred resume_typeinfos:introduce_new_typeinfo/2-0 (det)
mdb> print *
       HeadVar__1             	[1, 2]
mdb> goto 5
       5:      2  2 ELSE pred resume_typeinfos:test/2-0 (semidet) c2;e;
mdb> finish
       6:      2  2 FAIL pred resume_typeinfos:test/2-0 (semidet)
mdb> print *
       TestList (arg 1)       	[1, 2]
mdb> continue
no solution.
