       1:      1  1 CALL pred retry:main/2-0 (det) retry.m:25
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> scroll off
Scroll control disabled.
mdb> context none
Contexts will not be printed.
mdb> break det_without_cut_1
 0: + stop  interface pred retry:det_without_cut_1/2-0 (det)
mdb> continue -a
       2:      2  2 CALL pred retry:det_without_cut/2-0 (det)
       3:      3  3 CALL pred retry:det_without_cut_1/2-0 (det)
mdb> disable 0
 0: - stop  interface pred retry:det_without_cut_1/2-0 (det)
mdb> retry
This command is a no-op from this port.
mdb> stack
   0       pred retry:det_without_cut_1/2-0 (det)
   1       pred retry:det_without_cut/2-0 (det)
   2       pred retry:main/2-0 (det)
mdb> finish
       6:      3  3 EXIT pred retry:det_without_cut_1/2-0 (det)
mdb> retry 1
       2:      2  2 CALL pred retry:det_without_cut/2-0 (det)
mdb> stack
   0       pred retry:det_without_cut/2-0 (det)
   1       pred retry:main/2-0 (det)
mdb> break det_without_cut_2
 1: + stop  interface pred retry:det_without_cut_2/2-0 (det)
mdb> continue -a
       3:      3  3 CALL pred retry:det_without_cut_1/2-0 (det)
       4:      4  4 CALL pred retry:det_without_cut_2/2-0 (det)
mdb> delete *
 0: D stop  interface pred retry:det_without_cut_1/2-0 (det)
 1: E stop  interface pred retry:det_without_cut_2/2-0 (det)
mdb> retry 2
       2:      2  2 CALL pred retry:det_without_cut/2-0 (det)
mdb> finish
       7:      2  2 EXIT pred retry:det_without_cut/2-0 (det)
mdb> stack
   0       pred retry:det_without_cut/2-0 (det)
   1       pred retry:main/2-0 (det)
mdb> break det_with_cut_1
 0: + stop  interface pred retry:det_with_cut_1/2-0 (nondet)
mdb> continue -a
       8:      5  2 CALL pred retry:det_with_cut/2-0 (det)
       9:      6  3 CALL pred retry:det_with_cut_1/2-0 (nondet)
mdb> delete *
 0: E stop  interface pred retry:det_with_cut_1/2-0 (nondet)
mdb> finish
      13:      6  3 EXIT pred retry:det_with_cut_1/2-0 (nondet)
mdb> retry 1
       8:      5  2 CALL pred retry:det_with_cut/2-0 (det)
mdb> finish
      15:      5  2 EXIT pred retry:det_with_cut/2-0 (det)
mdb> stack
   0       pred retry:det_with_cut/2-0 (det)
   1       pred retry:main/2-0 (det)
mdb> retry 1
       1:      1  1 CALL pred retry:main/2-0 (det)
mdb> break det_with_cut_2
 0: + stop  interface pred retry:det_with_cut_2/2-0 (det)
mdb> continue -a
       2:      2  2 CALL pred retry:det_without_cut/2-0 (det)
       3:      3  3 CALL pred retry:det_without_cut_1/2-0 (det)
       4:      4  4 CALL pred retry:det_without_cut_2/2-0 (det)
       5:      4  4 EXIT pred retry:det_without_cut_2/2-0 (det)
       6:      3  3 EXIT pred retry:det_without_cut_1/2-0 (det)
       7:      2  2 EXIT pred retry:det_without_cut/2-0 (det)
       8:      5  2 CALL pred retry:det_with_cut/2-0 (det)
       9:      6  3 CALL pred retry:det_with_cut_1/2-0 (nondet)
      10:      6  3 DISJ pred retry:det_with_cut_1/2-0 (nondet) c2;d1;
      11:      7  4 CALL pred retry:det_with_cut_2/2-0 (det)
mdb> delete *
 0: E stop  interface pred retry:det_with_cut_2/2-0 (det)
mdb> break nondet
 0: + stop  interface pred retry:nondet/2-0 (multi)
mdb> continue
      21:     10  2 CALL pred retry:nondet/2-0 (multi)
mdb> print *
       X0 (arg 1)             	4
mdb> break nondet_2
 1: + stop  interface pred retry:nondet_2/2-0 (det)
mdb> continue
      25:     12  3 CALL pred retry:nondet_2/2-0 (det)
mdb> retry 1
      21:     10  2 CALL pred retry:nondet/2-0 (multi)
mdb> print *
       X0 (arg 1)             	4
mdb> delete *
 0: E stop  interface pred retry:nondet/2-0 (multi)
 1: E stop  interface pred retry:nondet_2/2-0 (det)
mdb> break fib
 0: + stop  interface pred retry:fib/2-0 (det)
mdb> continue
6
4
9
40 41 
50 51 
      89:     29  2 CALL pred retry:fib/2-0 (det)
mdb> print *
       N (arg 1)              	15
mdb> continue
      93:     30  3 CALL pred retry:fib/2-0 (det)
mdb> print *
       N (arg 1)              	14
mdb> continue
      97:     31  4 CALL pred retry:fib/2-0 (det)
mdb> continue
     101:     32  5 CALL pred retry:fib/2-0 (det)
mdb> step
     102:     32  5 ELSE pred retry:fib/2-0 (det) c2;e;
mdb> retry 2
      93:     30  3 CALL pred retry:fib/2-0 (det)
mdb> print *
       N (arg 1)              	14
mdb> next
      94:     30  3 ELSE pred retry:fib/2-0 (det) c2;e;
mdb> retry 1
      89:     29  2 CALL pred retry:fib/2-0 (det)
mdb> finish
      93:     30  3 CALL pred retry:fib/2-0 (det)
      97:     31  4 CALL pred retry:fib/2-0 (det)
     101:     32  5 CALL pred retry:fib/2-0 (det)
     105:     33  6 CALL pred retry:fib/2-0 (det)
     109:     34  7 CALL pred retry:fib/2-0 (det)
     113:     35  8 CALL pred retry:fib/2-0 (det)
     117:     36  9 CALL pred retry:fib/2-0 (det)
     121:     37 10 CALL pred retry:fib/2-0 (det)
     125:     38 11 CALL pred retry:fib/2-0 (det)
     129:     39 12 CALL pred retry:fib/2-0 (det)
     133:     40 13 CALL pred retry:fib/2-0 (det)
     137:     41 14 CALL pred retry:fib/2-0 (det)
     141:     42 15 CALL pred retry:fib/2-0 (det)
     145:     43 16 CALL pred retry:fib/2-0 (det)
     149:     43 16 EXIT pred retry:fib/2-0 (det)
     150:     44 16 CALL pred retry:fib/2-0 (det)
     154:     44 16 EXIT pred retry:fib/2-0 (det)
     155:     42 15 EXIT pred retry:fib/2-0 (det)
     156:     45 15 CALL pred retry:fib/2-0 (det)
     158:     45 15 EXIT pred retry:fib/2-0 (det)
     159:     41 14 EXIT pred retry:fib/2-0 (det)
     160:     46 14 CALL pred retry:fib/2-0 (det)
     162:     46 14 EXIT pred retry:fib/2-0 (det)
     163:     40 13 EXIT pred retry:fib/2-0 (det)
     164:     47 13 CALL pred retry:fib/2-0 (det)
     166:     47 13 EXIT pred retry:fib/2-0 (det)
     167:     39 12 EXIT pred retry:fib/2-0 (det)
     168:     48 12 CALL pred retry:fib/2-0 (det)
     170:     48 12 EXIT pred retry:fib/2-0 (det)
     171:     38 11 EXIT pred retry:fib/2-0 (det)
     172:     49 11 CALL pred retry:fib/2-0 (det)
     174:     49 11 EXIT pred retry:fib/2-0 (det)
     175:     37 10 EXIT pred retry:fib/2-0 (det)
     176:     50 10 CALL pred retry:fib/2-0 (det)
     178:     50 10 EXIT pred retry:fib/2-0 (det)
     179:     36  9 EXIT pred retry:fib/2-0 (det)
     180:     51  9 CALL pred retry:fib/2-0 (det)
     182:     51  9 EXIT pred retry:fib/2-0 (det)
     183:     35  8 EXIT pred retry:fib/2-0 (det)
     184:     52  8 CALL pred retry:fib/2-0 (det)
     186:     52  8 EXIT pred retry:fib/2-0 (det)
     187:     34  7 EXIT pred retry:fib/2-0 (det)
     188:     53  7 CALL pred retry:fib/2-0 (det)
     190:     53  7 EXIT pred retry:fib/2-0 (det)
     191:     33  6 EXIT pred retry:fib/2-0 (det)
     192:     54  6 CALL pred retry:fib/2-0 (det)
     194:     54  6 EXIT pred retry:fib/2-0 (det)
     195:     32  5 EXIT pred retry:fib/2-0 (det)
     196:     55  5 CALL pred retry:fib/2-0 (det)
     198:     55  5 EXIT pred retry:fib/2-0 (det)
     199:     31  4 EXIT pred retry:fib/2-0 (det)
     200:     56  4 CALL pred retry:fib/2-0 (det)
     202:     56  4 EXIT pred retry:fib/2-0 (det)
     203:     30  3 EXIT pred retry:fib/2-0 (det)
     204:     57  3 CALL pred retry:fib/2-0 (det)
     206:     57  3 EXIT pred retry:fib/2-0 (det)
     207:     29  2 EXIT pred retry:fib/2-0 (det)
mdb> continue -S
987
