      E1:     C1 CALL pred synth_attr.main/2-0 (cc_multi) synth_attr.m:17
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> user
      E2:     C2 USER <safe_test> pred synth_attr.queen/2-0 (nondet) c5; synth_attr.m:33
mdb> print *
       test_list (attr 0, Out)	[1, 2, 3, 4, 5]
       f (attr 1)             	testlen(10)
       excp (attr 2)          	univ_cons(software_error("testlen: N < Min"))
       Data (arg 1)           	[1, 2, 3, 4, 5]
mdb> browse !test_list
browser> p
[1, 2, 3, 4, 5]
browser> ^2^1
browser> p
2
browser> quit
mdb> user
      E3:     C3 USER <nodiag_fail> pred synth_attr.nodiag/3-0 (semidet) s2;c6;t;c4; synth_attr.m:75
mdb> vars
        1 test_failed (attr 0)
        2 arg_b (attr 1, B)
        3 arg_d (attr 2, N)
        4 arg_list_len (attr 3)
        5 sorted_list (attr 4)
        6 list_len_func (attr 5)
        7 list_sort_func (attr 6)
        8 arg_list (attr 7, HeadVar__3)
        9 HeadVar__1
       10 HeadVar__2
       11 HeadVar__3
       12 B
       13 BmN
       14 D
       15 L
       16 N
       17 NmB
mdb> print *
       test_failed (attr 0)   	"N - B"
       arg_b (attr 1, B)      	1
       arg_d (attr 2, N)      	2
       arg_list_len (attr 3)  	4
       sorted_list (attr 4)   	[2, 3, 4, 5]
       list_len_func (attr 5) 	lambda_synth_attr_m_75
       list_sort_func (attr 6)	lambda2_synth_attr_m_75
       arg_list (attr 7, HeadVar__3)	[2, 3, 4, 5]
       HeadVar__1             	1
       HeadVar__2             	1
       BmN                    	-1
       D                      	1
       L                      	[3, 4, 5]
       NmB                    	1
mdb> print !arg_b
       arg_b (attr 1, B)      	1
mdb> user
      E4:     C2 USER <safe_test> pred synth_attr.queen/2-0 (nondet) c5; synth_attr.m:33
mdb> print *
       test_list (attr 0, Out)	[1, 2, 3, 5, 4]
       f (attr 1)             	testlen(10)
       excp (attr 2)          	univ_cons(software_error("testlen: N < Min"))
       Data (arg 1)           	[1, 2, 3, 4, 5]
mdb> continue
[1, 3, 5, 2, 4]
