      E1:     C1  1 CALL pred tabled_read_unitize:main/2-0 (det) tabled_read_unitize.m:17
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> context none
Contexts will not be printed.
mdb> table_io start
io tabling started
mdb> break unitize
 0: + stop  interface pred tabled_read_unitize:unitize/4-0 (det)
mdb> continue
      E2:     C2  2 CALL pred tabled_read_unitize:unitize/4-0 (det)
mdb> finish -a
      E3:     C2  2 THEN pred tabled_read_unitize:unitize/4-0 (det) t;
      E4:     C2  2 ELSE pred tabled_read_unitize:unitize/4-0 (det) t;c2;e;
      E5:     C2  2 EXIT pred tabled_read_unitize:unitize/4-0 (det)
mdb> retry -f
      E2:     C2  2 CALL pred tabled_read_unitize:unitize/4-0 (det)
mdb> continue -S
123
4506
789
