      E1:     C1 CALL pred tabled_typeclass.main/2-0 (det) tabled_typeclass.m:30
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> finish
1
2
3
4
5
6
      E2:     C1 EXIT pred tabled_typeclass.main/2-0 (det)
mdb> print io *
action 0: tc_action("the arguments are not available due to the presence of one or more type class constraints")
action 1: write_int(1)
action 2: write_char('\n')
action 3: notc_action(status, status_success, 2)
action 4: write_int(2)
action 5: write_char('\n')
action 6: tc_action("the arguments are not available due to the presence of one or more type class constraints")
action 7: write_int(3)
action 8: write_char('\n')
action 9: notc_action(status, status_no_memory, 4)
action 10: write_int(4)
action 11: write_char('\n')
action 12: tc_action("the arguments are not available due to the presence of one or more type class constraints")
action 13: write_int(5)
action 14: write_char('\n')
action 15: notc_action(status, status_null_pointer, 6)
action 16: write_int(6)
action 17: write_char('\n')
mdb> retry -f
      E1:     C1 CALL pred tabled_typeclass.main/2-0 (det)
mdb> continue
