      E1:     C1 CALL pred tabled_read_unitize.main/2-0 (det) tabled_read_unitize.m:22
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> context none
Contexts will not be printed.
mdb> table_io allow
mdb> table_io start
I/O tabling started.
mdb> break unitize
 0: + stop  interface pred tabled_read_unitize.unitize/4-0 (det)
mdb> continue
      E2:     C2 CALL pred tabled_read_unitize.unitize/4-0 (det)
mdb> finish -a
      E3:     C2 EXIT pred tabled_read_unitize.unitize/4-0 (det)
mdb> retry -f
      E2:     C2 CALL pred tabled_read_unitize.unitize/4-0 (det)
mdb> continue -S
123
4506
789
