      E1:     C1  1 CALL pred type_desc_test.main/2-0 (det) type_desc_test.m:21
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break get_type_desc
 0: + stop  interface func type_desc_test.get_type_desc/1-0 (det)
mdb> break get_type_ctor_desc
 1: + stop  interface func type_desc_test.get_type_ctor_desc/1-0 (det)
mdb> continue
      E2:     C2  3 CALL func type_desc_test.get_type_desc/1-0 (det)
mdb> finish
      E3:     C2  3 EXIT func type_desc_test.get_type_desc/1-0 (det)
mdb> print *
       Val (arg 1)            	[1, 2]
       HeadVar__2             	list.list(int)
mdb> continue
type_desc: list.list(int)
      E4:     C3  3 CALL func type_desc_test.get_type_ctor_desc/1-0 (det)
mdb> finish
      E5:     C3  3 EXIT func type_desc_test.get_type_ctor_desc/1-0 (det)
mdb> print *
       TypeDesc (arg 1)       	list.list(int)
       HeadVar__2             	list.list/1
mdb> continue
type_ctor_desc: list.list/1
      E6:     C4  3 CALL func type_desc_test.get_type_desc/1-0 (det)
mdb> finish
      E7:     C4  3 EXIT func type_desc_test.get_type_desc/1-0 (det)
mdb> print *
       Val (arg 1)            	["one", "two", "three"]
       HeadVar__2             	list.list(string)
mdb> continue
type_desc: list.list(string)
      E8:     C5  3 CALL func type_desc_test.get_type_ctor_desc/1-0 (det)
mdb> finish
      E9:     C5  3 EXIT func type_desc_test.get_type_ctor_desc/1-0 (det)
mdb> print *
       TypeDesc (arg 1)       	list.list(string)
       HeadVar__2             	list.list/1
mdb> continue -S
type_ctor_desc: list.list/1
