      E1:     C1 CALL pred uci.main/2-0 (det) uci.m:22
mdb> echo on
Command echo enabled.
mdb> context none
Contexts will not be printed.
mdb> register --quiet
mdb> break -A unif*uci.
 0: + stop  interface __Unify__ for uci.i/3-0 (semidet)
 1: + stop  interface __Unify__ for uci.t0/0-0 (semidet)
 2: + stop  interface __Unify__ for uci.t1/1-0 (semidet)
 3: + stop  interface __Unify__ for uci.t2/2-0 (semidet)
 4: + stop  interface __Unify__ for uci.t3/3-0 (semidet)
 5: + stop  interface __Unify__ for uci.t4/4-0 (semidet)
mdb> break -A comp*uci.
 6: + stop  interface __Compare__ for uci.i/3-0 (det)
 7: + stop  interface __Compare__ for uci.t0/0-0 (det)
 8: + stop  interface __Compare__ for uci.t1/1-0 (det)
 9: + stop  interface __Compare__ for uci.t2/2-0 (det)
10: + stop  interface __Compare__ for uci.t3/3-0 (det)
11: + stop  interface __Compare__ for uci.t4/4-0 (det)
mdb> c
      E2:     C2 CALL __Compare__ for uci.t1/1-0 (det)
mdb> print goal
__Compare__(_, b1(11), a1(1))
mdb> c
      E3:     C2 EXIT __Compare__ for uci.t1/1-0 (det)
mdb> print goal
__Compare__('>', b1(11), a1(1))
mdb> c
      E4:     C3 CALL __Compare__ for uci.t2/2-0 (det)
mdb> print goal
__Compare__(_, a2(1, 2), a2(1, 2))
mdb> c
      E5:     C3 EXIT __Compare__ for uci.t2/2-0 (det)
mdb> print goal
__Compare__('=', a2(1, 2), a2(1, 2))
mdb> c
      E6:     C4 CALL __Compare__ for uci.t3/3-0 (det)
mdb> print goal
__Compare__(_, b3(11, 12, 13), a3(1, 2, 3))
mdb> c
      E7:     C4 EXIT __Compare__ for uci.t3/3-0 (det)
mdb> print goal
__Compare__('>', b3(11, 12, 13), a3(1, 2, 3))
mdb> c
      E8:     C5 CALL __Compare__ for uci.t4/4-0 (det)
mdb> print goal
__Compare__(_, a4(1, 2, 3, 4), b4(11, 12, 13, 14))
mdb> c
      E9:     C5 EXIT __Compare__ for uci.t4/4-0 (det)
mdb> print goal
__Compare__('<', a4(1, 2, 3, 4), b4(11, 12, 13, 14))
mdb> c
     E10:     C6 CALL __Unify__ for uci.t1/1-0 (semidet)
mdb> print goal
__Unify__(a1(1), a1(1))
mdb> c
     E11:     C6 EXIT __Unify__ for uci.t1/1-0 (semidet)
mdb> print goal
__Unify__(a1(1), a1(1))
mdb> c
     E12:     C7 CALL __Unify__ for uci.t2/2-0 (semidet)
mdb> print goal
__Unify__(a2(1, 2), b2(11, 12))
mdb> c
     E13:     C7 FAIL __Unify__ for uci.t2/2-0 (semidet)
mdb> print goal
__Unify__(a2(1, 2), b2(11, 12))
mdb> c
     E14:     C8 CALL __Unify__ for uci.t3/3-0 (semidet)
mdb> print goal
__Unify__(b3(11, 12, 13), b3(11, 12, 13))
mdb> c
     E15:     C8 EXIT __Unify__ for uci.t3/3-0 (semidet)
mdb> print goal
__Unify__(b3(11, 12, 13), b3(11, 12, 13))
mdb> c
     E16:     C9 CALL __Unify__ for uci.t4/4-0 (semidet)
mdb> print goal
__Unify__(a4(1, 2, 3, 4), b4(11, 12, 13, 14))
mdb> c
     E17:     C9 FAIL __Unify__ for uci.t4/4-0 (semidet)
mdb> print goal
__Unify__(a4(1, 2, 3, 4), b4(11, 12, 13, 14))
mdb> c
     E18:    C10 CALL __Compare__ for uci.i/3-0 (det)
mdb> print goal
__Compare__(_, ai(1), bi(11))
mdb> c
     E19:    C10 EXIT __Compare__ for uci.i/3-0 (det)
mdb> print goal
__Compare__('<', ai(1), bi(11))
mdb> c
0 lt
1 ge
2 ge
3 ge
4 lt
0 ne
1 eq
2 ne
3 eq
4 ne
i lt
