      E1:     C1 CALL pred user_event_shallow.main/2-0 (cc_multi) user_event_shallow.m:20
mdb> echo on
Command echo enabled.
mdb> register --quiet
mdb> user
      E2:     C2 USER <safe_test> pred user_event_shallow.queen/2-0 (nondet) c3; user_event_shallow.m:36
mdb> retry
Cannot perform retry because information about the input arguments is not available.
mdb> print *
       test_list (attr 0, Out)	[1, 2, 3, 4, 5]
       Data (arg 1)           	[1, 2, 3, 4, 5]
mdb> browse !test_list
browser> p
[1, 2, 3, 4, 5]
browser> ^2^1
browser> p
2
browser> quit
mdb> user_event_context proc
User events will get only procedure contexts printed.
mdb> user
      E3:     C3 USER <nodiag_fail> pred user_event_shallow.nodiag/3-0 (semidet) s2-2;c4;t;c2;
mdb> user_event_context none
User events will get no contexts printed.
mdb> current
      E3:     C3 USER <nodiag_fail> 
mdb> user_event_context
User events get no contexts printed.
mdb> user_event_context full
User events will get full contexts printed.
mdb> current
      E3:     C3 USER <nodiag_fail> pred user_event_shallow.nodiag/3-0 (semidet) s2-2;c4;t;c2; user_event_shallow.m:71
mdb> user_event_context file
User events will get only file contexts printed.
mdb> current
      E3:     C3 USER <nodiag_fail>  user_event_shallow.m:71
mdb> vars
        1 test_failed (attr 0)
        2 arg_b (attr 1, B)
        3 arg_d (attr 2, N)
        4 arg_list (attr 3, HeadVar__3)
        5 B (arg 1)
        6 D (arg 2)
        7 HeadVar__3
        8 BmN
        9 L
       10 N
       11 NmB
mdb> print *
       test_failed (attr 0)   	"N - B"
       arg_b (attr 1, B)      	1
       arg_d (attr 2, N)      	2
       arg_list (attr 3, HeadVar__3)	[2, 3, 4, 5]
       D (arg 2)              	1
       BmN                    	-1
       L                      	[3, 4, 5]
       NmB                    	1
mdb> print !arg_b
       arg_b (attr 1, B)      	1
mdb> user
      E4:     C2 USER <safe_test>  user_event_shallow.m:36
mdb> print *
       test_list (attr 0, Out)	[1, 2, 3, 5, 4]
       Data (arg 1)           	[1, 2, 3, 4, 5]
mdb> continue
[1, 3, 5, 2, 4]
