#!/bin/sh
# Print the names of .int and .int2 files in the current directory
# that do not have a .m file with the same name.

for file in *.int
do
	if test ! -f `basename $file .int`.m
	then
		echo $file ${file}2
	fi
done

exit 0
