#!/usr/bin/awk -f
	{
		rep[$2] = 1;
		all += $3;
		pred[$1] += $3;
		kind[$1 "-" $2] += $3;
	}
END	{
		for (p in pred)
		{
			for (r in rep)
			{
				printf "%-8s %-20s %15d (%5.2f%%)\n", p, r ":", kind[p "-" r], (100 * kind[p "-" r]) / pred[p];
			}

			printf "%-29s %15d (%5.2f%%)\n\n", p ":", pred[p], (100 * pred[p]) / all;
		}
	}
