#!/bin/sh
#
# This script performs a diff between the main directories of two Mercury
# workspaces. It is meant to be useful if you are not connected to a network
# and therefore unable to "cvs add" files; in such circumstances, doing a
# "cvdd clean_ws work_ws" can be a sufficiently good substitute for a
# "cvd diff work_ws". It is not intended to be a full replacement, e.g.
# it doesn't do anything meaningful if you add an entire new directory.
#
# Normally, the script restricts its attention to files and directories
# that are either under CVS control or whose names appear in a file called
# NEWFILES (for files) or NEWDIRS (for directories). If you specify the -e
# option, the script will also look at files with the name given as the
# argument of -e. The intended use is "cvdd -e Log", which includes any changes
# in Log files to be reflected in the output. This is useful when backing up
# a workspace.

pathname="."
extras=""
extraopts=""
diffopts=""

while test $# -gt 0
do
	case "$1" in
	-e)
		extras="$extras $2"
		extraopts="$extraopts -e $2"
		shift ; shift
		;;
	-p)
		pathname="$2"
		shift ; shift
		;;
	-*)
		diffopts="$diffopts $1"
		shift
		;;
	*)
		break ;;
	esac
done

usage="usage: cvdd [-e filename] dir1 dir2"

if test "$diffopts" = ""
then
	# these are the default diff options
	diffopts="-ubB"
fi

if test $# -ne 2
then
	echo "$usage"
	exit 1
fi

if test ! -d "$1" -o ! -d "$2"
then
	echo "$usage"
	exit 1
fi

case "$pathname" in
./*)
	pathname=`expr $pathname : '\./\(.*\)'`
	;;
esac

echo "Diffing $pathname"

filelist="/tmp/cvdd_files$$"
dirlist="/tmp/cvdd_dirs$$"
trap "/bin/rm -f $filelist $dirlist > /dev/null 2>&1; exit 0" 0
trap "/bin/rm -f $filelist $dirlist > /dev/null 2>&1; exit 1" 1 2 3 15

(
	cvsfiles $1
	cvsfiles $2
	if test -f $1/NEWFILES
	then
		cat $1/NEWFILES
	fi
	if test -f $2/NEWFILES
	then
		cat $2/NEWFILES
	fi
	for extra in "$extras"
	do
		extra=`echo $extra | sed -e 's/^ *//'`
		if test -f "$1/$extra" -o -f "$2/$extra"
		then
			echo $extra
		fi
	done
) | sort -u > $filelist

(
	cvsdirs $1
	cvsdirs $2
	if test -f $1/NEWDIRS
	then
		cat $1/NEWDIRS
	fi
	if test -f $2/NEWDIRS
	then
		cat $2/NEWDIRS
	fi
) | sort -u > $dirlist

for file in `cat $filelist`
do
	if test -f "$1/$file" -a -f "$2/$file"
	then
		diff $diffopts "$1/$file" "$2/$file"
	elif test -f "$1/$file"
	then
		echo "old file $1/$file"
		cat "$1/$file"
	elif test -f "$2/$file"
	then
		echo "new file $2/$file"
		cat "$2/$file"
	else
		echo "neither $1/$file nor $2/$file exist"
	fi
done

for dir in `cat $dirlist`
do
	if test -d "$1/$dir/CVS" -a -d "$2/$dir/CVS"
	then
		cvdd -p "$pathname/$dir" $extraopts $diffopts "$1/$dir" "$2/$dir"
	elif test -d "$1/$dir/CVS"
	then
		echo "old dir $1/$dir"
		if test -f "$1/$dir/NEWDIRFILES"
		then
			more `cat $1/$dir/NEWDIRFILES`
		else
			more $1/$dir/*
		fi
	elif test -d "$2/$dir/CVS"
	then
		echo "new dir $2/$dir"
		if test -f "$2/$dir/NEWDIRFILES"
		then
			more `cat $2/$dir/NEWDIRFILES`
		else
			more $2/$dir/*
		fi
	else
		echo "neither $1/$dir nor $2/$dir are under CVS control"
	fi
done
