#!/bin/sh
#---------------------------------------------------------------------------#
# Copyright (C) 2001 The University of Melbourne.
# This file may only be copied under the terms of the GNU General
# Public License - see the file COPYING in the Mercury distribution.
#---------------------------------------------------------------------------#
#
# This shell script allows you to execute a version of the Mercury compiler
# that you have built in a workspace. Everything that the compilation process
# needs will come from that workspace: the libraries for the runtime system,
# the trace system, the Mercury standard library, the Boehm collector, etc.
# You specify the directory containing the workspace by setting the value of
# the WORKSPACE environment variable. This can be done by setting up a small
# shell script for each workspace you have:
#
# #!/bin/sh
# WORKSPACE=$HOME/mer/ws1
# export WORKSPACE
# $WORKSPACE/tools/lmc "$@"
#
# If you want to track down some C level bug, you can ask this script to
# pass -g to the C compiler and to the linker by setting the environment
# variable MMC_CDEBUG to the string "true".
#
# If you want to track down some low level bug, you can ask this script to
# execute the Mercury compiler under gdb by setting the environment variable
# MMC_UNDER_GDB to the string "true".

MERCURY_COMPILER=$WORKSPACE/compiler/mercury_compile
export MERCURY_COMPILER

if test ! -d $WORKSPACE
then
	echo "workspace $WORKSPACE does not exist"
fi

if test -s $WORKSPACE/boehm_gc/libgc.a
then
	gclib="$WORKSPACE/boehm_gc/libgc.a"
elif test -s $WORKSPACE/boehm_gc/libpar_gc.a
then
	gclib="$WORKSPACE/boehm_gc/libpar_gc.a"
elif test -s $WORKSPACE/boehm_gc/libgc_prof.a
then
	gclib="$WORKSPACE/boehm_gc/libgc_prof.a"
else
	echo "$WORKSPACE/boehm_gc does not have a gc library"
fi

LIB_FLAGS="--link-object $WORKSPACE/trace/libmer_trace.a --link-object $WORKSPACE/browser/libmer_browser.a --link-object $WORKSPACE/library/libmer_std.a --link-object $WORKSPACE/runtime/libmer_rt.a --link-object $gclib -lm"
INIT_FLAGS="--trace-init-file $WORKSPACE/browser/mer_browser.init --init-file $WORKSPACE/library/mer_std.init --init-file $WORKSPACE/runtime/mer_rt.init"

if test "$MMC_CDEBUG" != ""
then
	CDEBUG_FLAGS="--link-flags -g --cflags -g"
else
	CDEBUG_FLAGS=""
fi

C_FLAGS="--c-include-directory $WORKSPACE/trace --c-include-directory $WORKSPACE/library --c-include-directory $WORKSPACE/runtime --c-include-directory $WORKSPACE/boehm_gc --c-include-directory $WORKSPACE/boehm_gc/include"

if test "$MMC_UNDER_GDB" != ""
then
	MERCURY_COMPILER="$WORKSPACE/tools/gdbrun $MERCURY_COMPILER"
	export MERCURY_COMPILER
fi

PATH="$WORKSPACE/scripts:$WORKSPACE/util:$PATH"
export PATH
mmc --no-mercury-stdlib-dir -I $WORKSPACE/library $CDEBUG_FLAGS $C_FLAGS $INIT_FLAGS $LIB_FLAGS "$@"
