#!/usr/bin/awk -f
# vim: ft=awk ts=4 sw=4 et
BEGIN {
        for (i = 2; i <= 24; i++) {
            init[i] = "not accessed";
            make[i] = "not accessed";
        }

        desc[2]  = "SrcFileName";
        desc[3]  = "SrcFileDir";
        desc[4]  = "SrcFileModuleName";
        desc[5]  = "MaybeTopModule";
        desc[6]  = "IntDepsMap";
        desc[7]  = "ImpDepsMap";
        desc[8]  = "IndirectDeps";
        desc[9]  = "FIMs";
        desc[10] = "ForeignIncludeFiles";
        desc[11] = "HasForeignCode";
        desc[12] = "HasForeignExport";
        desc[13] = "ParseTreeModuleSrc";
        desc[14] = "AncestorSpecs";
        desc[15] = "DirectIntSpecs";
        desc[16] = "IndirectIntSpecs";
        desc[17] = "PlainOpts";
        desc[18] = "TransOpts";
        desc[19] = "IntForOptSpecs";
        desc[20] = "TypeRepnSpecs";
        desc[21] = "VersionNumbersMap";
        desc[22] = "MaybeTimestampMap";
        desc[23] = "Specs";
        desc[24] = "Errors";

}
$1 == "INIT" && NF == 24 {
        for (i = 2; i <= 24; i++) {
            if ($i == "a") {
                init[i] = "accessed";
            }
        }
    }
$1 == "MAKE" && NF == 24 {
        for (i = 2; i <= 24; i++) {
            if ($i == "a") {
                make[i] = "accessed";
            }
        }
    }
END {
        for (i = 2; i <= 24; i++) {
            printf "%-20s init %12s make %12s\n",
                desc[i], init[i], make[i];
        }
    }
