ambiguous_overloading.m:041: In clause for predicate `ambig_overload1'/1:
ambiguous_overloading.m:041:   warning: highly ambiguous overloading.
ambiguous_overloading.m:041:   The following symbol was overloaded in the
ambiguous_overloading.m:041:   following context.
ambiguous_overloading.m:041:   The function symbol `f'/0.
ambiguous_overloading.m:041:   The possible matches are:
ambiguous_overloading.m:041:     the type constructor
ambiguous_overloading.m:041:     `ambiguous_overloading.bar'/0,
ambiguous_overloading.m:041:     the type constructor
ambiguous_overloading.m:041:     `ambiguous_overloading.foo'/0,
ambiguous_overloading.m:041:     the builtin type constructor `character'.
ambiguous_overloading.m:045: In clause for predicate `ambig_overload2'/1:
ambiguous_overloading.m:045:   warning: highly ambiguous overloading.
ambiguous_overloading.m:045:   The following symbols were overloaded in the
ambiguous_overloading.m:045:   following contexts.
ambiguous_overloading.m:045:   The function symbol `a1'/0.
ambiguous_overloading.m:045:   The possible matches are:
ambiguous_overloading.m:045:     the type constructor
ambiguous_overloading.m:045:     `ambiguous_overloading.baz'/0,
ambiguous_overloading.m:045:     the type constructor
ambiguous_overloading.m:045:     `ambiguous_overloading.qux'/0.
ambiguous_overloading.m:045:   The function symbol `a2'/0.
ambiguous_overloading.m:045:   The possible matches are:
ambiguous_overloading.m:045:     the type constructor
ambiguous_overloading.m:045:     `ambiguous_overloading.baz'/0,
ambiguous_overloading.m:045:     the type constructor
ambiguous_overloading.m:045:     `ambiguous_overloading.qux'/0.
ambiguous_overloading.m:056: In clause for predicate `test_lt'/1:
ambiguous_overloading.m:056:   warning: highly ambiguous overloading.
ambiguous_overloading.m:056:   The following symbol was overloaded in the
ambiguous_overloading.m:056:   following contexts.
ambiguous_overloading.m:050:   The predicate symbol predicate `<'/2.
ambiguous_overloading.m:050:   The possible matches are:
ambiguous_overloading.m:050:     predicate `int.<'/2,
ambiguous_overloading.m:050:     predicate `float.<'/2.
ambiguous_overloading.m:051:   The predicate symbol predicate `<'/2 is also
ambiguous_overloading.m:051:   overloaded here.
ambiguous_overloading.m:052:   The predicate symbol predicate `<'/2 is also
ambiguous_overloading.m:052:   overloaded here.
ambiguous_overloading.m:053:   The predicate symbol predicate `<'/2 is also
ambiguous_overloading.m:053:   overloaded here.
ambiguous_overloading.m:054:   The predicate symbol predicate `<'/2 is also
ambiguous_overloading.m:054:   overloaded here.
ambiguous_overloading.m:055:   The predicate symbol predicate `<'/2 is also
ambiguous_overloading.m:055:   overloaded here.
ambiguous_overloading.m:077: In clause for predicate
ambiguous_overloading.m:077:   `set_browser_param_from_option_table'/3:
ambiguous_overloading.m:077:   warning: highly ambiguous overloading.
ambiguous_overloading.m:077:   The following symbol was overloaded in the
ambiguous_overloading.m:077:   following contexts.
ambiguous_overloading.m:072:   The function symbol `lookup_bool_option'/2.
ambiguous_overloading.m:072:   The possible matches are:
ambiguous_overloading.m:072:     predicate `getopt.lookup_bool_option'/3,
ambiguous_overloading.m:072:     function `getopt.lookup_bool_option'/2.
ambiguous_overloading.m:073:   The function symbol `lookup_bool_option'/2 is
ambiguous_overloading.m:073:   also overloaded here.
ambiguous_overloading.m:074:   The function symbol `lookup_bool_option'/2 is
ambiguous_overloading.m:074:   also overloaded here.
ambiguous_overloading.m:075:   The function symbol `lookup_bool_option'/2 is
ambiguous_overloading.m:075:   also overloaded here.
ambiguous_overloading.m:076:   The function symbol `lookup_bool_option'/2 is
ambiguous_overloading.m:076:   also overloaded here.
ambiguous_overloading.m:077:   The function symbol `lookup_bool_option'/2 is
ambiguous_overloading.m:077:   also overloaded here.
