inconsistent_pred_order.m:010: Warning: the order of the declarations and
inconsistent_pred_order.m:010:   definitions of the nonexported predicates is
inconsistent_pred_order.m:010:   inconsistent, as shown by this diff:
inconsistent_pred_order.m:010:   
inconsistent_pred_order.m:010:   --- declaration order
inconsistent_pred_order.m:010:   +++ definition order
inconsistent_pred_order.m:010:    predicate `data'/1
inconsistent_pred_order.m:010:    predicate `queen'/2
inconsistent_pred_order.m:010:    predicate `qperm'/2
inconsistent_pred_order.m:010:   -predicate `safe'/1
inconsistent_pred_order.m:010:    predicate `qdelete'/3
inconsistent_pred_order.m:010:   -predicate `print_list'/3
inconsistent_pred_order.m:010:   +predicate `safe'/1
inconsistent_pred_order.m:010:    predicate `nodiag'/3
inconsistent_pred_order.m:010:   +predicate `print_list'/3
inconsistent_pred_order.m:010:    predicate `print_list_elements'/4
