inst_with_no_type.m:018: Warning: inst `inst_with_no_type.i1_no_match'/0 does
inst_with_no_type.m:018:   not match any of the types in scope.
inst_with_no_type.m:039: Warning: inst `inst_with_no_type.i2_no_match'/1 does
inst_with_no_type.m:039:   not match any of the types in scope.
inst_with_no_type.m:050: Warning: inst `inst_with_no_type.i4_no_match'/0 does
inst_with_no_type.m:050:   not match any of the types in scope.
inst_with_no_type.m:063: Warning: inst `inst_with_no_type.i7_no_match'/0 does
inst_with_no_type.m:063:   not match any of the types in scope.
inst_with_no_type.m:074: Warning: inst `inst_with_no_type.mostly_unique_inst'/0
inst_with_no_type.m:074:   does not match any of the types in scope.
inst_with_no_type.m:076: Warning: inst
inst_with_no_type.m:076:   `inst_with_no_type.mostly_unique_no_match'/0 does
inst_with_no_type.m:076:   not match any of the types in scope.
inst_with_no_type.m:078: Warning: inst `inst_with_no_type.unique_inst'/0 does
inst_with_no_type.m:078:   not match any of the types in scope.
inst_with_no_type.m:080: Warning: inst `inst_with_no_type.unique_no_match'/0
inst_with_no_type.m:080:   does not match any of the types in scope.
inst_with_no_type.m:083: Warning: inst `inst_with_no_type.citrus'/0 does not
inst_with_no_type.m:083:   match any of the types in scope.
inst_with_no_type.m:095: Warning: inst `inst_with_no_type.t_no_match'/0 does
inst_with_no_type.m:095:   not match any of the types in scope.
