purity_warnings.m:030: In call to predicate `io.write_string'/3:
purity_warnings.m:030:   warning: [38;5;203munnecessary `semipure' indicator.[39;49m
purity_warnings.m:030:   No purity indicator is necessary.
purity_warnings.m:031: In call to predicate `io.print'/3:
purity_warnings.m:031:   warning: [38;5;203munnecessary `impure' indicator.[39;49m
purity_warnings.m:031:   No purity indicator is necessary.
purity_warnings.m:033: Warning: predicate `impure_pred1'/2 is declared [38;5;40mimpure,[39;49m
purity_warnings.m:033:   but is actually [38;5;203mpure.[39;49m
purity_warnings.m:037: Warning: predicate `impure_pred2'/2 is declared [38;5;40mimpure,[39;49m
purity_warnings.m:037:   but is actually [38;5;203msemipure.[39;49m
purity_warnings.m:045: Warning: predicate `semipure_pred'/2 is declared
purity_warnings.m:045:   [38;5;40msemipure,[39;49m but is actually [38;5;203mpure.[39;49m
purity_warnings.m:047: In call to predicate `io.write_string'/3:
purity_warnings.m:047:   warning: [38;5;203munnecessary `semipure' indicator.[39;49m
purity_warnings.m:047:   No purity indicator is necessary.
purity_warnings.m:077: Warning: predicate `impure_method1a_impl'/2 is declared
purity_warnings.m:077:   [38;5;40mimpure,[39;49m but is actually [38;5;203mpure.[39;49m
purity_warnings.m:079: In call to predicate `io.print'/3:
purity_warnings.m:079:   warning: [38;5;203munnecessary `impure' indicator.[39;49m
purity_warnings.m:079:   No purity indicator is necessary.
purity_warnings.m:089: Warning: predicate `semipure_method_a_impl'/2 is
purity_warnings.m:089:   declared [38;5;40msemipure,[39;49m but is actually [38;5;203mpure.[39;49m
purity_warnings.m:091: In call to predicate `io.print'/3:
purity_warnings.m:091:   warning: [38;5;203munnecessary `semipure' indicator.[39;49m
purity_warnings.m:091:   No purity indicator is necessary.
