#!/bin/sh
# Test whether the compiler is producing the right warnings.
# Return a status of 0 (true) if everything is all right, and 1 otherwise.

. ../handle_options

mmake $jfactor clean > /dev/null 2>&1
mmake $jfactor depend || exit 1
mmake -k $jfactor $gradeopt $flagsopt check
checkstatus=$?

cat *.res > .allres
if test ! -s .allres -a "$checkstatus" = 0
then
	echo "the tests in the warnings directory succeeded"
	exit 0
else
	echo "the tests in the warnings directory failed"
	echo "the differences are:"
	cat .allres
	exit 1
fi
