simple_code.m:014: Warning: this disjunct will never have any solutions.
simple_code.m:019: Warning: the condition of this if-then-else cannot fail.
simple_code.m:022: In clause for `p(in, out)':
simple_code.m:022:   warning: unification of `X' and 2 cannot succeed.
simple_code.m:022:   `X' has instantiatedness `unique(3)'.
simple_code.m:024: Warning: the condition of this if-then-else cannot succeed.
simple_code.m:029: Warning: the condition of this if-then-else cannot succeed.
simple_code.m:032: Warning: the negated goal cannot fail.
simple_code.m:032: Warning: the negated goal cannot succeed.
simple_code.m:034: Warning: the condition of this if-then-else cannot succeed.
simple_code.m:037: Warning: the negated goal cannot succeed.
simple_code.m:039: Warning: the condition of this if-then-else cannot fail.
simple_code.m:043: Warning: call to obsolete predicate
simple_code.m:043:   `simple_code.obsolete1'/0.
simple_code.m:044: Warning: call to obsolete predicate
simple_code.m:044:   `simple_code.obsolete2'/0.
simple_code.m:044:   The suggested replacement is `pred42'/0.
simple_code.m:045: Warning: call to obsolete predicate
simple_code.m:045:   `simple_code.obsolete3'/0.
simple_code.m:045:   The possible suggested replacements are `pred42'/0 and
simple_code.m:045:   `wonderful.pred43'/0.
simple_code.m:048: Warning: the condition of this if-then-else cannot fail.
simple_code.m:080: In clause for `r(in(bound(1)), out(bound(42)))':
simple_code.m:080:   in argument 1 of clause head:
simple_code.m:080:   warning: unification of `HeadVar__1' and 2 cannot succeed.
simple_code.m:080:   `HeadVar__1' has instantiatedness `bound(1)'.
simple_code.m:113: Warning: recursive call to predicate `anc'/2 will lead to
simple_code.m:113:   infinite recursion.
For more information, recompile with `-E'.
