singleton_test.m:008: In function `my_append_func'/2:
singleton_test.m:008:   warning: unresolved polymorphism.
singleton_test.m:008:   The variables with unbound types were:
singleton_test.m:008:     L2: V_1
singleton_test.m:008:     L1: V_1
singleton_test.m:008:   The unbound type variables will be implicitly bound to
singleton_test.m:008:   the builtin type `void'.
singleton_test.m:026: In clause for predicate `singleton_test.my_append'/3:
singleton_test.m:026:   warning: variable `L2' occurs only once in this scope.
singleton_test.m:030: In clause for function `singleton_test.my_append_func'/2:
singleton_test.m:030:   warning: variables `L1, L2' occur only once in this
singleton_test.m:030:   scope.
singleton_test.m:031: In clause for function `singleton_test.my_append_func'/2:
singleton_test.m:031:   warning: variable `T' occurs only once in this scope.
singleton_test.m:033: In the C code for predicate `singleton_test.my_c_pred'/3:
singleton_test.m:033:   warning: variable `Y' does not occur in the C code.
singleton_test.m:050: In the C code for function `singleton_test.my_c_func'/2:
singleton_test.m:050:   warning: variable `X' does not occur in the C code.
singleton_test.m:069: In the C code for predicate
singleton_test.m:069:   `singleton_test.c_hello_world'/3:
singleton_test.m:069:   warning: variable `Msg' does not occur in the C code.
singleton_test.m:090: In clause for predicate `singleton_test.test_head'/6:
singleton_test.m:090:   warning: variable `_D' occurs more than once in this
singleton_test.m:090:   scope.
singleton_test.m:090: In clause for predicate `singleton_test.test_head'/6:
singleton_test.m:090:   warning: variables `A, B' occur only once in this
singleton_test.m:090:   scope.
