table_with_inline.m:011: Warning: function `table_with_inline.foo'/1 has a
table_with_inline.m:011:   `:- pragma memo' declaration but also has a
table_with_inline.m:011:   `:- pragma inline' declaration.
table_with_inline.m:011:   This inline pragma will be ignored since tabled
table_with_inline.m:011:   predicates cannot be inlined.
table_with_inline.m:011:   You can use the `--no-warn-table-with-inline' option
table_with_inline.m:011:   to suppress this warning.
