warn_succ_ind.m:030: Warning: the C code for predicate `warn_succ_ind.foo'/2
warn_succ_ind.m:030:   may set `SUCCESS_INDICATOR', but it cannot fail.
warn_succ_ind.m:062: Warning: the C code for predicate `warn_succ_ind.foo2'/2
warn_succ_ind.m:062:   may set `SUCCESS_INDICATOR', but it cannot fail.
warn_succ_ind.m:094: Warning: the C code for predicate `warn_succ_ind.bar'/2
warn_succ_ind.m:094:   does not appear to set `SUCCESS_INDICATOR', but it can
warn_succ_ind.m:094:   fail.
warn_succ_ind.m:122: Warning: the C code for predicate `warn_succ_ind.bar2'/2
warn_succ_ind.m:122:   does not appear to set `SUCCESS_INDICATOR', but it can
warn_succ_ind.m:122:   fail.
