before: 1 0
>> enter (1)
inside: 1 1
<< leave (1)
after: 1 1
=> fail back inside: 1
inside: 1 2
<< leave (1)
after: 1 2
=> fail back inside: 1
inside: 1 3
<< leave (1)
after: 1 3
=> fail back inside: 1
<= fail back outside: 1
before: 2 0
>> enter (2)
inside: 2 1
<< leave (2)
after: 2 1
=> fail back inside: 2
inside: 2 2
<< leave (2)
after: 2 2
=> fail back inside: 2
inside: 2 3
<< leave (2)
after: 2 3
=> fail back inside: 2
<= fail back outside: 2
before: 3 0
>> enter (3)
inside: 3 1
<< leave (3)
after: 3 1
=> fail back inside: 3
inside: 3 2
<< leave (3)
after: 3 2
=> fail back inside: 3
inside: 3 3
<< leave (3)
after: 3 3
=> fail back inside: 3
<= fail back outside: 3
Failure
