[morphine 1]: 
**************************************************
**** Testing test_vars.m...
Start debugging test_vars program.
				       
---------------------------------
[./test_vars ...]			       
				       
  1: 1 [1] call main(state('<<c_pointer>>'), -) [] 
  3:  2 [2] exit p(3 - 8) [] 
[3 - 8]
---------------------------------
End of connection with the traced program
test_vars: ok.

Arg = [3 - 8]
[morphine 2]: 
bye
